enum ActivatableBase {
  // <db-replace-token>
  eigenerVorteil("ADV_0", "Eigener Vorteil", "", {}),
  adel("ADV_1", "Adel", "", {}),
  altersresistenz("ADV_2", "Altersresistenz", "", {}),
  angenehmerGeruch("ADV_3", "Angenehmer Geruch", "", {}),
  begabung("ADV_4", "Begabung", "", {}),
  beidhaendig("ADV_5", "Beidhändig", "", {}),
  dunkelsicht("ADV_6", "Dunkelsicht", "", {}),
  eisenaffineAura("ADV_7", "Eisenaffine Aura", "", {}),
  entfernungssinn("ADV_8", "Entfernungssinn", "", {}),
  flink("ADV_9", "Flink", "", {}),
  fuchssinn("ADV_10", "Fuchssinn", "", {}),
  geborenerRedner("ADV_11", "Geborener Redner", "", {}),
  geweihter("ADV_12", "Geweihter", "", {}),
  giftresistenz("ADV_13", "Giftresistenz", "", {}),
  glueck("ADV_14", "Glück", "", {}),
  gutaussehend("ADV_15", "Gutaussehend", "", {}),
  herausragendeFertigkeit("ADV_16", "Herausragende Fertigkeit", "", {}),
  herausragendeKampftechnik("ADV_17", "Herausragende Kampftechnik", "", {}),
  herausragenderSinn("ADV_18", "Herausragender Sinn", "", {
    1: "Sicht",
    2: "Gehör",
    3: "Geruch & Geschmack",
    4: "Tastsinn",
  }),
  hitzeresistenz("ADV_22", "Hitzeresistenz", "", {}),
  hoheAstralkraft("ADV_23", "Hohe Astralkraft", "", {}),
  hoheKarmalkraft("ADV_24", "Hohe Karmalkraft", "", {}),
  hoheLebenskraft("ADV_25", "Hohe Lebenskraft", "", {}),
  hoheSeelenkraft("ADV_26", "Hohe Seelenkraft", "", {}),
  hoheZaehigkeit("ADV_27", "Hohe Zähigkeit", "", {}),
  immunitaetGegenGift("ADV_28", "Immunität gegen", "", {
    1: "Arax",
    2: "Kelmon",
    3: "Tulmadron",
    4: "Wurara",
    5: "Kukris",
    6: "Mandragora",
    7: "Omrais",
    8: "Sunsura",
    9: "Höhlenspinnengift",
    10: "Krötengift",
    11: "Rattenpilzgift",
    12: "Ghulgift",
    13: "Mantikorgift",
    14: "Morfugift",
    15: "Brabacudagift",
    16: "Gelbschwanzskorpiongift",
    17: "Kvillottergift",
    18: "Vogelspinnengift",
    19: "Seilschlangengift",
    20: "Speikobragift",
    21: "Alkohol",
    22: "Angstgift",
    23: "Arachnae",
    24: "Betäubungsgift",
    25: "Boabungaha",
    26: "Charyb‘Ytt‘ Traum",
    27: "Drachenspeichel",
    28: "Feuerzunge",
    29: "Gonede",
    30: "Halbgift",
    31: "Hollbeerenbrechmittel",
    32: "Höhlenbovistgift",
    33: "Marbos Ruhe",
    34: "Margolaschabführmittel",
    35: "Purpurblitz",
    36: "Schattenneblergift",
    37: "Schwarzer Lotus",
    38: "Tinzal",
    39: "Urkaritgift",
    40: "Visarnetgift",
  }),
  immunitaetGegenKrankheit("ADV_29", "Immunität gegen", "", {
    1: "Flinker Difar",
    2: "Lutanas",
    3: "Rascher Wahn",
    4: "Sumpffieber/Brabaker Schweiß",
    5: "Zorganpocken",
    6: "Aussatz",
    7: "Blaue Keuche",
    8: "Blutiger Rotz",
    9: "Dumpfschädel",
    10: "Efferd-/Kerkersieche",
    11: "Gilbe/Schlachtfeldfieber",
    12: "Jahresfieber",
    13: "Schwarze Wut",
    14: "Tollwut",
    15: "Wundfieber",
    16: "Augenpest",
    17: "Paralyse/Basiliskenblick",
    18: "Blutkrächzen",
    19: "Grasse",
    20: "Gänsepusteln",
    21: "Herbstpocken",
    22: "Horasierkrankheit",
    23: "Karmesin",
    24: "Leichenblässe",
    25: "Lykanthropie",
    26: "Marder-/Orkenkrätze",
    27: "Rotbacke",
    28: "Schlafkrankheit",
    29: "Triefnase",
    30: "Bleiche Sieche",
    31: "Reißwasserseuche",
  }),
  kaelteresistenz("ADV_30", "Kälteresistenz", "", {}),
  krankheitsresistenz("ADV_31", "Krankheitsresistenz", "", {}),
  magischeEinstimmung("ADV_32", "Magische Einstimmung", "", {
    1: "Wesen der Auen",
    2: "Wesen der Berge",
    3: "Wesen des Eises",
    4: "Wesen der Meere",
    5: "Wesen der Nacht",
    6: "Wesen des Waldes",
  }),
  mystiker("ADV_33", "Mystiker", "", {}),
  nichtschlaefer("ADV_34", "Nichtschläfer", "", {}),
  pragmatiker("ADV_35", "Pragmatiker", "", {}),
  reich("ADV_36", "Reich", "", {}),
  richtungssinn("ADV_37", "Richtungssinn", "", {}),
  schlangenmensch("ADV_38", "Schlangenmensch", "", {}),
  schwerZuVerzaubern("ADV_39", "Schwer zu verzaubern", "", {}),
  sozialeAnpassungsfaehigkeit("ADV_40", "Soziale Anpassungsfähigkeit", "", {}),
  unscheinbar("ADV_41", "Unscheinbar", "", {}),
  verbesserteRegenerationAstralenergie(
    "ADV_42",
    "Verbesserte Regeneration (Astralenergie)",
    "",
    {},
  ),
  verbesserteRegenerationKarmaenergie(
    "ADV_43",
    "Verbesserte Regeneration (Karmaenergie)",
    "",
    {},
  ),
  verbesserteRegenerationLebensenergie(
    "ADV_44",
    "Verbesserte Regeneration (Lebensenergie)",
    "",
    {},
  ),
  verhuellteAura("ADV_45", "Verhüllte Aura", "", {}),
  vertrauenerweckend("ADV_46", "Vertrauenerweckend", "", {}),
  waffenbegabung("ADV_47", "Waffenbegabung", "", {}),
  wohlklang("ADV_48", "Wohlklang", "", {}),
  zaeherHund("ADV_49", "Zäher Hund", "", {}),
  zauberer("ADV_50", "Zauberer", "", {}),
  zeitgefuehl("ADV_51", "Zeitgefühl", "", {}),
  zweistimmigerGesang("ADV_52", "Zweistimmiger Gesang", "", {}),
  zwergennase("ADV_53", "Zwergennase", "", {}),
  eisern("ADV_54", "Eisern", "", {}),
  hartImNehmen("ADV_55", "Hart im nehmen", "", {}),
  affinitaetZuDaemonen("ADV_56", "Affinität zu Dämonen", "", {}),
  affinitaetZuElementaren("ADV_57", "Affinität zu Elementaren", "", {}),
  grosseZauberauswahl("ADV_58", "Große Zauberauswahl", "", {}),
  keinBannDesEisen("ADV_59", "Kein Bann des Eisen", "", {}),
  machtvolleZaubermelodien("ADV_60", "Machtvolle Zaubermelodien", "", {}),
  machtvolleZaubertaenze("ADV_61", "Machtvolle Zaubertänze", "", {}),
  schutzgeist("ADV_62", "Schutzgeist", "", {}),
  weitreichendeZaubermelodien("ADV_63", "Weitreichende Zaubermelodien", "", {}),
  weitreichendeZaubertaenze("ADV_64", "Weitreichende Zaubertänze", "", {}),
  basiliskentoeter("ADV_65", "Basiliskentöter", "", {}),
  drachentoeter("ADV_66", "Drachentöter", "", {}),
  feenfreund("ADV_67", "Feenfreund", "", {}),
  hassAuf("ADV_68", "Hass auf", "", {
    1: "Häufig",
    2: "Gelegentlich",
    3: "Selten",
  }),
  saumagen("ADV_69", "Saumagen", "", {}),
  tierfreund("ADV_70", "Tierfreund", "", {}),
  wasserlebewesen("ADV_71", "Wasserlebewesen", "", {}),
  allerweltsname("ADV_72", "Allerweltsname", "", {}),
  gutesNamensgedaechtnis("ADV_73", "Gutes Namensgedächtnis", "", {}),
  heldenhafterName("ADV_74", "Heldenhafter Name", "", {}),
  schnellWiederAufDenBeinen("ADV_75", "Schnell wieder auf den Beinen", "", {}),
  akoluth("ADV_76", "Akoluth", "", {}),
  prediger("ADV_77", "Prediger", "", {}),
  visionaer("ADV_78", "Visionär", "", {}),
  zahlreichePredigten("ADV_79", "Zahlreiche Predigten", "", {}),
  zahlreicheVisionen("ADV_80", "Zahlreiche Visionen", "", {}),
  feenblutBluetenfee("ADV_81", "Feenblut (Blütenfee)", "", {}),
  feenblutDryade("ADV_82", "Feenblut (Dryade)", "", {}),
  feenblutGrosserEberbiestinger(
    "ADV_83",
    "Feenblut (Großer Eberbiestinger)",
    "",
    {},
  ),
  feenblutNixer("ADV_84", "Feenblut (Nixer)", "", {}),
  animalischeKraft("ADV_85", "Animalische Kraft", "", {}),
  blumenduft("ADV_86", "Blumenduft", "", {}),
  dickesFell("ADV_87", "Dickes Fell", "", {}),
  einblickeInsVerborgene("ADV_88", "Einblicke ins Verborgene", "", {}),
  glatteHaut("ADV_89", "Glatte Haut", "", {}),
  harmonieDesWaldes("ADV_90", "Harmonie des Waldes", "", {}),
  kraftDerBaeume("ADV_91", "Kraft der Bäume", "", {}),
  leichterGang("ADV_92", "Leichter Gang", "", {}),
  seesprache("ADV_93", "Seesprache", "", {}),
  tierischeKampfgefaehrten("ADV_94", "Tierische Kampfgefährten", "", {}),
  verfuehrerischeGestalt("ADV_95", "Verführerische Gestalt", "", {}),
  wasserDesLebens("ADV_96", "Wasser des Lebens", "", {}),
  unbeschwertesZaubern("ADV_97", "Unbeschwertes Zaubern", "", {}),
  begabteRAufreisserIn("ADV_98", "Begabte/r Aufreißer/in", "", {}),
  einkommen("ADV_99", "Einkommen", "", {}),
  natuerlicherRuestungsschutz("ADV_100", "Natürlicher Rüstungsschutz", "", {}),
  ausdauerndeRLiebhaberIn("ADV_101", "Ausdauernde/r Liebhaber/in", "", {}),
  begabteRAufreisserIn2("ADV_102", "Begabte/r Aufreißer/in", "", {}),
  erotischeAusstrahlung("ADV_103", "Erotische Ausstrahlung", "", {}),
  erotischeStimme("ADV_104", "Erotische Stimme", "", {}),
  freudenfluss("ADV_105", "Freudenfluss", "", {}),
  fruchtbar("ADV_106", "Fruchtbar", "", {}),
  grosseBlase("ADV_107", "Große Blase", "", {}),
  guterGeschmack("ADV_108", "Guter Geschmack", "", {}),
  hypnotischeSBruesteGesaessGemaecht(
    "ADV_109",
    "Hypnotische(s) Brüste / Gesäß / Gemächt",
    "",
    {},
  ),
  jungfrau("ADV_110", "Jungfrau", "", {}),
  levthangekuesst("ADV_111", "Levthangeküsst", "", {}),
  potent("ADV_112", "Potent", "", {}),
  rahjagekuesst("ADV_113", "Rahjageküsst", "", {}),
  resistenzGegenGeschlechtskrankheiten(
    "ADV_114",
    "Resistenz gegen Geschlechtskrankheiten",
    "",
    {},
  ),
  stattlicherPenis("ADV_115", "Stattlicher Penis", "", {}),
  traumhafterPo("ADV_116", "Traumhafter Po", "", {}),
  treuIIi("ADV_117", "Treu I-II", "", {}),
  vorliebeSexpraktik("ADV_118", "Vorliebe (Sexpraktik)", "", {}),
  wohlgeformteBrueste("ADV_119", "Wohlgeformte Brüste", "", {}),
  wunderschoeneVagina("ADV_120", "Wunderschöne Vagina", "", {}),
  wolfsblut("ADV_121", "Wolfsblut", "", {}),
  wolfsgebiss("ADV_122", "Wolfsgebiss", "", {}),
  wolfskind("ADV_123", "Wolfskind", "", {}),
  dschinnenblutRosendschinn("ADV_124", "Dschinnenblut (Rosendschinn)", "", {}),
  feenblutLevschy("ADV_125", "Feenblut (Levschy)", "", {}),
  feenblutVila("ADV_126", "Feenblut (Vila)", "", {}),
  betoerenderDuft("ADV_127", "Betörender Duft", "", {}),
  muttererde("ADV_128", "Muttererde", "", {}),
  rosenliebe("ADV_129", "Rosenliebe", "", {}),
  ekstatischesVerlangen("ADV_130", "Ekstatisches Verlangen", "", {}),
  gabeDerSonne("ADV_132", "Gabe der Sonne", "", {}),
  lustvolleAusschweifung("ADV_134", "Lustvolle Ausschweifung", "", {}),
  rauschDerLeidenschaft("ADV_135", "Rausch der Leidenschaft", "", {}),
  reigenDerLiebe("ADV_136", "Reigen der Liebe", "", {}),
  wildeErregung("ADV_138", "Wilde Erregung", "", {}),
  koboldfreund("ADV_139", "Koboldfreund", "", {}),
  blutzauberer("ADV_140", "Blutzauberer", "", {}),
  eigenerNachteil("DISADV_0", "Eigener Nachteil", "", {}),
  angstVor("DISADV_1", "Angst vor", "", {
    1: "Blut",
    2: "Dunkelheit",
    3: "Höhe",
    4: "Insekten",
    5: "dem Meer",
    6: "Reptilien",
    7: "engen Räumen",
    8: "Spinnen",
    9: "Toten und Untoten",
  }),
  arm("DISADV_2", "Arm", "", {}),
  artefaktgebunden("DISADV_3", "Artefaktgebunden", "", {}),
  behaebig("DISADV_4", "Behäbig", "", {}),
  blind("DISADV_5", "Blind", "", {}),
  blutrausch("DISADV_6", "Blutrausch", "", {}),
  eingeschraenkterSinn("DISADV_7", "Eingeschränkter Sinn", "", {
    1: "Sicht",
    2: "Gehör",
    3: "Geruch & Geschmack",
    4: "Tastsinn",
  }),
  farbenblind("DISADV_11", "Farbenblind", "", {}),
  fettleibig("DISADV_12", "Fettleibig", "", {}),
  giftanfaellig("DISADV_13", "Giftanfällig", "", {}),
  haesslich("DISADV_14", "Hässlich", "", {}),
  hitzeempfindlich("DISADV_15", "Hitzeempfindlich", "", {}),
  kaelteempfindlich("DISADV_16", "Kälteempfindlich", "", {}),
  keineFlugsalbe("DISADV_17", "Keine Flugsalbe", "", {}),
  keinVertrauter("DISADV_18", "Kein Vertrauter", "", {}),
  koerpergebundeneKraft("DISADV_19", "Körpergebundene Kraft", "", {}),
  koerperlicheAuffaelligkeit("DISADV_20", "Körperliche Auffälligkeit", "", {}),
  krankheitsanfaellig("DISADV_21", "Krankheitsanfällig", "", {}),
  laestigeMindergeister("DISADV_22", "Lästige Mindergeister", "", {}),
  lichtempfindlich("DISADV_23", "Lichtempfindlich", "", {}),
  magischeEinschraenkung("DISADV_24", "Magische Einschränkung", "", {
    1: "Fluch der Auen",
    2: "Fluch der Berge",
    3: "Fluch des Eises",
    4: "Fluch der Meere",
    5: "Fluch der Nacht",
    6: "Fluch des Waldes",
    7: "Fluch der Helligkeit",
  }),
  nachtblind("DISADV_25", "Nachtblind", "", {}),
  niedrigeAstralkraft("DISADV_26", "Niedrige Astralkraft", "", {}),
  niedrigeKarmalkraft("DISADV_27", "Niedrige Karmalkraft", "", {}),
  niedrigeLebenskraft("DISADV_28", "Niedrige Lebenskraft", "", {}),
  niedrigeSeelenkraft("DISADV_29", "Niedrige Seelenkraft", "", {}),
  niedrigeZaehigkeit("DISADV_30", "Niedrige Zähigkeit", "", {}),
  pech("DISADV_31", "Pech", "", {}),
  pechmagnet("DISADV_32", "Pechmagnet", "", {}),
  persoenlichkeitsschwaechen("DISADV_33", "Persönlichkeitsschwächen", "", {
    1: "Arroganz",
    2: "Eitelkeit",
    3: "Neid",
    4: "Streitsucht",
    5: "Unheimlich",
    6: "Verwöhnt",
    7: "Vorurteile",
    8: "Weltfremd",
    9: "Anzügliches Verhalten",
    10: "Eifersucht",
    11: "Busenkomplexe",
    12: "Peniskomplexe",
    13: "Stimmungsschwankungen",
  }),
  prinzipientreue("DISADV_34", "Prinzipientreue", "", {
    1: "99 Gesetze",
    2: "Moralkodex der Hesindekirche",
    3: "Moralkodex der Phexkirche",
    4: "Moralkodex der Perainekirche",
    5: "Ehrenkodex der Krieger",
    6: "Ehrenkodex der Ritter",
    7: "Elfische Weltsicht",
    8: "Moralkodex der Boronkirche",
    9: "Moralkodex der Praioskirche",
    10: "Moralkodex der Rondrakirche",
    11: "Zwergischer Ehrenkodex",
    12: "Pazifismus",
    13: "Moralkodex der Efferdkirche",
    14: "Moralkodex der Traviakirche",
    15: "Moralkodex der Firunkirche",
    16: "Moralkodex der Tsakirche",
    17: "Moralkodex der Ingerimmkirche",
    18: "Moralkodex der Rahjakirche",
    19: "Moralkodex der Aveskirche",
    20: "Moralkodex der Ifirnkirche",
    21: "Moralkodex der Korkirche",
    22: "Moralkodex der Nanduskirche",
    23: "Moralkodex der Swafnirkirche",
  }),
  schlafwandler("DISADV_35", "Schlafwandler", "", {}),
  schlechteAngewohnheit("DISADV_36", "Schlechte Angewohnheit", "", {
    1: "Barfüßer",
    2: "Belästigung",
    3: "Dritte Person",
    4: "Duzer",
    5: "Erster",
    6: "Heulsuse",
    7: "Hypochonder",
    8: "Junge",
    9: "Langschläfer",
    10: "Links-Rechts-Schwäche",
    11: "Mein Kind",
    12: "Nägelkauer",
    13: "Nase-/Ohrenbohrer",
    14: "Nervös",
    15: "Putzfimmel",
    16: "Raucher",
    17: "Redet wie ein Wasserfall",
    18: "Schlechte Tischmanieren",
    19: "Selbstgespräche",
    20: "Unordentlich",
    21: "Wir",
    22: "Falscher Name",
    23: "He du! / He ihr!",
    24: "Namensnenner",
    25: "Namensverdreher",
    26: "Anspielungen",
    27: "Lauter Liebhaber",
    28: "Miese Anmache",
    29: "Nur im Dunkeln",
    30: "Prüde",
    31: "Schamlos",
    32: "Schwärmerei",
  }),
  schlechteEigenschaft("DISADV_37", "Schlechte Eigenschaft", "", {
    1: "Aberglaube",
    2: "Autoritätsglaube",
    3: "Geiz",
    4: "Goldgier",
    5: "Jähzorn",
    6: "Kleptomanie",
    7: "Naiv",
    8: "Neugier",
    9: "Rachsucht",
    10: "Spielsucht",
    11: "Verschwendungssucht",
    12: "Exhibitionismus",
    13: "Lüsternheit",
    14: "Voyeurismus",
    15: "Sikaryan-Durst",
  }),
  schlechteRegenerationAstralenergie(
    "DISADV_38",
    "Schlechte Regeneration (Astralenergie)",
    "",
    {},
  ),
  schlechteRegenerationKarmalenergie(
    "DISADV_39",
    "Schlechte Regeneration (Karmalenergie)",
    "",
    {},
  ),
  schlechteRegenerationLebensenergie(
    "DISADV_40",
    "Schlechte Regeneration (Lebensenergie)",
    "",
    {},
  ),
  schwacherAstralkoerper("DISADV_41", "Schwacher Astralkörper", "", {}),
  schwacherKarmalkoerper("DISADV_42", "Schwacher Karmalkörper", "", {}),
  sensiblerGeruchssinn("DISADV_43", "Sensibler Geruchssinn", "", {}),
  sprachfehler("DISADV_44", "Sprachfehler", "", {}),
  stigma("DISADV_45", "Stigma", "", {
    1: "Albino",
    2: "Brandmale",
    3: "Grüne Haare",
    4: "Katzenhafte Augen",
    5: "Schlangenschuppen",
  }),
  stumm("DISADV_46", "Stumm", "", {}),
  taub("DISADV_47", "Taub", "", {}),
  unfaehig("DISADV_48", "Unfähig", "", {}),
  unfrei("DISADV_49", "Unfrei", "", {}),
  verpflichtungen("DISADV_50", "Verpflichtungen", "", {
    1: "Sippenmitglied gegenüber der Sippe",
    2: "Verschuldeter Held",
    3: "Adliger gegenüber seinem Lehnsherrn",
    4: "Geweihter gegenüber seiner Kirche",
    5: "Geweihter gegenüber seinem Tempel",
    6: "Magier gegenüber seinem Lehrmeister",
    7: "Magier gegenüber seiner Akademie",
    8: "Magier gegenüber seiner Gilde",
    9: "Mitglied einer radikalen Sekte gegenüber den Anführern der Gruppe",
  }),
  verstuemmelt("DISADV_51", "Verstümmelt", "", {
    1: "Einarmig",
    2: "Einäugig",
    3: "Einbeinig",
    4: "Einhändig",
    5: "Einohrig",
    6: "Eunuch I",
    7: "Eunuch II",
  }),
  wahrerName("DISADV_52", "Wahrer Name", "", {}),
  wildeMagie("DISADV_53", "Wilde Magie", "", {}),
  zauberanfaellig("DISADV_54", "Zauberanfällig", "", {}),
  zerbrechlich("DISADV_55", "Zerbrechlich", "", {}),
  glaesern("DISADV_56", "Gläsern", "", {}),
  verweichlicht("DISADV_57", "Verweichlicht", "", {}),
  instabilerZauberer("DISADV_58", "Instabiler Zauberer", "", {}),
  kleineZauberauswahl("DISADV_59", "Kleine Zauberauswahl", "", {}),
  schwacheZaubermelodien("DISADV_60", "Schwache Zaubermelodien", "", {}),
  schwacheZaubertaenze("DISADV_61", "Schwache Zaubertänze", "", {}),
  verminderteZaubermelodien("DISADV_62", "Verminderte Zaubermelodien", "", {}),
  verminderteZaubertaenze("DISADV_63", "Verminderte Zaubertänze", "", {}),
  jagdwildgeruch("DISADV_64", "Jagdwildgeruch", "", {}),
  raubtiergeruch("DISADV_65", "Raubtiergeruch", "", {}),
  boeserNamensvetter("DISADV_66", "Böser Namensvetter", "", {}),
  laecherlicherName("DISADV_67", "Lächerlicher Name", "", {}),
  schlechtesNamensgedaechtnis(
    "DISADV_68",
    "Schlechtes Namensgedächtnis",
    "",
    {},
  ),
  schurkenname("DISADV_69", "Schurkenname", "", {}),
  unpassenderName("DISADV_70", "Unpassender Name", "", {}),
  unvertraeglichkeitGegenueberAlkohol(
    "DISADV_71",
    "Unverträglichkeit gegenüber Alkohol",
    "",
    {},
  ),
  wenigePredigten("DISADV_72", "Wenige Predigten", "", {}),
  wenigeVisionen("DISADV_73", "Wenige Visionen", "", {}),
  lernfaul("DISADV_74", "Lernfaul", "", {}),
  abneigungSexpraktik("DISADV_75", "Abneigung (Sexpraktik)", "", {}),
  fixierung("DISADV_76", "Fixierung", "", {}),
  frigide("DISADV_77", "Frigide", "", {}),
  homophobieHeterophobie("DISADV_78", "Homophobie/Heterophobie", "", {}),
  schlechterGeschmack("DISADV_79", "Schlechter Geschmack", "", {}),
  unerotischeStimme("DISADV_80", "Unerotische Stimme", "", {}),
  untreu("DISADV_81", "Untreu", "", {}),
  verfruehterHoehepunkt("DISADV_82", "Verfrühter Höhepunkt", "", {}),
  impotent("DISADV_84", "Impotent", "", {}),
  unfruchtbar("DISADV_85", "Unfruchtbar", "", {}),
  laestigeBluetenfeen("DISADV_86", "Lästige Blütenfeen", "", {});
  // </db-replace-token>

  final String id;
  final String name;
  final String rules;
  final Map<int, String> selectOptions;
  const ActivatableBase(this.id, this.name, this.rules, this.selectOptions);
}

const Map<String, ActivatableBase> activatableById = {
  "ADV_0": ActivatableBase.eigenerVorteil,
  "ADV_1": ActivatableBase.adel,
  "ADV_2": ActivatableBase.altersresistenz,
  "ADV_3": ActivatableBase.angenehmerGeruch,
  "ADV_4": ActivatableBase.begabung,
  "ADV_5": ActivatableBase.beidhaendig,
  "ADV_6": ActivatableBase.dunkelsicht,
  "ADV_7": ActivatableBase.eisenaffineAura,
  "ADV_8": ActivatableBase.entfernungssinn,
  "ADV_9": ActivatableBase.flink,
  "ADV_10": ActivatableBase.fuchssinn,
  "ADV_11": ActivatableBase.geborenerRedner,
  "ADV_12": ActivatableBase.geweihter,
  "ADV_13": ActivatableBase.giftresistenz,
  "ADV_14": ActivatableBase.glueck,
  "ADV_15": ActivatableBase.gutaussehend,
  "ADV_16": ActivatableBase.herausragendeFertigkeit,
  "ADV_17": ActivatableBase.herausragendeKampftechnik,
  "ADV_18": ActivatableBase.herausragenderSinn,
  "ADV_22": ActivatableBase.hitzeresistenz,
  "ADV_23": ActivatableBase.hoheAstralkraft,
  "ADV_24": ActivatableBase.hoheKarmalkraft,
  "ADV_25": ActivatableBase.hoheLebenskraft,
  "ADV_26": ActivatableBase.hoheSeelenkraft,
  "ADV_27": ActivatableBase.hoheZaehigkeit,
  "ADV_28": ActivatableBase.immunitaetGegenGift,
  "ADV_29": ActivatableBase.immunitaetGegenKrankheit,
  "ADV_30": ActivatableBase.kaelteresistenz,
  "ADV_31": ActivatableBase.krankheitsresistenz,
  "ADV_32": ActivatableBase.magischeEinstimmung,
  "ADV_33": ActivatableBase.mystiker,
  "ADV_34": ActivatableBase.nichtschlaefer,
  "ADV_35": ActivatableBase.pragmatiker,
  "ADV_36": ActivatableBase.reich,
  "ADV_37": ActivatableBase.richtungssinn,
  "ADV_38": ActivatableBase.schlangenmensch,
  "ADV_39": ActivatableBase.schwerZuVerzaubern,
  "ADV_40": ActivatableBase.sozialeAnpassungsfaehigkeit,
  "ADV_41": ActivatableBase.unscheinbar,
  "ADV_42": ActivatableBase.verbesserteRegenerationAstralenergie,
  "ADV_43": ActivatableBase.verbesserteRegenerationKarmaenergie,
  "ADV_44": ActivatableBase.verbesserteRegenerationLebensenergie,
  "ADV_45": ActivatableBase.verhuellteAura,
  "ADV_46": ActivatableBase.vertrauenerweckend,
  "ADV_47": ActivatableBase.waffenbegabung,
  "ADV_48": ActivatableBase.wohlklang,
  "ADV_49": ActivatableBase.zaeherHund,
  "ADV_50": ActivatableBase.zauberer,
  "ADV_51": ActivatableBase.zeitgefuehl,
  "ADV_52": ActivatableBase.zweistimmigerGesang,
  "ADV_53": ActivatableBase.zwergennase,
  "ADV_54": ActivatableBase.eisern,
  "ADV_55": ActivatableBase.hartImNehmen,
  "ADV_56": ActivatableBase.affinitaetZuDaemonen,
  "ADV_57": ActivatableBase.affinitaetZuElementaren,
  "ADV_58": ActivatableBase.grosseZauberauswahl,
  "ADV_59": ActivatableBase.keinBannDesEisen,
  "ADV_60": ActivatableBase.machtvolleZaubermelodien,
  "ADV_61": ActivatableBase.machtvolleZaubertaenze,
  "ADV_62": ActivatableBase.schutzgeist,
  "ADV_63": ActivatableBase.weitreichendeZaubermelodien,
  "ADV_64": ActivatableBase.weitreichendeZaubertaenze,
  "ADV_65": ActivatableBase.basiliskentoeter,
  "ADV_66": ActivatableBase.drachentoeter,
  "ADV_67": ActivatableBase.feenfreund,
  "ADV_68": ActivatableBase.hassAuf,
  "ADV_69": ActivatableBase.saumagen,
  "ADV_70": ActivatableBase.tierfreund,
  "ADV_71": ActivatableBase.wasserlebewesen,
  "ADV_72": ActivatableBase.allerweltsname,
  "ADV_73": ActivatableBase.gutesNamensgedaechtnis,
  "ADV_74": ActivatableBase.heldenhafterName,
  "ADV_75": ActivatableBase.schnellWiederAufDenBeinen,
  "ADV_76": ActivatableBase.akoluth,
  "ADV_77": ActivatableBase.prediger,
  "ADV_78": ActivatableBase.visionaer,
  "ADV_79": ActivatableBase.zahlreichePredigten,
  "ADV_80": ActivatableBase.zahlreicheVisionen,
  "ADV_81": ActivatableBase.feenblutBluetenfee,
  "ADV_82": ActivatableBase.feenblutDryade,
  "ADV_83": ActivatableBase.feenblutGrosserEberbiestinger,
  "ADV_84": ActivatableBase.feenblutNixer,
  "ADV_85": ActivatableBase.animalischeKraft,
  "ADV_86": ActivatableBase.blumenduft,
  "ADV_87": ActivatableBase.dickesFell,
  "ADV_88": ActivatableBase.einblickeInsVerborgene,
  "ADV_89": ActivatableBase.glatteHaut,
  "ADV_90": ActivatableBase.harmonieDesWaldes,
  "ADV_91": ActivatableBase.kraftDerBaeume,
  "ADV_92": ActivatableBase.leichterGang,
  "ADV_93": ActivatableBase.seesprache,
  "ADV_94": ActivatableBase.tierischeKampfgefaehrten,
  "ADV_95": ActivatableBase.verfuehrerischeGestalt,
  "ADV_96": ActivatableBase.wasserDesLebens,
  "ADV_97": ActivatableBase.unbeschwertesZaubern,
  "ADV_98": ActivatableBase.begabteRAufreisserIn,
  "ADV_99": ActivatableBase.einkommen,
  "ADV_100": ActivatableBase.natuerlicherRuestungsschutz,
  "ADV_101": ActivatableBase.ausdauerndeRLiebhaberIn,
  "ADV_102": ActivatableBase.begabteRAufreisserIn2,
  "ADV_103": ActivatableBase.erotischeAusstrahlung,
  "ADV_104": ActivatableBase.erotischeStimme,
  "ADV_105": ActivatableBase.freudenfluss,
  "ADV_106": ActivatableBase.fruchtbar,
  "ADV_107": ActivatableBase.grosseBlase,
  "ADV_108": ActivatableBase.guterGeschmack,
  "ADV_109": ActivatableBase.hypnotischeSBruesteGesaessGemaecht,
  "ADV_110": ActivatableBase.jungfrau,
  "ADV_111": ActivatableBase.levthangekuesst,
  "ADV_112": ActivatableBase.potent,
  "ADV_113": ActivatableBase.rahjagekuesst,
  "ADV_114": ActivatableBase.resistenzGegenGeschlechtskrankheiten,
  "ADV_115": ActivatableBase.stattlicherPenis,
  "ADV_116": ActivatableBase.traumhafterPo,
  "ADV_117": ActivatableBase.treuIIi,
  "ADV_118": ActivatableBase.vorliebeSexpraktik,
  "ADV_119": ActivatableBase.wohlgeformteBrueste,
  "ADV_120": ActivatableBase.wunderschoeneVagina,
  "ADV_121": ActivatableBase.wolfsblut,
  "ADV_122": ActivatableBase.wolfsgebiss,
  "ADV_123": ActivatableBase.wolfskind,
  "ADV_124": ActivatableBase.dschinnenblutRosendschinn,
  "ADV_125": ActivatableBase.feenblutLevschy,
  "ADV_126": ActivatableBase.feenblutVila,
  "ADV_127": ActivatableBase.betoerenderDuft,
  "ADV_128": ActivatableBase.muttererde,
  "ADV_129": ActivatableBase.rosenliebe,
  "ADV_130": ActivatableBase.ekstatischesVerlangen,
  "ADV_132": ActivatableBase.gabeDerSonne,
  "ADV_134": ActivatableBase.lustvolleAusschweifung,
  "ADV_135": ActivatableBase.rauschDerLeidenschaft,
  "ADV_136": ActivatableBase.reigenDerLiebe,
  "ADV_138": ActivatableBase.wildeErregung,
  "ADV_139": ActivatableBase.koboldfreund,
  "ADV_140": ActivatableBase.blutzauberer,
  "DISADV_0": ActivatableBase.eigenerNachteil,
  "DISADV_1": ActivatableBase.angstVor,
  "DISADV_2": ActivatableBase.arm,
  "DISADV_3": ActivatableBase.artefaktgebunden,
  "DISADV_4": ActivatableBase.behaebig,
  "DISADV_5": ActivatableBase.blind,
  "DISADV_6": ActivatableBase.blutrausch,
  "DISADV_7": ActivatableBase.eingeschraenkterSinn,
  "DISADV_11": ActivatableBase.farbenblind,
  "DISADV_12": ActivatableBase.fettleibig,
  "DISADV_13": ActivatableBase.giftanfaellig,
  "DISADV_14": ActivatableBase.haesslich,
  "DISADV_15": ActivatableBase.hitzeempfindlich,
  "DISADV_16": ActivatableBase.kaelteempfindlich,
  "DISADV_17": ActivatableBase.keineFlugsalbe,
  "DISADV_18": ActivatableBase.keinVertrauter,
  "DISADV_19": ActivatableBase.koerpergebundeneKraft,
  "DISADV_20": ActivatableBase.koerperlicheAuffaelligkeit,
  "DISADV_21": ActivatableBase.krankheitsanfaellig,
  "DISADV_22": ActivatableBase.laestigeMindergeister,
  "DISADV_23": ActivatableBase.lichtempfindlich,
  "DISADV_24": ActivatableBase.magischeEinschraenkung,
  "DISADV_25": ActivatableBase.nachtblind,
  "DISADV_26": ActivatableBase.niedrigeAstralkraft,
  "DISADV_27": ActivatableBase.niedrigeKarmalkraft,
  "DISADV_28": ActivatableBase.niedrigeLebenskraft,
  "DISADV_29": ActivatableBase.niedrigeSeelenkraft,
  "DISADV_30": ActivatableBase.niedrigeZaehigkeit,
  "DISADV_31": ActivatableBase.pech,
  "DISADV_32": ActivatableBase.pechmagnet,
  "DISADV_33": ActivatableBase.persoenlichkeitsschwaechen,
  "DISADV_34": ActivatableBase.prinzipientreue,
  "DISADV_35": ActivatableBase.schlafwandler,
  "DISADV_36": ActivatableBase.schlechteAngewohnheit,
  "DISADV_37": ActivatableBase.schlechteEigenschaft,
  "DISADV_38": ActivatableBase.schlechteRegenerationAstralenergie,
  "DISADV_39": ActivatableBase.schlechteRegenerationKarmalenergie,
  "DISADV_40": ActivatableBase.schlechteRegenerationLebensenergie,
  "DISADV_41": ActivatableBase.schwacherAstralkoerper,
  "DISADV_42": ActivatableBase.schwacherKarmalkoerper,
  "DISADV_43": ActivatableBase.sensiblerGeruchssinn,
  "DISADV_44": ActivatableBase.sprachfehler,
  "DISADV_45": ActivatableBase.stigma,
  "DISADV_46": ActivatableBase.stumm,
  "DISADV_47": ActivatableBase.taub,
  "DISADV_48": ActivatableBase.unfaehig,
  "DISADV_49": ActivatableBase.unfrei,
  "DISADV_50": ActivatableBase.verpflichtungen,
  "DISADV_51": ActivatableBase.verstuemmelt,
  "DISADV_52": ActivatableBase.wahrerName,
  "DISADV_53": ActivatableBase.wildeMagie,
  "DISADV_54": ActivatableBase.zauberanfaellig,
  "DISADV_55": ActivatableBase.zerbrechlich,
  "DISADV_56": ActivatableBase.glaesern,
  "DISADV_57": ActivatableBase.verweichlicht,
  "DISADV_58": ActivatableBase.instabilerZauberer,
  "DISADV_59": ActivatableBase.kleineZauberauswahl,
  "DISADV_60": ActivatableBase.schwacheZaubermelodien,
  "DISADV_61": ActivatableBase.schwacheZaubertaenze,
  "DISADV_62": ActivatableBase.verminderteZaubermelodien,
  "DISADV_63": ActivatableBase.verminderteZaubertaenze,
  "DISADV_64": ActivatableBase.jagdwildgeruch,
  "DISADV_65": ActivatableBase.raubtiergeruch,
  "DISADV_66": ActivatableBase.boeserNamensvetter,
  "DISADV_67": ActivatableBase.laecherlicherName,
  "DISADV_68": ActivatableBase.schlechtesNamensgedaechtnis,
  "DISADV_69": ActivatableBase.schurkenname,
  "DISADV_70": ActivatableBase.unpassenderName,
  "DISADV_71": ActivatableBase.unvertraeglichkeitGegenueberAlkohol,
  "DISADV_72": ActivatableBase.wenigePredigten,
  "DISADV_73": ActivatableBase.wenigeVisionen,
  "DISADV_74": ActivatableBase.lernfaul,
  "DISADV_75": ActivatableBase.abneigungSexpraktik,
  "DISADV_76": ActivatableBase.fixierung,
  "DISADV_77": ActivatableBase.frigide,
  "DISADV_78": ActivatableBase.homophobieHeterophobie,
  "DISADV_79": ActivatableBase.schlechterGeschmack,
  "DISADV_80": ActivatableBase.unerotischeStimme,
  "DISADV_81": ActivatableBase.untreu,
  "DISADV_82": ActivatableBase.verfruehterHoehepunkt,
  "DISADV_84": ActivatableBase.impotent,
  "DISADV_85": ActivatableBase.unfruchtbar,
  "DISADV_86": ActivatableBase.laestigeBluetenfeen,
};
