enum ActivatableBase {
  // <db-replace-token>
  eigenerVorteil("ADV_0", "Eigener Vorteil", "", {}),
  adel("ADV_1", "Adel", "", {}),
  altersresistenz("ADV_2", "Altersresistenz", "", {}),
  angenehmerGeruch("ADV_3", "Angenehmer Geruch", "", {}),
  begabung("ADV_4", "Begabung", "", {}),
  beidhaendig("ADV_5", "Beidhändig", "", {}),
  dunkelsicht("ADV_6", "Dunkelsicht", "", {}),
  eisenaffineAura("ADV_7", "Eisenaffine Aura", "", {}),
  entfernungssinn("ADV_8", "Entfernungssinn", "", {}),
  flink("ADV_9", "Flink", "", {}),
  fuchssinn("ADV_10", "Fuchssinn", "", {}),
  geborenerRedner("ADV_11", "Geborener Redner", "", {}),
  geweihter("ADV_12", "Geweihter", "", {}),
  giftresistenz("ADV_13", "Giftresistenz", "", {}),
  glueck("ADV_14", "Glück", "", {}),
  gutaussehend("ADV_15", "Gutaussehend", "", {}),
  herausragendeFertigkeit("ADV_16", "Herausragende Fertigkeit", "", {}),
  herausragendeKampftechnik("ADV_17", "Herausragende Kampftechnik", "", {}),
  herausragenderSinn("ADV_18", "Herausragender Sinn", "", {
    1: "Sicht",
    2: "Gehör",
    3: "Geruch & Geschmack",
    4: "Tastsinn",
  }),
  hitzeresistenz("ADV_22", "Hitzeresistenz", "", {}),
  hoheAstralkraft("ADV_23", "Hohe Astralkraft", "", {}),
  hoheKarmalkraft("ADV_24", "Hohe Karmalkraft", "", {}),
  hoheLebenskraft("ADV_25", "Hohe Lebenskraft", "", {}),
  hoheSeelenkraft("ADV_26", "Hohe Seelenkraft", "", {}),
  hoheZaehigkeit("ADV_27", "Hohe Zähigkeit", "", {}),
  immunitaetGegenGift("ADV_28", "Immunität gegen", "", {
    1: "Arax",
    2: "Kelmon",
    3: "Tulmadron",
    4: "Wurara",
    5: "Kukris",
    6: "Mandragora",
    7: "Omrais",
    8: "Sunsura",
    9: "Höhlenspinnengift",
    10: "Krötengift",
    11: "Rattenpilzgift",
    12: "Ghulgift",
    13: "Mantikorgift",
    14: "Morfugift",
    15: "Brabacudagift",
    16: "Gelbschwanzskorpiongift",
    17: "Kvillottergift",
    18: "Vogelspinnengift",
    19: "Seilschlangengift",
    20: "Speikobragift",
    21: "Alkohol",
    22: "Angstgift",
    23: "Arachnae",
    24: "Betäubungsgift",
    25: "Boabungaha",
    26: "Charyb‘Ytt‘ Traum",
    27: "Drachenspeichel",
    28: "Feuerzunge",
    29: "Gonede",
    30: "Halbgift",
    31: "Hollbeerenbrechmittel",
    32: "Höhlenbovistgift",
    33: "Marbos Ruhe",
    34: "Margolaschabführmittel",
    35: "Purpurblitz",
    36: "Schattenneblergift",
    37: "Schwarzer Lotus",
    38: "Tinzal",
    39: "Urkaritgift",
    40: "Visarnetgift",
  }),
  immunitaetGegenKrankheit("ADV_29", "Immunität gegen", "", {
    1: "Flinker Difar",
    2: "Lutanas",
    3: "Rascher Wahn",
    4: "Sumpffieber/Brabaker Schweiß",
    5: "Zorganpocken",
    6: "Aussatz",
    7: "Blaue Keuche",
    8: "Blutiger Rotz",
    9: "Dumpfschädel",
    10: "Efferd-/Kerkersieche",
    11: "Gilbe/Schlachtfeldfieber",
    12: "Jahresfieber",
    13: "Schwarze Wut",
    14: "Tollwut",
    15: "Wundfieber",
    16: "Augenpest",
    17: "Paralyse/Basiliskenblick",
    18: "Blutkrächzen",
    19: "Grasse",
    20: "Gänsepusteln",
    21: "Herbstpocken",
    22: "Horasierkrankheit",
    23: "Karmesin",
    24: "Leichenblässe",
    25: "Lykanthropie",
    26: "Marder-/Orkenkrätze",
    27: "Rotbacke",
    28: "Schlafkrankheit",
    29: "Triefnase",
    30: "Bleiche Sieche",
    31: "Reißwasserseuche",
  }),
  kaelteresistenz("ADV_30", "Kälteresistenz", "", {}),
  krankheitsresistenz("ADV_31", "Krankheitsresistenz", "", {}),
  magischeEinstimmung("ADV_32", "Magische Einstimmung", "", {
    1: "Wesen der Auen",
    2: "Wesen der Berge",
    3: "Wesen des Eises",
    4: "Wesen der Meere",
    5: "Wesen der Nacht",
    6: "Wesen des Waldes",
  }),
  mystiker("ADV_33", "Mystiker", "", {}),
  nichtschlaefer("ADV_34", "Nichtschläfer", "", {}),
  pragmatiker("ADV_35", "Pragmatiker", "", {}),
  reich("ADV_36", "Reich", "", {}),
  richtungssinn("ADV_37", "Richtungssinn", "", {}),
  schlangenmensch("ADV_38", "Schlangenmensch", "", {}),
  schwerZuVerzaubern("ADV_39", "Schwer zu verzaubern", "", {}),
  sozialeAnpassungsfaehigkeit("ADV_40", "Soziale Anpassungsfähigkeit", "", {}),
  unscheinbar("ADV_41", "Unscheinbar", "", {}),
  verbesserteRegenerationAstralenergie(
    "ADV_42",
    "Verbesserte Regeneration (Astralenergie)",
    "",
    {},
  ),
  verbesserteRegenerationKarmaenergie(
    "ADV_43",
    "Verbesserte Regeneration (Karmaenergie)",
    "",
    {},
  ),
  verbesserteRegenerationLebensenergie(
    "ADV_44",
    "Verbesserte Regeneration (Lebensenergie)",
    "",
    {},
  ),
  verhuellteAura("ADV_45", "Verhüllte Aura", "", {}),
  vertrauenerweckend("ADV_46", "Vertrauenerweckend", "", {}),
  waffenbegabung("ADV_47", "Waffenbegabung", "", {}),
  wohlklang("ADV_48", "Wohlklang", "", {}),
  zaeherHund("ADV_49", "Zäher Hund", "", {}),
  zauberer("ADV_50", "Zauberer", "", {}),
  zeitgefuehl("ADV_51", "Zeitgefühl", "", {}),
  zweistimmigerGesang("ADV_52", "Zweistimmiger Gesang", "", {}),
  zwergennase("ADV_53", "Zwergennase", "", {}),
  eisern("ADV_54", "Eisern", "", {}),
  hartImNehmen("ADV_55", "Hart im nehmen", "", {}),
  affinitaetZuDaemonen("ADV_56", "Affinität zu Dämonen", "", {}),
  affinitaetZuElementaren("ADV_57", "Affinität zu Elementaren", "", {}),
  grosseZauberauswahl("ADV_58", "Große Zauberauswahl", "", {}),
  keinBannDesEisen("ADV_59", "Kein Bann des Eisen", "", {}),
  machtvolleZaubermelodien("ADV_60", "Machtvolle Zaubermelodien", "", {}),
  machtvolleZaubertaenze("ADV_61", "Machtvolle Zaubertänze", "", {}),
  schutzgeist("ADV_62", "Schutzgeist", "", {}),
  weitreichendeZaubermelodien("ADV_63", "Weitreichende Zaubermelodien", "", {}),
  weitreichendeZaubertaenze("ADV_64", "Weitreichende Zaubertänze", "", {}),
  basiliskentoeter("ADV_65", "Basiliskentöter", "", {}),
  drachentoeter("ADV_66", "Drachentöter", "", {}),
  feenfreund("ADV_67", "Feenfreund", "", {}),
  hassAuf("ADV_68", "Hass auf", "", {
    1: "Häufig",
    2: "Gelegentlich",
    3: "Selten",
  }),
  saumagen("ADV_69", "Saumagen", "", {}),
  tierfreund("ADV_70", "Tierfreund", "", {}),
  wasserlebewesen("ADV_71", "Wasserlebewesen", "", {}),
  allerweltsname("ADV_72", "Allerweltsname", "", {}),
  gutesNamensgedaechtnis("ADV_73", "Gutes Namensgedächtnis", "", {}),
  heldenhafterName("ADV_74", "Heldenhafter Name", "", {}),
  schnellWiederAufDenBeinen("ADV_75", "Schnell wieder auf den Beinen", "", {}),
  akoluth("ADV_76", "Akoluth", "", {}),
  prediger("ADV_77", "Prediger", "", {}),
  visionaer("ADV_78", "Visionär", "", {}),
  zahlreichePredigten("ADV_79", "Zahlreiche Predigten", "", {}),
  zahlreicheVisionen("ADV_80", "Zahlreiche Visionen", "", {}),
  feenblutBluetenfee("ADV_81", "Feenblut (Blütenfee)", "", {}),
  feenblutDryade("ADV_82", "Feenblut (Dryade)", "", {}),
  feenblutGrosserEberbiestinger(
    "ADV_83",
    "Feenblut (Großer Eberbiestinger)",
    "",
    {},
  ),
  feenblutNixer("ADV_84", "Feenblut (Nixer)", "", {}),
  animalischeKraft("ADV_85", "Animalische Kraft", "", {}),
  blumenduft("ADV_86", "Blumenduft", "", {}),
  dickesFell("ADV_87", "Dickes Fell", "", {}),
  einblickeInsVerborgene("ADV_88", "Einblicke ins Verborgene", "", {}),
  glatteHaut("ADV_89", "Glatte Haut", "", {}),
  harmonieDesWaldes("ADV_90", "Harmonie des Waldes", "", {}),
  kraftDerBaeume("ADV_91", "Kraft der Bäume", "", {}),
  leichterGang("ADV_92", "Leichter Gang", "", {}),
  seesprache("ADV_93", "Seesprache", "", {}),
  tierischeKampfgefaehrten("ADV_94", "Tierische Kampfgefährten", "", {}),
  verfuehrerischeGestalt("ADV_95", "Verführerische Gestalt", "", {}),
  wasserDesLebens("ADV_96", "Wasser des Lebens", "", {}),
  unbeschwertesZaubern("ADV_97", "Unbeschwertes Zaubern", "", {}),
  begabteRAufreisserIn("ADV_98", "Begabte/r Aufreißer/in", "", {}),
  einkommen("ADV_99", "Einkommen", "", {}),
  natuerlicherRuestungsschutz("ADV_100", "Natürlicher Rüstungsschutz", "", {}),
  ausdauerndeRLiebhaberIn("ADV_101", "Ausdauernde/r Liebhaber/in", "", {}),
  begabteRAufreisserIn2("ADV_102", "Begabte/r Aufreißer/in", "", {}),
  erotischeAusstrahlung("ADV_103", "Erotische Ausstrahlung", "", {}),
  erotischeStimme("ADV_104", "Erotische Stimme", "", {}),
  freudenfluss("ADV_105", "Freudenfluss", "", {}),
  fruchtbar("ADV_106", "Fruchtbar", "", {}),
  grosseBlase("ADV_107", "Große Blase", "", {}),
  guterGeschmack("ADV_108", "Guter Geschmack", "", {}),
  hypnotischeSBruesteGesaessGemaecht(
    "ADV_109",
    "Hypnotische(s) Brüste / Gesäß / Gemächt",
    "",
    {},
  ),
  jungfrau("ADV_110", "Jungfrau", "", {}),
  levthangekuesst("ADV_111", "Levthangeküsst", "", {}),
  potent("ADV_112", "Potent", "", {}),
  rahjagekuesst("ADV_113", "Rahjageküsst", "", {}),
  resistenzGegenGeschlechtskrankheiten(
    "ADV_114",
    "Resistenz gegen Geschlechtskrankheiten",
    "",
    {},
  ),
  stattlicherPenis("ADV_115", "Stattlicher Penis", "", {}),
  traumhafterPo("ADV_116", "Traumhafter Po", "", {}),
  treuIIi("ADV_117", "Treu I-II", "", {}),
  vorliebeSexpraktik("ADV_118", "Vorliebe (Sexpraktik)", "", {}),
  wohlgeformteBrueste("ADV_119", "Wohlgeformte Brüste", "", {}),
  wunderschoeneVagina("ADV_120", "Wunderschöne Vagina", "", {}),
  wolfsblut("ADV_121", "Wolfsblut", "", {}),
  wolfsgebiss("ADV_122", "Wolfsgebiss", "", {}),
  wolfskind("ADV_123", "Wolfskind", "", {}),
  dschinnenblutRosendschinn("ADV_124", "Dschinnenblut (Rosendschinn)", "", {}),
  feenblutLevschy("ADV_125", "Feenblut (Levschy)", "", {}),
  feenblutVila("ADV_126", "Feenblut (Vila)", "", {}),
  betoerenderDuft("ADV_127", "Betörender Duft", "", {}),
  muttererde("ADV_128", "Muttererde", "", {}),
  rosenliebe("ADV_129", "Rosenliebe", "", {}),
  ekstatischesVerlangen("ADV_130", "Ekstatisches Verlangen", "", {}),
  gabeDerSonne("ADV_132", "Gabe der Sonne", "", {}),
  lustvolleAusschweifung("ADV_134", "Lustvolle Ausschweifung", "", {}),
  rauschDerLeidenschaft("ADV_135", "Rausch der Leidenschaft", "", {}),
  reigenDerLiebe("ADV_136", "Reigen der Liebe", "", {}),
  wildeErregung("ADV_138", "Wilde Erregung", "", {}),
  koboldfreund("ADV_139", "Koboldfreund", "", {}),
  blutzauberer("ADV_140", "Blutzauberer", "", {}),
  eigenerNachteil("DISADV_0", "Eigener Nachteil", "", {}),
  angstVor("DISADV_1", "Angst vor", "", {
    1: "Blut",
    2: "Dunkelheit",
    3: "Höhe",
    4: "Insekten",
    5: "dem Meer",
    6: "Reptilien",
    7: "engen Räumen",
    8: "Spinnen",
    9: "Toten und Untoten",
  }),
  arm("DISADV_2", "Arm", "", {}),
  artefaktgebunden("DISADV_3", "Artefaktgebunden", "", {}),
  behaebig("DISADV_4", "Behäbig", "", {}),
  blind("DISADV_5", "Blind", "", {}),
  blutrausch("DISADV_6", "Blutrausch", "", {}),
  eingeschraenkterSinn("DISADV_7", "Eingeschränkter Sinn", "", {
    1: "Sicht",
    2: "Gehör",
    3: "Geruch & Geschmack",
    4: "Tastsinn",
  }),
  farbenblind("DISADV_11", "Farbenblind", "", {}),
  fettleibig("DISADV_12", "Fettleibig", "", {}),
  giftanfaellig("DISADV_13", "Giftanfällig", "", {}),
  haesslich("DISADV_14", "Hässlich", "", {}),
  hitzeempfindlich("DISADV_15", "Hitzeempfindlich", "", {}),
  kaelteempfindlich("DISADV_16", "Kälteempfindlich", "", {}),
  keineFlugsalbe("DISADV_17", "Keine Flugsalbe", "", {}),
  keinVertrauter("DISADV_18", "Kein Vertrauter", "", {}),
  koerpergebundeneKraft("DISADV_19", "Körpergebundene Kraft", "", {}),
  koerperlicheAuffaelligkeit("DISADV_20", "Körperliche Auffälligkeit", "", {}),
  krankheitsanfaellig("DISADV_21", "Krankheitsanfällig", "", {}),
  laestigeMindergeister("DISADV_22", "Lästige Mindergeister", "", {}),
  lichtempfindlich("DISADV_23", "Lichtempfindlich", "", {}),
  magischeEinschraenkung("DISADV_24", "Magische Einschränkung", "", {
    1: "Fluch der Auen",
    2: "Fluch der Berge",
    3: "Fluch des Eises",
    4: "Fluch der Meere",
    5: "Fluch der Nacht",
    6: "Fluch des Waldes",
    7: "Fluch der Helligkeit",
  }),
  nachtblind("DISADV_25", "Nachtblind", "", {}),
  niedrigeAstralkraft("DISADV_26", "Niedrige Astralkraft", "", {}),
  niedrigeKarmalkraft("DISADV_27", "Niedrige Karmalkraft", "", {}),
  niedrigeLebenskraft("DISADV_28", "Niedrige Lebenskraft", "", {}),
  niedrigeSeelenkraft("DISADV_29", "Niedrige Seelenkraft", "", {}),
  niedrigeZaehigkeit("DISADV_30", "Niedrige Zähigkeit", "", {}),
  pech("DISADV_31", "Pech", "", {}),
  pechmagnet("DISADV_32", "Pechmagnet", "", {}),
  persoenlichkeitsschwaechen("DISADV_33", "Persönlichkeitsschwächen", "", {
    1: "Arroganz",
    2: "Eitelkeit",
    3: "Neid",
    4: "Streitsucht",
    5: "Unheimlich",
    6: "Verwöhnt",
    7: "Vorurteile",
    8: "Weltfremd",
    9: "Anzügliches Verhalten",
    10: "Eifersucht",
    11: "Busenkomplexe",
    12: "Peniskomplexe",
    13: "Stimmungsschwankungen",
  }),
  prinzipientreue("DISADV_34", "Prinzipientreue", "", {
    1: "99 Gesetze",
    2: "Moralkodex der Hesindekirche",
    3: "Moralkodex der Phexkirche",
    4: "Moralkodex der Perainekirche",
    5: "Ehrenkodex der Krieger",
    6: "Ehrenkodex der Ritter",
    7: "Elfische Weltsicht",
    8: "Moralkodex der Boronkirche",
    9: "Moralkodex der Praioskirche",
    10: "Moralkodex der Rondrakirche",
    11: "Zwergischer Ehrenkodex",
    12: "Pazifismus",
    13: "Moralkodex der Efferdkirche",
    14: "Moralkodex der Traviakirche",
    15: "Moralkodex der Firunkirche",
    16: "Moralkodex der Tsakirche",
    17: "Moralkodex der Ingerimmkirche",
    18: "Moralkodex der Rahjakirche",
    19: "Moralkodex der Aveskirche",
    20: "Moralkodex der Ifirnkirche",
    21: "Moralkodex der Korkirche",
    22: "Moralkodex der Nanduskirche",
    23: "Moralkodex der Swafnirkirche",
  }),
  schlafwandler("DISADV_35", "Schlafwandler", "", {}),
  schlechteAngewohnheit("DISADV_36", "Schlechte Angewohnheit", "", {
    1: "Barfüßer",
    2: "Belästigung",
    3: "Dritte Person",
    4: "Duzer",
    5: "Erster",
    6: "Heulsuse",
    7: "Hypochonder",
    8: "Junge",
    9: "Langschläfer",
    10: "Links-Rechts-Schwäche",
    11: "Mein Kind",
    12: "Nägelkauer",
    13: "Nase-/Ohrenbohrer",
    14: "Nervös",
    15: "Putzfimmel",
    16: "Raucher",
    17: "Redet wie ein Wasserfall",
    18: "Schlechte Tischmanieren",
    19: "Selbstgespräche",
    20: "Unordentlich",
    21: "Wir",
    22: "Falscher Name",
    23: "He du! / He ihr!",
    24: "Namensnenner",
    25: "Namensverdreher",
    26: "Anspielungen",
    27: "Lauter Liebhaber",
    28: "Miese Anmache",
    29: "Nur im Dunkeln",
    30: "Prüde",
    31: "Schamlos",
    32: "Schwärmerei",
  }),
  schlechteEigenschaft("DISADV_37", "Schlechte Eigenschaft", "", {
    1: "Aberglaube",
    2: "Autoritätsglaube",
    3: "Geiz",
    4: "Goldgier",
    5: "Jähzorn",
    6: "Kleptomanie",
    7: "Naiv",
    8: "Neugier",
    9: "Rachsucht",
    10: "Spielsucht",
    11: "Verschwendungssucht",
    12: "Exhibitionismus",
    13: "Lüsternheit",
    14: "Voyeurismus",
    15: "Sikaryan-Durst",
  }),
  schlechteRegenerationAstralenergie(
    "DISADV_38",
    "Schlechte Regeneration (Astralenergie)",
    "",
    {},
  ),
  schlechteRegenerationKarmalenergie(
    "DISADV_39",
    "Schlechte Regeneration (Karmalenergie)",
    "",
    {},
  ),
  schlechteRegenerationLebensenergie(
    "DISADV_40",
    "Schlechte Regeneration (Lebensenergie)",
    "",
    {},
  ),
  schwacherAstralkoerper("DISADV_41", "Schwacher Astralkörper", "", {}),
  schwacherKarmalkoerper("DISADV_42", "Schwacher Karmalkörper", "", {}),
  sensiblerGeruchssinn("DISADV_43", "Sensibler Geruchssinn", "", {}),
  sprachfehler("DISADV_44", "Sprachfehler", "", {}),
  stigma("DISADV_45", "Stigma", "", {
    1: "Albino",
    2: "Brandmale",
    3: "Grüne Haare",
    4: "Katzenhafte Augen",
    5: "Schlangenschuppen",
  }),
  stumm("DISADV_46", "Stumm", "", {}),
  taub("DISADV_47", "Taub", "", {}),
  unfaehig("DISADV_48", "Unfähig", "", {}),
  unfrei("DISADV_49", "Unfrei", "", {}),
  verpflichtungen("DISADV_50", "Verpflichtungen", "", {
    1: "Sippenmitglied gegenüber der Sippe",
    2: "Verschuldeter Held",
    3: "Adliger gegenüber seinem Lehnsherrn",
    4: "Geweihter gegenüber seiner Kirche",
    5: "Geweihter gegenüber seinem Tempel",
    6: "Magier gegenüber seinem Lehrmeister",
    7: "Magier gegenüber seiner Akademie",
    8: "Magier gegenüber seiner Gilde",
    9: "Mitglied einer radikalen Sekte gegenüber den Anführern der Gruppe",
  }),
  verstuemmelt("DISADV_51", "Verstümmelt", "", {
    1: "Einarmig",
    2: "Einäugig",
    3: "Einbeinig",
    4: "Einhändig",
    5: "Einohrig",
    6: "Eunuch I",
    7: "Eunuch II",
  }),
  wahrerName("DISADV_52", "Wahrer Name", "", {}),
  wildeMagie("DISADV_53", "Wilde Magie", "", {}),
  zauberanfaellig("DISADV_54", "Zauberanfällig", "", {}),
  zerbrechlich("DISADV_55", "Zerbrechlich", "", {}),
  glaesern("DISADV_56", "Gläsern", "", {}),
  verweichlicht("DISADV_57", "Verweichlicht", "", {}),
  instabilerZauberer("DISADV_58", "Instabiler Zauberer", "", {}),
  kleineZauberauswahl("DISADV_59", "Kleine Zauberauswahl", "", {}),
  schwacheZaubermelodien("DISADV_60", "Schwache Zaubermelodien", "", {}),
  schwacheZaubertaenze("DISADV_61", "Schwache Zaubertänze", "", {}),
  verminderteZaubermelodien("DISADV_62", "Verminderte Zaubermelodien", "", {}),
  verminderteZaubertaenze("DISADV_63", "Verminderte Zaubertänze", "", {}),
  jagdwildgeruch("DISADV_64", "Jagdwildgeruch", "", {}),
  raubtiergeruch("DISADV_65", "Raubtiergeruch", "", {}),
  boeserNamensvetter("DISADV_66", "Böser Namensvetter", "", {}),
  laecherlicherName("DISADV_67", "Lächerlicher Name", "", {}),
  schlechtesNamensgedaechtnis(
    "DISADV_68",
    "Schlechtes Namensgedächtnis",
    "",
    {},
  ),
  schurkenname("DISADV_69", "Schurkenname", "", {}),
  unpassenderName("DISADV_70", "Unpassender Name", "", {}),
  unvertraeglichkeitGegenueberAlkohol(
    "DISADV_71",
    "Unverträglichkeit gegenüber Alkohol",
    "",
    {},
  ),
  wenigePredigten("DISADV_72", "Wenige Predigten", "", {}),
  wenigeVisionen("DISADV_73", "Wenige Visionen", "", {}),
  lernfaul("DISADV_74", "Lernfaul", "", {}),
  abneigungSexpraktik("DISADV_75", "Abneigung (Sexpraktik)", "", {}),
  fixierung("DISADV_76", "Fixierung", "", {}),
  frigide("DISADV_77", "Frigide", "", {}),
  homophobieHeterophobie("DISADV_78", "Homophobie/Heterophobie", "", {}),
  schlechterGeschmack("DISADV_79", "Schlechter Geschmack", "", {}),
  unerotischeStimme("DISADV_80", "Unerotische Stimme", "", {}),
  untreu("DISADV_81", "Untreu", "", {}),
  verfruehterHoehepunkt("DISADV_82", "Verfrühter Höhepunkt", "", {}),
  impotent("DISADV_84", "Impotent", "", {}),
  unfruchtbar("DISADV_85", "Unfruchtbar", "", {}),
  laestigeBluetenfeen("DISADV_86", "Lästige Blütenfeen", "", {});
  // </db-replace-token>

  final String id;
  final String name;
  final String rules;
  final Map<int, String> selectOptions;
  const ActivatableBase(this.id, this.name, this.rules, this.selectOptions);
  static Map<String, ActivatableBase> get byID => {
    for (var it in ActivatableBase.values) it.id: it,
  };
}
