// TODO: Differentiate between "passiv", "Basismanöver" and "Spezialmanöver".

enum SpecialAbilityBase {
  // <db-replace-token>
  aufmerksamkeit("SA_40", "Aufmerksamkeit", "", 1),
  belastungsgewoehnung("SA_41", "Belastungsgewöhnung", "", 1),
  beidhaendigerKampf("SA_42", "Beidhändiger Kampf", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_9',
    'CT_10',
    'CT_12',
  ]),
  berittenerKampf("SA_43", "Berittener Kampf", "", 1),
  berittenerSchuetze("SA_44", "Berittener Schütze", "", [
    'CT_1',
    'CT_2',
    'CT_11',
    'CT_14',
  ]),
  einhaendigerKampf("SA_45", "Einhändiger Kampf", "", ['CT_4', 'CT_12']),
  entwaffnen("SA_46", "Entwaffnen", "", [
    'CT_4',
    'CT_5',
    'CT_8',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  feindgespuer("SA_47", "Feindgespür", "", 1),
  finte("SA_48", "Finte", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_8',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  haltegriff("SA_49", "Haltegriff", "", ['CT_9']),
  hammerschlag("SA_50", "Hammerschlag", "", [
    'CT_5',
    'CT_6',
    'CT_12',
    'CT_15',
    'CT_16',
  ]),
  kampfreflexe("SA_51", "Kampfreflexe", "", 1),
  klingenfaenger("SA_52", "Klingenfänger", "", ['CT_3']),
  kreuzblock("SA_53", "Kreuzblock", "", ['CT_3', 'CT_4']),
  lanzenangriff("SA_54", "Lanzenangriff", "", ['CT_7']),
  praeziserSchussWurf("SA_55", "Präziser Schuss/Wurf", "", [
    'CT_1',
    'CT_18',
    'CT_2',
    'CT_19',
    'CT_11',
    'CT_14',
  ]),
  praeziserStich("SA_56", "Präziser Stich", "", ['CT_3', 'CT_4']),
  riposte("SA_57", "Riposte", "", ['CT_3', 'CT_4']),
  rundumschlag("SA_58", "Rundumschlag", "", [
    'CT_5',
    'CT_6',
    'CT_10',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  schildspalter("SA_59", "Schildspalter", "", [
    'CT_5',
    'CT_6',
    'CT_15',
    'CT_16',
  ]),
  schnellladen("SA_60", "Schnellladen", "", [
    'CT_1',
    'CT_18',
    'CT_2',
    'CT_19',
    'CT_11',
    'CT_14',
  ]),
  schnellziehen("SA_61", "Schnellziehen", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_8',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  sturmangriff("SA_62", "Sturmangriff", "", [
    'CT_5',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  todesstoss("SA_63", "Todesstoß", "", ['CT_3', 'CT_4']),
  verbessertesAusweichen("SA_64", "Verbessertes Ausweichen", "", 1),
  verteidigungshaltung("SA_65", "Verteidigungshaltung", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_9',
    'CT_10',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  vorstoss("SA_66", "Vorstoß", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  wuchtschlag("SA_67", "Wuchtschlag", "", [
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  wurf("SA_68", "Wurf", "", ['CT_9']),
  zuFallBringen("SA_69", "Zu Fall bringen", "", ['CT_8', 'CT_13']),
  armbrustUeberdrehen("SA_151", "Armbrust überdrehen", "", ['CT_1']),
  aufDistanzHalten("SA_152", "Auf Distanz halten", "", 2),
  ballistischerSchuss("SA_153", "Ballistischer Schuss", "", ['CT_2']),
  berittenerFlugkampf("SA_154", "Berittener Flugkampf", "", 1),
  beschuetzer("SA_155", "Beschützer", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_10',
    'CT_12',
    'CT_13',
  ]),
  betaeubungsschlag("SA_156", "Betäubungsschlag", "", [
    'CT_5',
    'CT_12',
    'CT_13',
  ]),
  blindkampf("SA_157", "Blindkampf", "", 2),
  eisenhagel("SA_158", "Eisenhagel", "", "Diskusse (nur Stufe I), Wurfwaffen"),
  festnageln("SA_159", "Festnageln", "", ['CT_13']),
  gezielterAngriff("SA_160", "Gezielter Angriff", "", 2),
  gezielterSchuss("SA_161", "Gezielter Schuss", "", 3),
  herunterstossen("SA_162", "Herunterstoßen", "", ['CT_13']),
  kampfImWasser("SA_163", "Kampf im Wasser", "", 2),
  kampfstilKombination(
    "SA_164",
    "Kampfstil-Kombination",
    "",
    "je nach Kampfstil; die beiden Kampfstile lassen sich jeweils nur für die entsprechenden Kampftechniken nutzen",
  ),
  klingensturm("SA_165", "Klingensturm", "", ['CT_4', 'CT_12']),
  meisterDerImprovisiertenWaffen(
    "SA_166",
    "Meister der improvisierten Waffen",
    "",
    1,
  ),
  meisterlichesAusweichen("SA_167", "Meisterliches Ausweichen", "", []),
  meisterparade("SA_168", "Meisterparade", "", 4),
  pikenwall("SA_169", "Pikenwall", "", ['CT_13']),
  scharfschuetze("SA_170", "Scharfschütze", "", [
    'CT_1',
    'CT_18',
    'CT_2',
    'CT_19',
    'CT_11',
    'CT_14',
  ]),
  schwitzkasten("SA_171", "Schwitzkasten", "", ['CT_9']),
  unterlaufen("SA_172", "Unterlaufen", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_10',
    'CT_12',
    'CT_15',
    'CT_16',
  ]),
  verbessertesUnterlaufen("SA_173", "Verbessertes Unterlaufen", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_10',
    'CT_12',
    'CT_15',
    'CT_16',
  ]),
  verteilterEisenhagel("SA_174", "Verteilter Eisenhagel", "", [
    'CT_19',
    'CT_14',
  ]),
  zweihaendigerReiterkampf("SA_175", "Zweihändiger Reiterkampf", "", [
    'CT_15',
    'CT_16',
  ]),
  unterwasserkampf("SA_418", "Unterwasserkampf", "", []),
  auflaufen("SA_860", "Auflaufen", "", ['CT_7', 'CT_21']),
  spiessgespann("SA_861", "Spießgespann", "", []),
  formation("SA_862", "Formation", "", 1),
  ausfall("SA_864", "Ausfall", "", ['CT_3', 'CT_20', 'CT_4']),
  beritteneLanzenformation("SA_865", "Berittene Lanzenformation", "", ['CT_7']),
  blutgraetsche("SA_866", "Blutgrätsche", "", ['CT_9']),
  doppelangriff("SA_867", "Doppelangriff", "", [
    'CT_3',
    'CT_20',
    'CT_4',
    'CT_5',
    'CT_12',
  ]),
  drachenkampfTaktik("SA_868", "Drachenkampf-Taktik", "", 1),
  durchgezogenerTritt("SA_869", "Durchgezogener Tritt", "", ['CT_9']),
  ellbogenangriff("SA_870", "Ellbogenangriff", "", ['CT_9']),
  gefechtsformation("SA_871", "Gefechtsformation", "", 1),
  gegenhalten("SA_872", "Gegenhalten", "", 4),
  geschossabwehr("SA_873", "Geschossabwehr", "", ['CT_9']),
  graetsche("SA_874", "Grätsche", "", ['CT_9']),
  kernschuss("SA_875", "Kernschuss", "", 3),
  khaFormation("SA_876", "Kha-Formation", "", 1),
  klingeDrehen(
    "SA_877",
    "Klinge drehen",
    "",
    "Dolche, Fechtwaffen, Schwerter, Stangenwaffen (muss eine spitze Klinge haben)",
  ),
  klingentaenzer("SA_878", "Klingentänzer", "", 1),
  kraftvollerSpeerwurf(
    "SA_879",
    "Kraftvoller Speerwurf",
    "",
    "Wurfwaffen (nur Wurfspeere)",
  ),
  lanzenfuehrung("SA_880", "Lanzenführung", "", ['CT_7']),
  machtvolleMeisterparade("SA_881", "Machtvolle Meisterparade", "", 4),
  meisterlicheGeschossabwehr("SA_882", "Meisterliche Geschossabwehr", "", [
    'CT_9',
  ]),
  meisterlicherKlingentaenzer("SA_883", "Meisterlicher Klingentänzer", "", 1),
  plaenklerFormation("SA_884", "Plänkler-Formation", "", 1),
  querschuss("SA_885", "Querschuss", "", ['CT_2']),
  reissangriff("SA_886", "Reißangriff", "", ['CT_6']),
  schildschlag("SA_887", "Schildschlag", "", []),
  turnierreiterei("SA_888", "Turnierreiterei", "", ['CT_7']),
  umrennen("SA_889", "Umrennen", "", ['CT_9']),
  umwickeln("SA_890", "Umwickeln", "", ['CT_6', 'CT_8']),
  ungeheuerTaktik("SA_891", "Ungeheuer-Taktik", "", 1),
  weitwurf("SA_892", "Weitwurf", "", []),
  wirbelangriff("SA_893", "Wirbelangriff", "", [
    'CT_3',
    'CT_20',
    'CT_4',
    'CT_9',
  ]);
  // </db-replace-token>

  final String id;
  final String name;
  final String rules;
  final dynamic ct;

  const SpecialAbilityBase(this.id, this.name, this.rules, this.ct);
}
