enum EyeColour {
  amethystviolett(1, "amethystviolett"),
  bernsteinfarben(2, "bernsteinfarben"),
  blau(3, "blau"),
  braun(4, "braun"),
  dunkelbraun(5, "dunkelbraun"),
  dunkelviolett(6, "dunkelviolett"),
  eisgrau(7, "eisgrau"),
  goldgesprenkelt(8, "goldgesprenkelt"),
  grau(9, "grau"),
  graublau(10, "graublau"),
  gruen(11, "grün"),
  hellbraun(12, "hellbraun"),
  rubinrot(13, "rubinrot"),
  saphirblau(14, "saphirblau"),
  schwarz(15, "schwarz"),
  schwarzbraun(16, "schwarzbraun"),
  silbergrau(17, "silbergrau"),
  smaragdgruen(18, "smaragdgrün"),
  rot(19, "rot"),
  violett(20, "violett");

  final int id;
  final String name;
  const EyeColour(this.id, this.name);

  @override
  String toString() {
    return name;
  }
}

const Map<int, EyeColour> eyeColourById = {
  1: EyeColour.amethystviolett,
  2: EyeColour.bernsteinfarben,
  3: EyeColour.blau,
  4: EyeColour.braun,
  5: EyeColour.dunkelbraun,
  6: EyeColour.dunkelviolett,
  7: EyeColour.eisgrau,
  8: EyeColour.goldgesprenkelt,
  9: EyeColour.grau,
  10: EyeColour.graublau,
  11: EyeColour.gruen,
  12: EyeColour.hellbraun,
  13: EyeColour.rubinrot,
  14: EyeColour.saphirblau,
  15: EyeColour.schwarz,
  16: EyeColour.schwarzbraun,
  17: EyeColour.silbergrau,
  18: EyeColour.smaragdgruen,
  19: EyeColour.rot,
  20: EyeColour.violett,
};

enum HairColour {
  blauschwarz(1, "blauschwarz"),
  blond(2, "blond"),
  braun(3, "braun"),
  dunkelblond(4, "dunkelblond"),
  dunkelbraun(5, "dunkelbraun"),
  goldblond(6, "goldblond"),
  grau(7, "grau"),
  hellblond(8, "hellblond"),
  hellbraun(9, "hellbraun"),
  kupferrot(10, "kupferrot"),
  mittelblond(11, "mittelblond"),
  mittelbraun(12, "mittelbraun"),
  rot(13, "rot"),
  rotblond(14, "rotblond"),
  schneeweiss(15, "schneeweiß"),
  schwarz(16, "schwarz"),
  silbern(17, "silbern"),
  weissblond(18, "weißblond"),
  dunkelgrau(19, "dunkelgrau"),
  hellgrau(20, "hellgrau"),
  salzweiss(21, "salzweiß"),
  silberweiss(22, "silberweiß"),
  feuerrot(23, "feuerrot"),
  weiss(24, "weiß"),
  gruen(25, "grün");

  final int id;
  final String name;
  const HairColour(this.id, this.name);

  @override
  String toString() {
    return name;
  }
}

const Map<int, HairColour> hairColourById = {
  1: HairColour.blauschwarz,
  2: HairColour.blond,
  3: HairColour.braun,
  4: HairColour.dunkelblond,
  5: HairColour.dunkelbraun,
  6: HairColour.goldblond,
  7: HairColour.grau,
  8: HairColour.hellblond,
  9: HairColour.hellbraun,
  10: HairColour.kupferrot,
  11: HairColour.mittelblond,
  12: HairColour.mittelbraun,
  13: HairColour.rot,
  14: HairColour.rotblond,
  15: HairColour.schneeweiss,
  16: HairColour.schwarz,
  17: HairColour.silbern,
  18: HairColour.weissblond,
  19: HairColour.dunkelgrau,
  20: HairColour.hellgrau,
  21: HairColour.salzweiss,
  22: HairColour.silberweiss,
  23: HairColour.feuerrot,
  24: HairColour.weiss,
  25: HairColour.gruen,
};

enum Profession {
  barde("P_1", "Barde", "Bardin", "", ""),
  gardist("P_2", "Gardist", "Gardistin", "", ""),
  gaukler("P_3", "Gaukler", "Gauklerin", "", ""),
  gladiator("P_4", "Gladiator", "Gladiatorin", "", ""),
  haendler("P_5", "Händler", "Händlerin", "", ""),
  heiler("P_6", "Heiler", "Heilerin", "", ""),
  hoefling("P_7", "Höfling", "Höfling", "", ""),
  jaeger("P_8", "Jäger", "Jägerin", "", ""),
  krieger("P_9", "Krieger", "Kriegerin", "", ""),
  prostituierter("P_10", "Prostituierter", "Prostituierte", "", ""),
  ritter("P_11", "Ritter", "Ritterin", "", ""),
  seefahrer("P_12", "Seefahrer", "Seefahrerin", "", ""),
  soeldner("P_13", "Söldner", "Söldnerin", "", ""),
  spitzel("P_14", "Spitzel", "Spitzelin", "", ""),
  stammeskrieger("P_15", "Stammeskrieger", "Stammeskriegerin", "", ""),
  streuner("P_16", "Streuner", "Streunerin", "", ""),
  wildnislaeufer("P_17", "Wildnisläufer", "Wildnisläuferin", "", ""),
  zauberweber("P_18", "Zauberweber", "Zauberweberin", "", ""),
  katzenhexer(
    "P_19",
    "Katzenhexer",
    "Katzenhexe",
    "Schöne der Nacht",
    "Schöne der Nacht",
  ),
  kroetenhexer(
    "P_20",
    "Krötenhexer",
    "Krötenhexe",
    "Töchter der Erde",
    "Töchter der Erde",
  ),
  rabenhexer(
    "P_21",
    "Rabenhexer",
    "Rabenhexe",
    "Seher von Heute und Morgen",
    "Seherin von Heute und Morgen",
  ),
  gildenloserMagier(
    "P_22",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Schüler des Magister Dagabor",
    "Schülerin des Magister Dagabor",
  ),
  graumagier(
    "P_23",
    "Graumagier",
    "Graumagierin",
    "Schule der Verformungen zu Lowangen",
    "Schule der Verformungen zu Lowangen",
  ),
  schwarzmagier(
    "P_24",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Akademie der Geistigen Kraft zu Fasar",
    "Akademie der Geistigen Kraft zu Fasar",
  ),
  weissmagier(
    "P_25",
    "Weißmagier",
    "Weißmagierin",
    "Akademie Schwert und Stab zu Gareth",
    "Akademie Schwert und Stab zu Gareth",
  ),
  borongeweihter("P_26", "Borongeweihter", "Borongeweihte", "", ""),
  hesindegeweihter("P_27", "Hesindegeweihter", "Hesindegeweihte", "", ""),
  perainegeweihter("P_28", "Perainegeweihter", "Perainegeweihte", "", ""),
  phexgeweihter("P_29", "Phexgeweihter", "Phexgeweihte", "", ""),
  praiosgeweihter("P_30", "Praiosgeweihter", "Praiosgeweihte", "", ""),
  rondrageweihter("P_31", "Rondrageweihter", "Rondrageweihte", "", ""),
  adersinSchwertgeselle(
    "P_32",
    "Adersin-Schwertgeselle",
    "Adersin-Schwertgesellin",
    "",
    "",
  ),
  adliger("P_33", "Adliger", "Adlige", "", ""),
  baburinerKrieger("P_34", "Baburiner Krieger", "Baburiner Kriegerin", "", ""),
  balihoerKrieger("P_35", "Balihoer Krieger", "Balihoer Kriegerin", "", ""),
  bauer("P_36", "Bauer", "Bäuerin", "", ""),
  dajinBuskur("P_37", "Dajin-Buskur", "Dajin-Buskur", "", ""),
  diener("P_38", "Diener", "Dienerin", "", ""),
  elenvinerKrieger("P_39", "Elenviner Krieger", "Elenviner Kriegerin", "", ""),
  entdecker("P_40", "Entdecker", "Entdeckerin", "", ""),
  fedorinoSchwertgeselle(
    "P_41",
    "Fedorino-Schwertgeselle",
    "Fedorino-Schwertgeselle",
    "",
    "",
  ),
  gelehrter("P_42", "Gelehrter", "Gelehrte", "", ""),
  hirte("P_43", "Hirte", "Hirtin", "", ""),
  hylailerKrieger("P_44", "Hylailer Krieger", "Hylailer Kriegerin", "", ""),
  kuenstler("P_45", "Künstler", "Künstlerin", "", ""),
  marwanSahibBalayan(
    "P_46",
    "Marwan Sahib-Balayan",
    "Marwan Sahib-Balayan",
    "",
    "",
  ),
  mechanikus("P_47", "Mechanikus", "Mechanika", "", ""),
  mengbillerKrieger(
    "P_48",
    "Mengbiller Krieger",
    "Mengbiller Kriegerin",
    "",
    "",
  ),
  premerKrieger("P_49", "Premer Krieger", "Premer Kriegerin", "", ""),
  schmied("P_50", "Schmied", "Schmiedin", "", ""),
  sklave("P_51", "Sklave", "Sklavin", "", ""),
  soldat("P_52", "Soldat", "Soldatin", "", ""),
  tageloehner("P_53", "Tagelöhner", "Tagelöhner", "", ""),
  wildniskundiger("P_54", "Wildniskundiger", "Wildniskundige", "", ""),
  wirt("P_55", "Wirt", "Wirtin", "", ""),
  zuckerbaecker("P_56", "Zuckerbäcker", "Zuckerbäckerin", "", ""),
  ceoladir("P_57", "Ceoladir", "Ceoladir", "", ""),
  derwisch("P_58", "Derwisch", "Derwisch", "", ""),
  schuelerDesAlrikDagabor(
    "P_59",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Schüler des Alrik Dagabor",
    "Schülerin des Alrik Dagabor",
  ),
  seminarDerElfischenVerstaendigungUndNatuerlichenHeilungZuDonnerbach(
    "P_60",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Seminar der elfischen Verständigung und natürlichen Heilung zu Donnerbach",
    "Seminar der elfischen Verständigung und natürlichen Heilung zu Donnerbach",
  ),
  schuelerDesVadifSalKarim(
    "P_61",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Schüler des Vadif sal Karim",
    "Schülerin des Vadif sal Karim",
  ),
  schuelerDerKhelbaraAyBaburia(
    "P_62",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Schüler der Khelbara ay Baburia",
    "Schülerin der Khelbara ay Baburia",
  ),
  schuleDesDirektenWegesZuGerasim(
    "P_63",
    "Graumagier",
    "Graumagierin",
    "Schule des Direkten Weges zu Gerasim",
    "Schule des Direkten Weges zu Gerasim",
  ),
  halleDerAntimagieZuKuslik(
    "P_64",
    "Graumagier",
    "Graumagierin",
    "Halle der Antimagie zu Kuslik",
    "Halle der Antimagie zu Kuslik",
  ),
  schuleDerHellsichtZuThorwal(
    "P_65",
    "Graumagier",
    "Graumagierin",
    "Schule der Hellsicht zu Thorwal",
    "Schule der Hellsicht zu Thorwal",
  ),
  akademieDerHohenMagieZuPunin(
    "P_66",
    "Graumagier",
    "Graumagierin",
    "Akademie der Hohen Magie zu Punin",
    "Akademie der Hohen Magie zu Punin",
  ),
  schuleDesSeiendenScheinsZuZorgan(
    "P_67",
    "Graumagier",
    "Graumagierin",
    "Schule des Seienden Scheins zu Zorgan",
    "Schule des Seienden Scheins zu Zorgan",
  ),
  schuleDerVerformungenZuLowangen(
    "P_68",
    "Graumagier",
    "Graumagierin",
    "Schule der Verformungen zu Lowangen",
    "Schule der Verformungen zu Lowangen",
  ),
  schuleDerVierfachenVerwandlungZuSinoda(
    "P_69",
    "Graumagier",
    "Graumagierin",
    "Schule der Vierfachen Verwandlung zu Sinoda",
    "Schule der Vierfachen Verwandlung zu Sinoda",
  ),
  hazaqi("P_70", "Hazaqi", "Hazaqi", "", ""),
  magischerTaugenichts(
    "P_71",
    "Magischer Taugenichts",
    "Magische Taugenicht",
    "",
    "",
  ),
  majuna("P_72", "Majuna", "Majuna", "", ""),
  qabalothDerToechterNiobaras(
    "P_73",
    "Qabaloth der Töchter Niobaras",
    "Qabaloth der Töchter Niobaras",
    "",
    "",
  ),
  rahkisa("P_74", "Rahkisa", "Rahkisa", "", ""),
  sangara("P_75", "Sangara", "Sangara", "", ""),
  scharlatan("P_76", "Scharlatan", "Scharlatanin", "", ""),
  halleDerErleuchtungZuAlanfa(
    "P_77",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Halle der Erleuchtung zu Al'Anfa",
    "Halle der Erleuchtung zu Al'Anfa",
  ),
  schuelerDesDemirionOphenos(
    "P_78",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Schüler des Demirion Ophenos",
    "Schülerin des Demirion Ophenos",
  ),
  akademieDerGeistigenKraftZuFasar(
    "P_79",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Akademie der Geistigen Kraft zu Fasar",
    "Akademie der Geistigen Kraft zu Fasar",
  ),
  sharisad("P_80", "Sharisad", "Sharisad", "", ""),
  akademieSchwertUndStabZuGareth(
    "P_81",
    "Weißmagier",
    "Weißmagierin",
    "Akademie Schwert & Stab zu Gareth",
    "Akademie Schwert & Stab zu Gareth",
  ),
  schuelerDesHesindiusLichtblick(
    "P_82",
    "Weißmagier",
    "Weißmagierin",
    "Schüler des Hesindius Lichtblick",
    "Schülerin des Hesindius Lichtblick",
  ),
  schuleDerAustreibungZuPerricum(
    "P_83",
    "Weißmagier",
    "Weißmagierin",
    "Schule der Austreibung zu Perricum",
    "Schule der Austreibung zu Perricum",
  ),
  bogner("P_84", "Bogner", "Bognerin", "", ""),
  deichbauer("P_85", "Deichbauer", "Deichbauerin", "", ""),
  holzfaeller("P_86", "Holzfäller", "Holzfällerin", "", ""),
  ritterDerStreitendenKoenigreiche(
    "P_87",
    "Ritter der Streitenden Königreiche",
    "Ritterin der Streitenden Königreiche",
    "Seenritter",
    "Seenritterin",
  ),
  waldritter(
    "P_88",
    "Ritter der Streitenden Königreiche",
    "Ritterin der Streitenden Königreiche",
    "Waldritter",
    "Waldritterin",
  ),
  kampfseminarAndergast(
    "P_89",
    "Graumagier",
    "Graumagierin",
    "Kampfseminar Andergast",
    "Kampfseminar Andergast",
  ),
  akademieVonLichtUndDunkelheit(
    "P_90",
    "Weißmagier",
    "Weißmagierin",
    "Akademie von Licht und Dunkelheit",
    "Akademie von Licht und Dunkelheit",
  ),
  eulenhexer(
    "P_91",
    "Eulenhexer",
    "Eulenhexe",
    "Verschwiegene Schwesternschaft",
    "Verschwiegene Schwesternschaft",
  ),
  schlangenhexer(
    "P_92",
    "Schlangenhexer",
    "Schlangenhexe",
    "Schwesternschaft des Wissens",
    "Schwesternschaft des Wissens",
  ),
  druide("P_93", "Druide", "Druidin", "Mehrer der Macht", "Mehrerin der Macht"),
  sumudiener("P_94", "Druide", "Druidin", "Sumudiener", "Sumudienerin"),
  efferdgeweihter("P_95", "Efferdgeweihter", "Efferdgeweihte", "", ""),
  traviageweihter("P_96", "Traviageweihter", "Traviageweihte", "", ""),
  firungeweihter("P_97", "Firungeweihter", "Firungeweihte", "", ""),
  tsageweihter("P_98", "Tsageweihter", "Tsageweihte", "", ""),
  ingerimmgeweihter("P_99", "Ingerimmgeweihter", "Ingerimmgeweihte", "", ""),
  rahjageweihter("P_100", "Rahjageweihter", "Rahjageweihte", "", ""),
  avesgeweihter("P_101", "Avesgeweihter", "Avesgeweihte", "", ""),
  ifirngeweihter("P_102", "Ifirngeweihter", "Ifirngeweihte", "", ""),
  korgeweihter("P_103", "Korgeweihter", "Korgeweihte", "", ""),
  nandusgeweihter("P_104", "Nandusgeweihter", "Nandusgeweihte", "", ""),
  swafnirgeweihter("P_105", "Swafnirgeweihter", "Swafnirgeweihte", "", ""),
  amazone("P_106", "Amazone", "Amazone", "", ""),
  draconiter("P_107", "Draconiter", "Draconiterin", "", ""),
  golgarit("P_108", "Golgarit", "Golgaritin", "", ""),
  namenloserGeweihter(
    "P_109",
    "Namenloser-Geweihter",
    "Namenloser-Geweihte",
    "",
    "",
  ),
  distelritter("P_110", "Distelritter", "Distelritterin", "", ""),
  heckenreiter("P_111", "Heckenreiter", "Heckenreiterin", "", ""),
  kuestenschmuggler("P_112", "Küstenschmuggler", "Küstenschmugglerin", "", ""),
  havenerKrieger("P_113", "Havener Krieger", "Havener Kriegerin", "", ""),
  schwertgeselleNachScanlailNiUinin(
    "P_114",
    "Schwertgeselle nach Scanlail ni Uinin",
    "Schwertgesellin nach Scanlail ni Uinin",
    "",
    "",
  ),
  seesoldat("P_115", "Seesoldat", "Seesoldatin", "", ""),
  windhagerSippenkrieger(
    "P_116",
    "Windhager Sippenkrieger",
    "Windhager Sippenkriegerin",
    "",
    "",
  ),
  winhallerKrieger("P_117", "Winhaller Krieger", "Winhaller Kriegerin", "", ""),
  schuelerDesHoningerCollegiums(
    "P_118",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Schüler des Honinger Collegiums",
    "Schülerin des Honinger Collegiums",
  ),
  kiranyaVonKutaki(
    "P_119",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Kiranya von Kutaki",
    "Kiranya von Kutaki",
  ),
  kreisDerEinfuehlung(
    "P_120",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Kreis der Einfühlung",
    "Kreis der Einfühlung",
  ),
  rafimBey(
    "P_121",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Rafim Bey",
    "Rafim Bey",
  ),
  sevastanaGevendar(
    "P_122",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Sevastana Gevendar",
    "Sevastana Gevendar",
  ),
  kampfseminarZuAndergast(
    "P_123",
    "Graumagier",
    "Graumagierin",
    "Kampfseminar zu Andergast",
    "Kampfseminar zu Andergast",
  ),
  akademieDerGeistreisenZuBelhanka(
    "P_124",
    "Graumagier",
    "Graumagierin",
    "Akademie der Geistreisen zu Belhanka",
    "Akademie der Geistreisen zu Belhanka",
  ),
  halleDesVollendetenKampfesZuBethana(
    "P_125",
    "Graumagier",
    "Graumagierin",
    "Halle des vollendeten Kampfes zu Bethana",
    "Halle des vollendeten Kampfes zu Bethana",
  ),
  halleDesQuecksilbersZuFestum(
    "P_126",
    "Graumagier",
    "Graumagierin",
    "Halle des Quecksilbers zu Festum",
    "Halle des Quecksilbers zu Festum",
  ),
  akademieDerErscheinungenZuGrangor(
    "P_127",
    "Graumagier",
    "Graumagierin",
    "Akademie der Erscheinungen zu Grangor",
    "Akademie der Erscheinungen zu Grangor",
  ),
  stoerrebrandtKollegZuRiva(
    "P_128",
    "Graumagier",
    "Graumagierin",
    "Stoerrebrandt-Kolleg zu Riva",
    "Stoerrebrandt-Kolleg zu Riva",
  ),
  halleDerMachtZuLowangen(
    "P_129",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Halle der Macht zu Lowangen",
    "Halle der Macht zu Lowangen",
  ),
  akademieDerHerrschaftZuElenvina(
    "P_130",
    "Weißmagier",
    "Weißmagierin",
    "Akademie der Herrschaft zu Elenvina",
    "Akademie der Herrschaft zu Elenvina",
  ),
  akademieDerMagischenRuestungZuGareth(
    "P_131",
    "Weißmagier",
    "Weißmagierin",
    "Akademie der magischen Rüstung zu Gareth",
    "Akademie der magischen Rüstung zu Gareth",
  ),
  schuleDesMagischenWissensZuMethumis(
    "P_132",
    "Weißmagier",
    "Weißmagierin",
    "Schule des  magischen Wissens zu Methumis",
    "Schule des  magischen Wissens zu Methumis",
  ),
  halleDesLebensZuNorburg(
    "P_133",
    "Weißmagier",
    "Weißmagierin",
    "Halle des Lebens zu Norburg",
    "Halle des Lebens zu Norburg",
  ),
  akademieVonLichtUndDunkelheitZuNostria(
    "P_134",
    "Weißmagier",
    "Weißmagierin",
    "Akademie von Licht und Dunkelheit zu Nostria",
    "Akademie von Licht und Dunkelheit zu Nostria",
  ),
  affenhexer(
    "P_135",
    "Affenhexer",
    "Affenhexe",
    "Fahrende Schwesternschaft",
    "Fahrende Schwesternschaft",
  ),
  verschwiegeneSchwesternschaft(
    "P_136",
    "Eulenhexer",
    "Eulenhexe",
    "Verschwiegene Schwesternschaft",
    "Verschwiegene Schwesternschaft",
  ),
  schoeneDerNacht(
    "P_137",
    "Katzenhexer",
    "Katzenhexe",
    "Schöne der Nacht",
    "Schöne der Nacht",
  ),
  toechterDerErde(
    "P_138",
    "Krötenhexer",
    "Krötenhexe",
    "Töchter der Erde",
    "Töchter der Erde",
  ),
  seherVonHeuteUndMorgen(
    "P_139",
    "Rabenhexer",
    "Rabenhexe",
    "Seher von Heute und Morgen",
    "Seherin von Heute und Morgen",
  ),
  schwesternDesWissens(
    "P_140",
    "Schlangenhexer",
    "Schlangenhexe",
    "Schwestern des Wissens",
    "Schwestern des Wissens",
  ),
  spinnenhexer(
    "P_141",
    "Spinnenhexer",
    "Spinnenhexe",
    "Schwesternschaft Schwarze Witwen",
    "Schwesternschaft Schwarze Witwen",
  ),
  bewahrer("P_142", "Bewahrer", "Bewahrerin", "", ""),
  former("P_143", "Former", "Formerin", "", ""),
  kaempfer("P_144", "Kämpfer", "Kämpferin", "", ""),
  legendensaenger("P_145", "Legendensänger", "Legendensängerin", "", ""),
  schelm("P_146", "Schelm", "Schelmin", "", ""),
  zauberalchimist("P_147", "Zauberalchimist", "Zauberalchimistin", "", ""),
  wildnislaeufer2("P_148", "Wildnisläufer", "Wildnisläuferin", "", ""),
  zauberweber2("P_149", "Zauberweber", "Zauberweberin", "", ""),
  apothekarius("P_150", "Apothekarius", "Apothekarius", "", ""),
  auftragsmoerder("P_151", "Auftragsmörder", "Auftragsmörderin", "", ""),
  bader("P_152", "Bader", "Baderin", "", ""),
  bote("P_153", "Bote", "Botin", "", ""),
  fallensteller("P_154", "Fallensteller", "Fallenstellerin", "", ""),
  fleischer("P_155", "Fleischer", "Fleischerin", "", ""),
  garetherKrieger("P_156", "Garether Krieger", "Garether Kriegerin", "", ""),
  herrscher("P_157", "Herrscher", "Herrscherin", "", ""),
  holzfaeller2("P_158", "Holzfäller", "Holzfällerin", "", ""),
  ishannahAlkiraBalayan(
    "P_159",
    "Ishannah al'Kira-Balayan",
    "Ishannah al'Kira-Balayan",
    "",
    "",
  ),
  karawanenfuehrer("P_160", "Karawanenführer", "Karawanenführerin", "", ""),
  kontorist("P_161", "Kontorist", "Kontoristin", "", ""),
  landwehrsoldat("P_162", "Landwehrsoldat", "Landwehrsoldatin", "", ""),
  lanisto("P_163", "Lanisto", "Lanisto", "", ""),
  logenmitglied("P_164", "Logenmitglied", "Logenmitglied", "", ""),
  mawdli("P_165", "Mawdli", "Mawdli", "", ""),
  albernischerSeefahrer(
    "P_166",
    "Albernischer Seefahrer",
    "Albernische Seefahrerin",
    "",
    "",
  ),
  kuestenschmugglerAusHavena(
    "P_167",
    "Küstenschmuggler aus Havena",
    "Küstenschmugglerin aus Havena",
    "",
    "",
  ),
  schatzsucherDerSiebenwindkueste(
    "P_168",
    "Schatzsucher der Siebenwindküste",
    "Schatzsucherin der Siebenwindküste",
    "",
    "",
  ),
  efferdgeweihterDerSiebwindkueste(
    "P_169",
    "Efferdgeweihter der Siebwindküste",
    "Efferdgeweihte der Siebwindküste",
    "",
    "",
  ),
  numinorupriester("P_170", "Numinorupriester", "Numinorupriesterin", "", ""),
  metessaGaloraSchwertgeselle(
    "P_171",
    "Metessa Galora-Schwertgeselle",
    "Metessa Galora-Schwertgesellin",
    "",
    "",
  ),
  neersanderKrieger(
    "P_172",
    "Neersander Krieger",
    "Neersander Kriegerin",
    "",
    "",
  ),
  patrizier("P_173", "Patrizier", "Patrizierin", "", ""),
  prospektor("P_174", "Prospektor", "Prospektorin", "", ""),
  raeuber("P_175", "Räuber", "Räuberin", "", ""),
  rommilyserKrieger(
    "P_176",
    "Rommilyser Krieger",
    "Rommilyser Kriegerin",
    "",
    "",
  ),
  sappeur("P_177", "Sappeur", "Sappeurin", "", ""),
  sarvinioDellaMonteSchwertgeselle(
    "P_178",
    "Sarvinio della Monte-Schwertgeselle",
    "Sarvinio della Monte-Schwertgesellin",
    "",
    "",
  ),
  scanlailUiUininSchwertgeselle(
    "P_179",
    "Scanlail ui Uinin-Schwertgeselle",
    "Scanlail ui Uinin-Schwertgesellin",
    "",
    "",
  ),
  schankbursche("P_180", "Schankbursche", "Schankmagd", "", ""),
  schaukaempfer("P_181", "Schaukämpfer", "Schaukämpferin", "", ""),
  schauspieler("P_182", "Schauspieler", "Schauspielerin", "", ""),
  schmuggler("P_183", "Schmuggler", "Schmugglerin", "", ""),
  schreiber("P_184", "Schreiber", "Schreiberin", "", ""),
  schriftsteller("P_185", "Schriftsteller", "Schriftstellerin", "", ""),
  seekrieger("P_186", "Seekrieger", "Seekriegerin", "", ""),
  stutzer("P_187", "Stutzer", "Stutzerin", "", ""),
  tannhausSchwertgeselle(
    "P_188",
    "Tannhaus-Schwertgeselle",
    "Tannhaus-Schwertgesellin",
    "",
    "",
  ),
  taschendieb("P_189", "Taschendieb", "Taschendiebin", "", ""),
  taetowierer("P_190", "Tätowierer", "Tätowiererin", "", ""),
  thorwalerKrieger("P_191", "Thorwaler Krieger", "Thorwaler Kriegerin", "", ""),
  viehtreiber("P_192", "Viehtreiber", "Viehtreiberin", "", ""),
  vinsalterKrieger("P_193", "Vinsalter Krieger", "Vinsalter Kriegerin", "", ""),
  winhallerKrieger2(
    "P_194",
    "Winhaller Krieger",
    "Winhaller Kriegerin",
    "",
    "",
  ),
  zimmermann("P_195", "Zimmermann", "Zimmerfrau", "", ""),
  kammerdienerZofe("P_196", "Kammerdiener (Zofe)", "Zofe", "", ""),
  zwergenkriegerNachHardas(
    "P_197",
    "Zwergenkrieger nach Hardas",
    "Zwergenkriegerin nach Hardas",
    "",
    "",
  ),
  seenritter(
    "P_198",
    "Ritter der Streitenden Königreiche",
    "Ritterin der Streitenden Königreiche",
    "Seenritter",
    "Seenritterin",
  ),
  ritterDerStreitendenKoenigreiche2(
    "P_199",
    "Ritter der Streitenden Königreiche",
    "Ritterin der Streitenden Königreiche",
    "Waldritter",
    "Waldritterin",
  ),
  mehrerDerMacht(
    "P_200",
    "Druide",
    "Druidin",
    "Mehrer der Macht",
    "Mehrerin der Macht",
  ),
  druide2("P_201", "Druide", "Druidin", "Sumudiener", "Sumudienerin"),
  distelritter2("P_202", "Distelritter", "Distelritterin", "", ""),
  havenerKrieger2("P_203", "Havener Krieger", "Havener Kriegerin", "", ""),
  seesoldat2("P_204", "Seesoldat", "Seesoldatin", "", ""),
  windhagerSippenkrieger2(
    "P_205",
    "Windhager Sippenkrieger",
    "Windhager Sippenkriegerin",
    "",
    "",
  ),
  gildenloserMagier2(
    "P_206",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Schüler des Honinger Collegiums",
    "Schülerin des Honinger Collegiums",
  ),
  erotikkuenstler("P_207", "Erotikkünstler", "Erotikkünstlerin", "", ""),
  prostituierter2("P_210", "Prostituierter", "Prostituierte", "", ""),
  sexualmagier("P_211", "Sexualmagier", "Sexualmagierin", "", ""),
  tsatuaraAnhaenger(
    "P_212",
    "Tsatuara-Anhänger",
    "Tsatuara-Anhängerin",
    "",
    "",
  ),
  levthanpriester("P_213", "Levthanpriester", "Levthanpriesterin", "", ""),
  rahjageweihter2("P_214", "Rahjageweihter", "Rahjageweihte", "", ""),
  rahjasutraMeister(
    "P_215",
    "Rahjasutra-Meister",
    "Rahjasutra-Meisterin",
    "",
    "",
  ),
  saebeltaenzer("P_216", "Säbeltänzer", "Säbeltänzerin", "", ""),
  anachNur(
    "P_217",
    "Anach-Nûr",
    "Anach-Nûr",
    "Ferkina-Besessener",
    "Ferkina-Besessene",
  ),
  durroDun(
    "P_218",
    "Durro-Dûn",
    "Durro-Dûn",
    "Gjalsker Tierkrieger",
    "Gjalsker Tierkriegerin",
  ),
  hadanHarigasta(
    "P_219",
    "Hadan-Harigasta",
    "Hadan-Harigasta",
    "Zauberschmied der Fjarninger",
    "Zauberschmiedin der Fjarninger",
  ),
  mudrannura(
    "P_220",
    "Mudran'Nura",
    "Mudran'Nura",
    "Trollzacker Elementmeister",
    "Trollzacker Elementmeisterin",
  ),
  nipakauKocan(
    "P_221",
    "Nipakau-Kocan",
    "Nipakau-Kocan",
    "Mohischer Geisterkrieger",
    "Mohische Geisterkriegerin",
  ),
  nuan(
    "P_222",
    "Nuan",
    "Nuan",
    "Nivesisches Wolfskind",
    "Nivesisches Wolfskind",
  ),
  haindruide("P_223", "Haindruide", "Haindruidin", "", ""),
  hueterDerKraft("P_224", "Hüter der Kraft", "Hüterin der Kraft", "", ""),
  konzildruide("P_225", "Konzildruide", "Konzildruidin", "", ""),
  mehrerDerMacht2("P_226", "Mehrer der Macht", "Mehrerin der Macht", "", ""),
  sumudiener2("P_227", "Sumudiener", "Sumudienerin", "", ""),
  dienerDerErdmutter(
    "P_228",
    "Diener der Erdmutter",
    "Dienerin der Erdmutter",
    "",
    "",
  ),
  herrDerErde("P_229", "Herr der Erde", "Herrin der Erde", "", ""),
  bannakademieZuFasar(
    "P_230",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Bannakademie zu Fasar",
    "Bannakademie zu Fasar",
  ),
  halleDerWindeZuOlport(
    "P_231",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Halle der Winde zu Olport",
    "Halle der Winde zu Olport",
  ),
  heptagonakademieZuYolGhurmak(
    "P_232",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Heptagonakademie zu Yol-Ghurmak",
    "Heptagonakademie zu Yol-Ghurmak",
  ),
  magierkollegZuHoningen(
    "P_233",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Magierkolleg zu Honingen",
    "Magierkolleg zu Honingen",
  ),
  halibAbulKetab(
    "P_234",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Halib abu'l Ketab",
    "Halib abu'l Ketab",
  ),
  qabalothDerNachtwinde(
    "P_235",
    "Qabaloth der Nachtwinde",
    "Qabalothin der Nachtwinde",
    "",
    "",
  ),
  dracheneiAkademieZuKhunchom(
    "P_236",
    "Graumagier",
    "Graumagierin",
    "Drachenei-Akademie zu Khunchom",
    "Drachenei-Akademie zu Khunchom",
  ),
  zauberschuleDesKalifenZuMherwed(
    "P_237",
    "Graumagier",
    "Graumagierin",
    "Zauberschule des Kalifen zu Mherwed",
    "Zauberschule des Kalifen zu Mherwed",
  ),
  konzilsDerElementeZuDrakonia(
    "P_238",
    "Graumagier",
    "Graumagierin",
    "Konzils der Elemente zu Drakonia",
    "Konzils der Elemente zu Drakonia",
  ),
  pentagrammAkademieZuRashdul(
    "P_239",
    "Graumagier",
    "Graumagierin",
    "Pentagramm-Akademie zu Rashdul",
    "Pentagramm-Akademie zu Rashdul",
  ),
  schuleDerBeherrschungZuNeersand(
    "P_240",
    "Graumagier",
    "Graumagierin",
    "Schule der Beherrschung zu Neersand",
    "Schule der Beherrschung zu Neersand",
  ),
  akademieZuWagenhalt(
    "P_241",
    "Graumagier",
    "Graumagierin",
    "Akademie zu Wagenhalt",
    "Akademie zu Wagenhalt",
  ),
  rashdulerDaemonologe(
    "P_242",
    "Rashduler Dämonologe",
    "Rashduler Dämonologin",
    "",
    "",
  ),
  shanadaVonBenOni(
    "P_243",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Shanada von Ben-Oni",
    "Shanada von Ben-Oni",
  ),
  dunkleHalleDerGeisterZuBrabak(
    "P_244",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Dunkle Halle der Geister zu Brabak",
    "Dunkle Halle der Geister zu Brabak",
  ),
  schuleDerVariablenFormZuMirham(
    "P_245",
    "Schwarzmagier",
    "Schwarzmagierin",
    "Schule der variablen Form zu Mirham",
    "Schule der variablen Form zu Mirham",
  ),
  informationsInstitutsZuRommilys(
    "P_246",
    "Weißmagier",
    "Weißmagierin",
    "Informations-Instituts zu Rommilys",
    "Informations-Instituts zu Rommilys",
  ),
  anatomischeAkademieZuVinsalt(
    "P_247",
    "Weißmagier",
    "Weißmagierin",
    "Anatomische Akademie zu Vinsalt",
    "Anatomische Akademie zu Vinsalt",
  ),
  halleDerMetamorphosenZuKuslik(
    "P_248",
    "Weißmagier",
    "Weißmagierin",
    "Halle der Metamorphosen zu Kuslik",
    "Halle der Metamorphosen zu Kuslik",
  ),
  zibilja("P_249", "Zibilja", "Zibilja", "", ""),
  brobimGeode("P_250", "Brobim-Geode", "Brobim-Geodin", "", ""),
  agrimeton(
    "P_251",
    "Gildenloser Magier",
    "Gildenlose Magierin",
    "Agrimeton",
    "Agrimeton",
  ),
  ferdokerLanzer("P_252", "Ferdoker Lanzer", "Ferdoker Lanzerin", "", ""),
  elenvinerKrieger2(
    "P_253",
    "Elenviner Krieger",
    "Elenviner Kriegerin",
    "",
    "",
  ),
  klippagSchwertgeselle(
    "P_254",
    "Klippag-Schwertgeselle",
    "Klippag-Schwertgesellin",
    "",
    "",
  ),
  koscherAlmgreve("P_255", "Koscher Almgreve", "Koscher Almgrevin", "", ""),
  mechanikus2("P_256", "Mechanikus", "Mechanika", "", ""),
  rechtsgelehrter("P_257", "Rechtsgelehrter", "Rechtsgelehrte", "", ""),
  wandergeselle("P_258", "Wandergeselle", "Wandergesellin", "", ""),
  xorloscherDrachenkaempfer(
    "P_259",
    "Xorloscher Drachenkämpfer",
    "Xorloscher Drachenkämpferin",
    "",
    "",
  ),
  gratenfelserHaindruide(
    "P_260",
    "Gratenfelser Haindruide",
    "Gratenfelser Haindruidin",
    "",
    "",
  ),
  weissmagier2(
    "P_261",
    "Weißmagier",
    "Weißmagierin",
    "Akademie der Herrschaft zu Elenvina",
    "Akademie der Herrschaft zu Elenvina",
  );

  final String id;
  final String maleName;
  final String femaleName;
  final String maleSubName;
  final String femaleSubName;
  const Profession(
    this.id,
    this.maleName,
    this.femaleName,
    this.maleSubName,
    this.femaleSubName,
  );

  String description(String gender) {
    if (gender != "männlich" && gender != "weiblich") {
      gender = "männlich";
    }
    String name, subname;
    if (gender == "männlich") {
      name = maleName;
      subname = maleSubName;
    } else {
      name = femaleName;
      subname = femaleSubName;
    }
    if (subname != "") {
      return "$name ($subname)";
    }
    return name;
  }
}

const Map<String, Profession> professionsById = {
  "P_1": Profession.barde,
  "P_2": Profession.gardist,
  "P_3": Profession.gaukler,
  "P_4": Profession.gladiator,
  "P_5": Profession.haendler,
  "P_6": Profession.heiler,
  "P_7": Profession.hoefling,
  "P_8": Profession.jaeger,
  "P_9": Profession.krieger,
  "P_10": Profession.prostituierter,
  "P_11": Profession.ritter,
  "P_12": Profession.seefahrer,
  "P_13": Profession.soeldner,
  "P_14": Profession.spitzel,
  "P_15": Profession.stammeskrieger,
  "P_16": Profession.streuner,
  "P_17": Profession.wildnislaeufer,
  "P_18": Profession.zauberweber,
  "P_19": Profession.katzenhexer,
  "P_20": Profession.kroetenhexer,
  "P_21": Profession.rabenhexer,
  "P_22": Profession.gildenloserMagier,
  "P_23": Profession.graumagier,
  "P_24": Profession.schwarzmagier,
  "P_25": Profession.weissmagier,
  "P_26": Profession.borongeweihter,
  "P_27": Profession.hesindegeweihter,
  "P_28": Profession.perainegeweihter,
  "P_29": Profession.phexgeweihter,
  "P_30": Profession.praiosgeweihter,
  "P_31": Profession.rondrageweihter,
  "P_32": Profession.adersinSchwertgeselle,
  "P_33": Profession.adliger,
  "P_34": Profession.baburinerKrieger,
  "P_35": Profession.balihoerKrieger,
  "P_36": Profession.bauer,
  "P_37": Profession.dajinBuskur,
  "P_38": Profession.diener,
  "P_39": Profession.elenvinerKrieger,
  "P_40": Profession.entdecker,
  "P_41": Profession.fedorinoSchwertgeselle,
  "P_42": Profession.gelehrter,
  "P_43": Profession.hirte,
  "P_44": Profession.hylailerKrieger,
  "P_45": Profession.kuenstler,
  "P_46": Profession.marwanSahibBalayan,
  "P_47": Profession.mechanikus,
  "P_48": Profession.mengbillerKrieger,
  "P_49": Profession.premerKrieger,
  "P_50": Profession.schmied,
  "P_51": Profession.sklave,
  "P_52": Profession.soldat,
  "P_53": Profession.tageloehner,
  "P_54": Profession.wildniskundiger,
  "P_55": Profession.wirt,
  "P_56": Profession.zuckerbaecker,
  "P_57": Profession.ceoladir,
  "P_58": Profession.derwisch,
  "P_59": Profession.schuelerDesAlrikDagabor,
  "P_60": Profession
      .seminarDerElfischenVerstaendigungUndNatuerlichenHeilungZuDonnerbach,
  "P_61": Profession.schuelerDesVadifSalKarim,
  "P_62": Profession.schuelerDerKhelbaraAyBaburia,
  "P_63": Profession.schuleDesDirektenWegesZuGerasim,
  "P_64": Profession.halleDerAntimagieZuKuslik,
  "P_65": Profession.schuleDerHellsichtZuThorwal,
  "P_66": Profession.akademieDerHohenMagieZuPunin,
  "P_67": Profession.schuleDesSeiendenScheinsZuZorgan,
  "P_68": Profession.schuleDerVerformungenZuLowangen,
  "P_69": Profession.schuleDerVierfachenVerwandlungZuSinoda,
  "P_70": Profession.hazaqi,
  "P_71": Profession.magischerTaugenichts,
  "P_72": Profession.majuna,
  "P_73": Profession.qabalothDerToechterNiobaras,
  "P_74": Profession.rahkisa,
  "P_75": Profession.sangara,
  "P_76": Profession.scharlatan,
  "P_77": Profession.halleDerErleuchtungZuAlanfa,
  "P_78": Profession.schuelerDesDemirionOphenos,
  "P_79": Profession.akademieDerGeistigenKraftZuFasar,
  "P_80": Profession.sharisad,
  "P_81": Profession.akademieSchwertUndStabZuGareth,
  "P_82": Profession.schuelerDesHesindiusLichtblick,
  "P_83": Profession.schuleDerAustreibungZuPerricum,
  "P_84": Profession.bogner,
  "P_85": Profession.deichbauer,
  "P_86": Profession.holzfaeller,
  "P_87": Profession.ritterDerStreitendenKoenigreiche,
  "P_88": Profession.waldritter,
  "P_89": Profession.kampfseminarAndergast,
  "P_90": Profession.akademieVonLichtUndDunkelheit,
  "P_91": Profession.eulenhexer,
  "P_92": Profession.schlangenhexer,
  "P_93": Profession.druide,
  "P_94": Profession.sumudiener,
  "P_95": Profession.efferdgeweihter,
  "P_96": Profession.traviageweihter,
  "P_97": Profession.firungeweihter,
  "P_98": Profession.tsageweihter,
  "P_99": Profession.ingerimmgeweihter,
  "P_100": Profession.rahjageweihter,
  "P_101": Profession.avesgeweihter,
  "P_102": Profession.ifirngeweihter,
  "P_103": Profession.korgeweihter,
  "P_104": Profession.nandusgeweihter,
  "P_105": Profession.swafnirgeweihter,
  "P_106": Profession.amazone,
  "P_107": Profession.draconiter,
  "P_108": Profession.golgarit,
  "P_109": Profession.namenloserGeweihter,
  "P_110": Profession.distelritter,
  "P_111": Profession.heckenreiter,
  "P_112": Profession.kuestenschmuggler,
  "P_113": Profession.havenerKrieger,
  "P_114": Profession.schwertgeselleNachScanlailNiUinin,
  "P_115": Profession.seesoldat,
  "P_116": Profession.windhagerSippenkrieger,
  "P_117": Profession.winhallerKrieger,
  "P_118": Profession.schuelerDesHoningerCollegiums,
  "P_119": Profession.kiranyaVonKutaki,
  "P_120": Profession.kreisDerEinfuehlung,
  "P_121": Profession.rafimBey,
  "P_122": Profession.sevastanaGevendar,
  "P_123": Profession.kampfseminarZuAndergast,
  "P_124": Profession.akademieDerGeistreisenZuBelhanka,
  "P_125": Profession.halleDesVollendetenKampfesZuBethana,
  "P_126": Profession.halleDesQuecksilbersZuFestum,
  "P_127": Profession.akademieDerErscheinungenZuGrangor,
  "P_128": Profession.stoerrebrandtKollegZuRiva,
  "P_129": Profession.halleDerMachtZuLowangen,
  "P_130": Profession.akademieDerHerrschaftZuElenvina,
  "P_131": Profession.akademieDerMagischenRuestungZuGareth,
  "P_132": Profession.schuleDesMagischenWissensZuMethumis,
  "P_133": Profession.halleDesLebensZuNorburg,
  "P_134": Profession.akademieVonLichtUndDunkelheitZuNostria,
  "P_135": Profession.affenhexer,
  "P_136": Profession.verschwiegeneSchwesternschaft,
  "P_137": Profession.schoeneDerNacht,
  "P_138": Profession.toechterDerErde,
  "P_139": Profession.seherVonHeuteUndMorgen,
  "P_140": Profession.schwesternDesWissens,
  "P_141": Profession.spinnenhexer,
  "P_142": Profession.bewahrer,
  "P_143": Profession.former,
  "P_144": Profession.kaempfer,
  "P_145": Profession.legendensaenger,
  "P_146": Profession.schelm,
  "P_147": Profession.zauberalchimist,
  "P_148": Profession.wildnislaeufer2,
  "P_149": Profession.zauberweber2,
  "P_150": Profession.apothekarius,
  "P_151": Profession.auftragsmoerder,
  "P_152": Profession.bader,
  "P_153": Profession.bote,
  "P_154": Profession.fallensteller,
  "P_155": Profession.fleischer,
  "P_156": Profession.garetherKrieger,
  "P_157": Profession.herrscher,
  "P_158": Profession.holzfaeller2,
  "P_159": Profession.ishannahAlkiraBalayan,
  "P_160": Profession.karawanenfuehrer,
  "P_161": Profession.kontorist,
  "P_162": Profession.landwehrsoldat,
  "P_163": Profession.lanisto,
  "P_164": Profession.logenmitglied,
  "P_165": Profession.mawdli,
  "P_166": Profession.albernischerSeefahrer,
  "P_167": Profession.kuestenschmugglerAusHavena,
  "P_168": Profession.schatzsucherDerSiebenwindkueste,
  "P_169": Profession.efferdgeweihterDerSiebwindkueste,
  "P_170": Profession.numinorupriester,
  "P_171": Profession.metessaGaloraSchwertgeselle,
  "P_172": Profession.neersanderKrieger,
  "P_173": Profession.patrizier,
  "P_174": Profession.prospektor,
  "P_175": Profession.raeuber,
  "P_176": Profession.rommilyserKrieger,
  "P_177": Profession.sappeur,
  "P_178": Profession.sarvinioDellaMonteSchwertgeselle,
  "P_179": Profession.scanlailUiUininSchwertgeselle,
  "P_180": Profession.schankbursche,
  "P_181": Profession.schaukaempfer,
  "P_182": Profession.schauspieler,
  "P_183": Profession.schmuggler,
  "P_184": Profession.schreiber,
  "P_185": Profession.schriftsteller,
  "P_186": Profession.seekrieger,
  "P_187": Profession.stutzer,
  "P_188": Profession.tannhausSchwertgeselle,
  "P_189": Profession.taschendieb,
  "P_190": Profession.taetowierer,
  "P_191": Profession.thorwalerKrieger,
  "P_192": Profession.viehtreiber,
  "P_193": Profession.vinsalterKrieger,
  "P_194": Profession.winhallerKrieger2,
  "P_195": Profession.zimmermann,
  "P_196": Profession.kammerdienerZofe,
  "P_197": Profession.zwergenkriegerNachHardas,
  "P_198": Profession.seenritter,
  "P_199": Profession.ritterDerStreitendenKoenigreiche2,
  "P_200": Profession.mehrerDerMacht,
  "P_201": Profession.druide2,
  "P_202": Profession.distelritter2,
  "P_203": Profession.havenerKrieger2,
  "P_204": Profession.seesoldat2,
  "P_205": Profession.windhagerSippenkrieger2,
  "P_206": Profession.gildenloserMagier2,
  "P_207": Profession.erotikkuenstler,
  "P_210": Profession.prostituierter2,
  "P_211": Profession.sexualmagier,
  "P_212": Profession.tsatuaraAnhaenger,
  "P_213": Profession.levthanpriester,
  "P_214": Profession.rahjageweihter2,
  "P_215": Profession.rahjasutraMeister,
  "P_216": Profession.saebeltaenzer,
  "P_217": Profession.anachNur,
  "P_218": Profession.durroDun,
  "P_219": Profession.hadanHarigasta,
  "P_220": Profession.mudrannura,
  "P_221": Profession.nipakauKocan,
  "P_222": Profession.nuan,
  "P_223": Profession.haindruide,
  "P_224": Profession.hueterDerKraft,
  "P_225": Profession.konzildruide,
  "P_226": Profession.mehrerDerMacht2,
  "P_227": Profession.sumudiener2,
  "P_228": Profession.dienerDerErdmutter,
  "P_229": Profession.herrDerErde,
  "P_230": Profession.bannakademieZuFasar,
  "P_231": Profession.halleDerWindeZuOlport,
  "P_232": Profession.heptagonakademieZuYolGhurmak,
  "P_233": Profession.magierkollegZuHoningen,
  "P_234": Profession.halibAbulKetab,
  "P_235": Profession.qabalothDerNachtwinde,
  "P_236": Profession.dracheneiAkademieZuKhunchom,
  "P_237": Profession.zauberschuleDesKalifenZuMherwed,
  "P_238": Profession.konzilsDerElementeZuDrakonia,
  "P_239": Profession.pentagrammAkademieZuRashdul,
  "P_240": Profession.schuleDerBeherrschungZuNeersand,
  "P_241": Profession.akademieZuWagenhalt,
  "P_242": Profession.rashdulerDaemonologe,
  "P_243": Profession.shanadaVonBenOni,
  "P_244": Profession.dunkleHalleDerGeisterZuBrabak,
  "P_245": Profession.schuleDerVariablenFormZuMirham,
  "P_246": Profession.informationsInstitutsZuRommilys,
  "P_247": Profession.anatomischeAkademieZuVinsalt,
  "P_248": Profession.halleDerMetamorphosenZuKuslik,
  "P_249": Profession.zibilja,
  "P_250": Profession.brobimGeode,
  "P_251": Profession.agrimeton,
  "P_252": Profession.ferdokerLanzer,
  "P_253": Profession.elenvinerKrieger2,
  "P_254": Profession.klippagSchwertgeselle,
  "P_255": Profession.koscherAlmgreve,
  "P_256": Profession.mechanikus2,
  "P_257": Profession.rechtsgelehrter,
  "P_258": Profession.wandergeselle,
  "P_259": Profession.xorloscherDrachenkaempfer,
  "P_260": Profession.gratenfelserHaindruide,
  "P_261": Profession.weissmagier2,
};

enum SocialStatus {
  unfrei(1, "Unfrei"),
  frei(2, "Frei"),
  niederadel(3, "Niederadel"),
  adel(4, "Adel"),
  hochadel(5, "Hochadel");

  final int id;
  final String name;
  const SocialStatus(this.id, this.name);

  @override
  String toString() {
    return name;
  }
}

const Map<int, SocialStatus> socialStatusById = {
  1: SocialStatus.unfrei,
  2: SocialStatus.frei,
  3: SocialStatus.niederadel,
  4: SocialStatus.adel,
  5: SocialStatus.hochadel,
};

enum ExperienceLevel {
  unerfahren("EL_1", "Unerfahren"),
  durchschnittlich("EL_2", "Durchschnittlich"),
  erfahren("EL_3", "Erfahren"),
  kompetent("EL_4", "Kompetent"),
  meisterlich("EL_5", "Meisterlich"),
  brillant("EL_6", "Brillant"),
  legendaer("EL_7", "Legendär");

  final String id;
  final String name;
  const ExperienceLevel(this.id, this.name);

  @override
  String toString() {
    return name;
  }
}

const Map<String, ExperienceLevel> levelById = {
  "EL_1": ExperienceLevel.unerfahren,
  "EL_2": ExperienceLevel.durchschnittlich,
  "EL_3": ExperienceLevel.erfahren,
  "EL_4": ExperienceLevel.kompetent,
  "EL_5": ExperienceLevel.meisterlich,
  "EL_6": ExperienceLevel.brillant,
  "EL_7": ExperienceLevel.legendaer,
};
