import 'skill_groups.dart';
import 'attributes.dart';
import 'rules.dart';

enum Skill {
  // <db-replace-token-skill>
  fliegen(
    "TAL_1",
    "Fliegen",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.gewandtheit,
  ),
  gaukeleien(
    "TAL_2",
    "Gaukeleien",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.charisma,
    Attribute.fingerfertigkeit,
  ),
  klettern(
    "TAL_3",
    "Klettern",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  koerperbeherrschung(
    "TAL_4",
    "Körperbeherrschung",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.gewandtheit,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  kraftakt(
    "TAL_5",
    "Kraftakt",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.konstitution,
    Attribute.koerperkraft,
    Attribute.koerperkraft,
  ),
  reiten(
    "TAL_6",
    "Reiten",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.charisma,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  schwimmen(
    "TAL_7",
    "Schwimmen",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.gewandtheit,
    Attribute.konstitution,
    Attribute.koerperkraft,
  ),
  selbstbeherrschung(
    "TAL_8",
    "Selbstbeherrschung",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.mut,
    Attribute.konstitution,
  ),
  singen(
    "TAL_9",
    "Singen",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.charisma,
    Attribute.konstitution,
  ),
  sinnesschaerfe(
    "TAL_10",
    "Sinnesschärfe",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.intuition,
  ),
  tanzen(
    "TAL_11",
    "Tanzen",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.charisma,
    Attribute.gewandtheit,
  ),
  taschendiebstahl(
    "TAL_12",
    "Taschendiebstahl",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
  ),
  verbergen(
    "TAL_13",
    "Verbergen",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.gewandtheit,
  ),
  zechen(
    "TAL_14",
    "Zechen",
    "",
    "",
    "",
    "",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.konstitution,
    Attribute.koerperkraft,
  ),
  bekehrenUndUeberzeugen(
    "TAL_15",
    "Bekehren & Überzeugen",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.charisma,
  ),
  betoeren(
    "TAL_16",
    "Betören",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.charisma,
    Attribute.charisma,
  ),
  einschuechtern(
    "TAL_17",
    "Einschüchtern",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.charisma,
  ),
  etikette(
    "TAL_18",
    "Etikette",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  gassenwissen(
    "TAL_19",
    "Gassenwissen",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  menschenkenntnis(
    "TAL_20",
    "Menschenkenntnis",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  ueberreden(
    "TAL_21",
    "Überreden",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.charisma,
  ),
  verkleiden(
    "TAL_22",
    "Verkleiden",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.intuition,
    Attribute.charisma,
    Attribute.gewandtheit,
  ),
  willenskraft(
    "TAL_23",
    "Willenskraft",
    "",
    "",
    "",
    "",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.charisma,
  ),
  faehrtensuchen(
    "TAL_24",
    "Fährtensuchen",
    "",
    "",
    "",
    "",
    SkillGroup.naturtalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.gewandtheit,
  ),
  fesseln(
    "TAL_25",
    "Fesseln",
    "",
    "",
    "",
    "",
    SkillGroup.naturtalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.koerperkraft,
  ),
  fischenUndAngeln(
    "TAL_26",
    "Fischen & Angeln",
    "",
    "",
    "",
    "",
    SkillGroup.naturtalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  orientierung(
    "TAL_27",
    "Orientierung",
    "",
    "",
    "",
    "",
    SkillGroup.naturtalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.intuition,
  ),
  pflanzenkunde(
    "TAL_28",
    "Pflanzenkunde",
    "",
    "",
    "",
    "",
    SkillGroup.naturtalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
  ),
  tierkunde(
    "TAL_29",
    "Tierkunde",
    "",
    "",
    "",
    "",
    SkillGroup.naturtalente,
    Attribute.mut,
    Attribute.mut,
    Attribute.charisma,
  ),
  wildnisleben(
    "TAL_30",
    "Wildnisleben",
    "",
    "",
    "",
    "",
    SkillGroup.naturtalente,
    Attribute.mut,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  brettUndGluecksspiel(
    "TAL_31",
    "Brett- & Glücksspiel",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  geographie(
    "TAL_32",
    "Geographie",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  geschichtswissen(
    "TAL_33",
    "Geschichtswissen",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  goetterUndKulte(
    "TAL_34",
    "Götter & Kulte",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  kriegskunst(
    "TAL_35",
    "Kriegskunst",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  magiekunde(
    "TAL_36",
    "Magiekunde",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  mechanik(
    "TAL_37",
    "Mechanik",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
  ),
  rechnen(
    "TAL_38",
    "Rechnen",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  rechtskunde(
    "TAL_39",
    "Rechtskunde",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  sagenUndLegenden(
    "TAL_40",
    "Sagen & Legenden",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  sphaerenkunde(
    "TAL_41",
    "Sphärenkunde",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  sternkunde(
    "TAL_42",
    "Sternkunde",
    "",
    "",
    "",
    "",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  alchimie(
    "TAL_43",
    "Alchimie",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
  ),
  booteUndSchiffe(
    "TAL_44",
    "Boote & Schiffe",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  fahrzeuge(
    "TAL_45",
    "Fahrzeuge",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.charisma,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
  ),
  handel(
    "TAL_46",
    "Handel",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  heilkundeGift(
    "TAL_47",
    "Heilkunde Gift",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  heilkundeKrankheiten(
    "TAL_48",
    "Heilkunde Krankheiten",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.konstitution,
  ),
  heilkundeSeele(
    "TAL_49",
    "Heilkunde Seele",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.charisma,
    Attribute.konstitution,
  ),
  heilkundeWunden(
    "TAL_50",
    "Heilkunde Wunden",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  holzbearbeitung(
    "TAL_51",
    "Holzbearbeitung",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  lebensmittelbearbeitung(
    "TAL_52",
    "Lebensmittelbearbeitung",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  lederbearbeitung(
    "TAL_53",
    "Lederbearbeitung",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  malenUndZeichnen(
    "TAL_54",
    "Malen & Zeichnen",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  metallbearbeitung(
    "TAL_55",
    "Metallbearbeitung",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
    Attribute.koerperkraft,
  ),
  musizieren(
    "TAL_56",
    "Musizieren",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.charisma,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
  ),
  schloesserknacken(
    "TAL_57",
    "Schlösserknacken",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  steinbearbeitung(
    "TAL_58",
    "Steinbearbeitung",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
    Attribute.koerperkraft,
  ),
  stoffbearbeitung(
    "TAL_59",
    "Stoffbearbeitung",
    "",
    "",
    "",
    "",
    SkillGroup.handwerkstalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  );
  // </db-replace-token-skill>

  final String id;
  final String name;
  final String quality;
  final String failed;
  final String critical;
  final String botch;
  final SkillGroup skillGroup;
  final Attribute attr1;
  final Attribute attr2;
  final Attribute attr3;

  const Skill(
    this.id,
    this.name,
    this.quality,
    this.failed,
    this.critical,
    this.botch,
    this.skillGroup,
    this.attr1,
    this.attr2,
    this.attr3,
  );

  @override
  String toString() {
    return name;
  }
}

const Map<String, Skill> skillKeys = {
  "TAL_1": Skill.fliegen,
  "TAL_2": Skill.gaukeleien,
  "TAL_3": Skill.klettern,
  "TAL_4": Skill.koerperbeherrschung,
  "TAL_5": Skill.kraftakt,
  "TAL_6": Skill.reiten,
  "TAL_7": Skill.schwimmen,
  "TAL_8": Skill.selbstbeherrschung,
  "TAL_9": Skill.singen,
  "TAL_10": Skill.sinnesschaerfe,
  "TAL_11": Skill.tanzen,
  "TAL_12": Skill.taschendiebstahl,
  "TAL_13": Skill.verbergen,
  "TAL_14": Skill.zechen,
  "TAL_15": Skill.bekehrenUndUeberzeugen,
  "TAL_16": Skill.betoeren,
  "TAL_17": Skill.einschuechtern,
  "TAL_18": Skill.etikette,
  "TAL_19": Skill.gassenwissen,
  "TAL_20": Skill.menschenkenntnis,
  "TAL_21": Skill.ueberreden,
  "TAL_22": Skill.verkleiden,
  "TAL_23": Skill.willenskraft,
  "TAL_24": Skill.faehrtensuchen,
  "TAL_25": Skill.fesseln,
  "TAL_26": Skill.fischenUndAngeln,
  "TAL_27": Skill.orientierung,
  "TAL_28": Skill.pflanzenkunde,
  "TAL_29": Skill.tierkunde,
  "TAL_30": Skill.wildnisleben,
  "TAL_31": Skill.brettUndGluecksspiel,
  "TAL_32": Skill.geographie,
  "TAL_33": Skill.geschichtswissen,
  "TAL_34": Skill.goetterUndKulte,
  "TAL_35": Skill.kriegskunst,
  "TAL_36": Skill.magiekunde,
  "TAL_37": Skill.mechanik,
  "TAL_38": Skill.rechnen,
  "TAL_39": Skill.rechtskunde,
  "TAL_40": Skill.sagenUndLegenden,
  "TAL_41": Skill.sphaerenkunde,
  "TAL_42": Skill.sternkunde,
  "TAL_43": Skill.alchimie,
  "TAL_44": Skill.booteUndSchiffe,
  "TAL_45": Skill.fahrzeuge,
  "TAL_46": Skill.handel,
  "TAL_47": Skill.heilkundeGift,
  "TAL_48": Skill.heilkundeKrankheiten,
  "TAL_49": Skill.heilkundeSeele,
  "TAL_50": Skill.heilkundeWunden,
  "TAL_51": Skill.holzbearbeitung,
  "TAL_52": Skill.lebensmittelbearbeitung,
  "TAL_53": Skill.lederbearbeitung,
  "TAL_54": Skill.malenUndZeichnen,
  "TAL_55": Skill.metallbearbeitung,
  "TAL_56": Skill.musizieren,
  "TAL_57": Skill.schloesserknacken,
  "TAL_58": Skill.steinbearbeitung,
  "TAL_59": Skill.stoffbearbeitung,
};

class SkillWrapper implements Trial {
  final Skill skill;

  SkillWrapper(this.skill);

  @override
  Attribute get attr1 => skill.attr1;
  @override
  Attribute get attr2 => skill.attr2;
  @override
  Attribute get attr3 => skill.attr3;
  @override
  String get name => skill.name;
}
