import 'skill_groups.dart';
import 'attributes.dart';

enum Skill {
  fliegen(
    "TAL_1",
    "Fliegen",
    "Distanzen können schneller überwunden werden.",
    "Das Flugmanöver ist misslungen und muss abgebrochen werden.",
    "Dem Held ist nicht nur das Manöver gelungen, sondern er hat eine zusätzliche Aktion in dieser Runde.",
    "Der Held stürzt ab.",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.gewandtheit,
  ),
  gaukeleien(
    "TAL_2",
    "Gaukeleien",
    "Der Trick ist besonders gut gelungen und die Zuschauer applaudieren mehr.",
    "Der Trick funktioniert nicht richtig, kleine Fehler schleichen sich bei dem Versuch ein. Das Publikum ist enttäuscht.",
    "Die Zuschauer sind fasziniert, halten den Trick gar für echte Magie, und potenzielle Geldeinnahmen des Gauklers verdoppeln sich.",
    "Der Held wird bei der Präsentation ausgebuht, da ihm ein Missgeschick passiert (mit Jonglierkeule einen Zuschauer getroffen, mit Pyrotechnik den Bürgermeister verletzt etc.).",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.charisma,
    Attribute.fingerfertigkeit,
  ),
  klettern(
    "TAL_3",
    "Klettern",
    "Der Held kommt schneller an seinem Ziel an.",
    "Der Held braucht viel länger als üblich, verletzt sich leicht (1W3 SP), traut sich nicht, zu klettern, oder hängt fest.",
    "Ohne Schwierigkeiten und viel schneller als gewöhnlich hat der Held den Aufstieg geschafft. Zuschauer halten ihn für den besten Kletterer Deres. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Held rutscht ab und fällt (siehe Seite 340, Sturzschaden).",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  koerperbeherrschung(
    "TAL_4",
    "Körperbeherrschung",
    "Der Abenteurer kann sich schneller aus einer Fesselung befreien.",
    "Die Handlung des Helden geht teilweise schief, er braucht länger und macht Fehler oder muss die Handlung abbrechen.",
    "Dem Held gelingt seine Handlung und er hat noch eine zusätzliche Aktion zur Verfügung. Und was immer der Held getan hat: Es sah elegant aus.",
    "Der Held stürzt und erleidet Schaden (1W6 SP).",
    SkillGroup.koerpertalente,
    Attribute.gewandtheit,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  kraftakt(
    "TAL_5",
    "Kraftakt",
    "Für einen kurzen Zeitraum kann der Held mehr Gewicht stemmen oder eine schwere Last länger halten.",
    "Die Handlung des Helden misslingt.",
    "Der Held beeindruckt durch seine Muskelkraft alle Zuschauer und gilt fortan als einer der stärksten Aventurier. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Die Handlung des Helden misslingt völlig. Er stürzt, verhebt sich o.Ä. und verletzt sich dabei (1W6 SP).",
    SkillGroup.koerpertalente,
    Attribute.konstitution,
    Attribute.koerperkraft,
    Attribute.koerperkraft,
  ),
  reiten(
    "TAL_6",
    "Reiten",
    "Der Held ist schneller an seinem Ziel.",
    "Das Tier bewegt sich nicht oder nicht so, wie es soll.",
    "Das Tier macht seine Sache ausgezeichnet und wie gewünscht, der Reiter hat eine weitere Aktion zur Verfügung.",
    "Das Tier wirft den Reiter ab und er stürzt zu Boden (siehe Seite **340**, Sturzschaden).",
    SkillGroup.koerpertalente,
    Attribute.charisma,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  schwimmen(
    "TAL_7",
    "Schwimmen",
    "Der Held ist schneller an seinem Ziel.",
    "Der Held traut sich nicht zu schwimmen oder kommt nicht sonderlich weit – auf jeden Fall nicht bis dahin, wohin er wollte.",
    "Der Held schwimmt die Strecke in Bestzeit. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Held geht unter (siehe Seite 340ff., Erstickungsschaden). Grund dafür könnte ein Wadenkrampf sein.",
    SkillGroup.koerpertalente,
    Attribute.gewandtheit,
    Attribute.konstitution,
    Attribute.koerperkraft,
  ),
  selbstbeherrschung(
    "TAL_8",
    "Selbstbeherrschung",
    "Die Selbstbeherrschung hält für einen längeren Zeitraum.",
    "Dem Helden gelingt es nicht, den Schmerz zu unterdrücken oder die Ablenkung zu ignorieren.",
    "Es gelingt dem Helden, Schmerzen (bis Stufe III) und Ablenkungen einen ganzen Tag lang zu ignorieren.",
    "Der Held erhält für die nächste Stunde 2 Stufen des Zustands *Schmerz* oder ist durch die Ablenkung *Überrascht*.",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.mut,
    Attribute.konstitution,
  ),
  singen(
    "TAL_9",
    "Singen",
    "Der Gesang ist so gut, dass der Held mehr Applaus durch die Zuhörer erhält.",
    "Der Held vergisst den Text oder sein Auftritt gerät eher schlecht als recht.",
    "Der Gesang des Helden ist noch in vielen Wochen Thema seiner Zuhörer. Hat der Held sich um Geld bemüht, dann nimmt er mindestens das Doppelte ein als üblich. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Held liegt mehrere Halbtöne daneben oder vergeigt den Rhythmus. Das Lied ist eine Qual für jeden Zuhörer, der Held wird ausgebuht.",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.charisma,
    Attribute.konstitution,
  ),
  sinnesschaerfe(
    "TAL_10",
    "Sinnesschärfe",
    "Der Held bemerkt weitere Details.",
    "Der Held bemerkt nichts.",
    "Der Held nimmt sogar kaum bemerkbare Details wahr. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Held nimmt etwas anderes wahr, als das, was wirklich wichtig wäre. Er könnte zum Beispiel die in der Nähe befindlichen Blumen riechen, dafür aber nicht den auffällig stinkenden Oger, der an ihn heranschleicht.",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.intuition,
  ),
  tanzen(
    "TAL_11",
    "Tanzen",
    "Der Tanz ist so gut, dass der Held mehr Applaus erhält.",
    "Der Held bringt die Tanzschritte durcheinander.",
    "Die Aufmerksamkeit der Zuschauer fällt wegen des perfekten Tanzes auf den Helden. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Held tritt seiner Tanzpartnerin auf die Füße und verletzt sie dabei oder er stürzt und blamiert sich.",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.charisma,
    Attribute.gewandtheit,
  ),
  taschendiebstahl(
    "TAL_12",
    "Taschendiebstahl",
    "Der Taschendiebstahl wird später bemerkt.",
    "Der Versuch misslingt oder das Opfer bemerkt den Diebstahl.",
    "Das Opfer hat den Diebstahlversuch nicht bemerkt und der Held hat besonders wertvolle Beute gemacht oder gleich mehrere Ziele bestohlen. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Held wird von umstehenden Personen oder dem Opfer beobachtet, ohne es zu bemerken, und der Diebstahlversuch misslingt. Außerdem ist er *Überrascht*.",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
  ),
  verbergen(
    "TAL_13",
    "Verbergen",
    "Der Held kann schwieriger entdeckt werden oder findet schneller ein Versteck.",
    "Der Held hat sich nur dürftig versteckt oder Geräusche beim Schleichen verursacht.",
    "Der Held hat ein perfektes Versteck gefunden oder ist lautlos wie eine Katze. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Irgendetwas (Teller, ein Möbelstück) ist umgefallen.",
    SkillGroup.koerpertalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.gewandtheit,
  ),
  zechen(
    "TAL_14",
    "Zechen",
    "Der Held verträgt viel mehr als üblich.",
    "Der Held erhält eine Stufe des Zustands *Betäubung* und erwacht am nächsten Tag mit Kopfschmerzen oder anderen unliebsamen Auswirkungen seines Gelages.",
    "Dem Helden gelingt es, bis zum bitteren Ende durchzuhalten, und trotzdem geht es ihm am nächsten Morgen blendend.",
    "Der Held begeht in seinem Zustand jedwede Peinlichkeit. Er zerlegt die halbe Taverne, wacht morgens nackt auf dem Markt oder in einem fremden Bett auf, plaudert Geheimnisse an den Feind aus und kann sich danach an nichts mehr erinnern.",
    SkillGroup.koerpertalente,
    Attribute.klugheit,
    Attribute.konstitution,
    Attribute.koerperkraft,
  ),
  bekehrenUndUeberzeugen(
    "TAL_15",
    "Bekehren & Überzeugen",
    "Mehr Menschen lassen sich von dem Helden bekehren, oder der Bekehrte folgt seiner neuen Überzeugung länger.",
    "Das Opfer glaubt dem Prediger nicht.",
    "Das Opfer der Überzeugungsversuche ist vollends überzeugt.",
    "Das Opfer fühlt sich vom Prediger beleidigt oder für dumm verkauft.",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.charisma,
  ),
  betoeren(
    "TAL_16",
    "Betören",
    "Der Bezirzte ist bereit, mehr für den Helden zu tun.",
    "Dem Helden gelingt es vorerst nicht, Interesse beim Opfer zu wecken.",
    "Das Verführungsopfer versucht, dem betörenden Helden alle Wünsche zu erfüllen.",
    "Der Held kassiert eine schallende Ohrfeige für seinen plumpen Anmachversuch.",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.charisma,
    Attribute.charisma,
  ),
  einschuechtern(
    "TAL_17",
    "Einschüchtern",
    "Das Opfer ist länger eingeschüchtert oder verrät dem Helden mehr als erwartet.",
    "Das Gegenüber ignoriert alle Schmähungen und Einschüchterungsversuche des Helden.",
    "Das Gegenüber des Helden ist vollkommen eingeschüchtert und wird in absehbarer Zeit nichts mehr gegen den Helden unternehmen.",
    "Anstatt eingeschüchtert oder beleidigt zu sein, geschieht das Gegenteil: Das Opfer ist wütend, völlig gelassen oder amüsiert. Oder der Held macht sich mit seinem Gehabe völlig zum Affen.",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.charisma,
  ),
  etikette(
    "TAL_18",
    "Etikette",
    "Der Held hinterlässt einen guten Eindruck und bleibt positiv in Erinnerung.",
    "Der Held kann sich nicht an alle wichtigen Benimmregeln erinnern und fällt unangenehm auf.",
    "Auf der Feier ist der Held aufgrund seines Benehmens, Wortwitzes und Charmes der Mittelpunkt.",
    "Der Held beleidigt mit seinem Verhalten eine wichtige Persönlichkeit.",
    SkillGroup.gesellschaftstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  gassenwissen(
    "TAL_19",
    "Gassenwissen",
    "Der Held erhält mehr Informationen oder erlangt sie schneller als erwartet.",
    "Der Held erhält keine hilfreichen Informationen.",
    "Der Held entdeckt ein besonders gutes, aber günstiges Gasthaus, erhält mehr Informationen, als er erwartet hat, oder es gelingt ihm, einen Kontaktmann zu finden, der ihm exzellente Konditionen anbietet.",
    "Der Held gerät in den Hinterhalt einer Bande Schurken, die ihn ausplündern wollen.",
    SkillGroup.gesellschaftstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  menschenkenntnis(
    "TAL_20",
    "Menschenkenntnis",
    "Der Held hat einen stärkeren Verdacht, was sein Gegenüber vorhat oder warum es lügt.",
    "Der Held ist sich nicht sicher.",
    "Der Held durchschaut die Person komplett.",
    "Der Held ist einer kompletten Fehleinschätzung aufgesessen. So könnte er beispielsweise einem Lügner wirklich alles glauben, ehrlichen Leuten hingegen kein Wort.",
    SkillGroup.gesellschaftstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  ueberreden(
    "TAL_21",
    "Überreden",
    "Das Gegenüber ist bereit, mehr für den Helden zu tun.",
    "Dem Held gelingt es nicht, sein Gegenüber zu überreden.",
    "Die Person, die der Held überreden wollte, tut weit mehr als sie muss.",
    "Die Person, die der Held überreden wollte, ist wütend auf den Helden und lässt sich in nächster Zeit nicht mehr überreden.",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.charisma,
  ),
  verkleiden(
    "TAL_22",
    "Verkleiden",
    "Die Verkleidung ist schwerer zu durchschauen.",
    "Die Verkleidung ist nicht gut gewählt und hält einem prüfenden Blick nicht stand.",
    "Die Verkleidung funktioniert tadellos.",
    "Die Kleidung wird sofort durchschaut und der Held handelt sich in der Regel Ärger ein.",
    SkillGroup.gesellschaftstalente,
    Attribute.intuition,
    Attribute.charisma,
    Attribute.gewandtheit,
  ),
  willenskraft(
    "TAL_23",
    "Willenskraft",
    "Die Auswirkungen von Verführungs- oder Überredensversuchen sind deutlich abgeschwächt oder es wird ihnen ganz widerstanden.",
    "Der Held kann nicht widerstehen.",
    "Der Held widersteht und kann von dieser Person oder Sache in nächster Zeit nicht mehr beeinflusst werden.",
    "Der Held ist der Person, die ihn beeinflussen will, vollkommen verfallen oder fällt bei Anblick eines scheußlichen Dämons in Ohnmacht.",
    SkillGroup.gesellschaftstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.charisma,
  ),
  faehrtensuchen(
    "TAL_24",
    "Fährtensuchen",
    "über die Qualitätsstufe kann der Held mehr Details in der Fährte erkennen.",
    "Der Held findet keine Spur oder kann keine neuen Erkenntnisse gewinnen.",
    "Sofern die Spur nicht komplett zerstört wurde, kann der Held ihr zielsicher bis zum Ende folgen. Er erhält mehr Informationen als üblich. Täuschungsmanöver wie das Verwischen der Spuren durchschaut er sofort.",
    "Der Held verwechselt die Spur und folgt einer falschen Fährte. So trifft er vielleicht auf eine gefährliche Kreatur oder jagt den falschen Leuten hinterher.",
    SkillGroup.naturtalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.gewandtheit,
  ),
  fesseln(
    "TAL_25",
    "Fesseln",
    "Die Fessel hält länger und kann gegebenenfalls schwerer geöffnet werden.",
    "Dem Held gelingt nur ein Knoten von schlechter Qualität. Das Befreien daraus ist leichter als üblich.",
    "Der Held hat einen stabilen Knoten gemacht. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Held hat einen Knoten gemacht, der sich in jeder Lage löst - oder der denkbar ungünstigsten.",
    SkillGroup.naturtalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.koerperkraft,
  ),
  fischenUndAngeln(
    "TAL_26",
    "Fischen & Angeln",
    "Die Fische sind wohlschmeckender als bei einem durchschnittlichen Fang.",
    "Kein Fisch beißt an oder geht ins Netz.",
    "Die Zahl der Rationen ist sehr hoch. Für Qualitätsstufen, Vergleichs- und Sammelproben gilt: FP = doppelter FW.",
    "Der Angler fällt ins Wasser und die Angel geht verloren.",
    SkillGroup.naturtalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  orientierung(
    "TAL_27",
    "Orientierung",
    "Der Held findet schneller heraus, in welche Richtung er sich bewegt.",
    "Der Held weiß nicht sicher, wo es langgeht.",
    "Der Held findet den Weg ohne Schwierigkeiten selbst unter schlechtesten Bedingungen.",
    "Der Held hat sich komplett verlaufen und bewegt sich in die falsche Richtung, was ihm jedoch nicht bewusst ist.",
    SkillGroup.naturtalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.intuition,
  ),
  pflanzenkunde(
    "TAL_28",
    "Pflanzenkunde",
    "genauere Informationen zu einer Pflanze",
    "Der Held hat keine Ahnung.",
    "Der Held weiß alles über die Pflanze, auch besondere Wirkungen, und kann sie doppelt so lange haltbar machen wie üblich.",
    "Der Held verwechselt die Pflanze mit einer anderen.",
    SkillGroup.naturtalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
  ),
  tierkunde(
    "TAL_29",
    "Tierkunde",
    "genauere Informationen zu einem Tier",
    "Der Held hat keine Ahnung.",
    "Der Held weiß alles über das Tier.",
    "Der Held glaubt, etwas über das Tier zu wissen, liegt aber gefährlich falsch (schätzt es ungiftig ein, obwohl es sehr giftig ist, oder als Pflanzenfresser, obwohl es Fleischfresser ist).",
    SkillGroup.naturtalente,
    Attribute.mut,
    Attribute.mut,
    Attribute.charisma,
  ),
  wildnisleben(
    "TAL_30",
    "Wildnisleben",
    "Der Held benötigt nicht so lange, um ein Lager zu finden oder aufzubauen.",
    "Der Lagerplatz ist schlecht gewählt. Die Regeneration ist um 1 gesenkt.",
    "Ein phantastischer Schlafplatz! Die Regeneration ist um 1 Punkt erhöht.",
    "Das Lager wird überschwemmt oder von Ungeziefer heimgesucht.",
    SkillGroup.naturtalente,
    Attribute.mut,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  brettUndGluecksspiel(
    "TAL_31",
    "Brett- & Glücksspiel",
    "Der Held hat einen guten Spielzug gemacht.",
    "Der Held verliert.",
    "Der Held gewinnt auf spektakuläre Art und Weise. Wurde um Geld gespielt, verdoppelt sich sein Gewinn.",
    "Der Held wird fälschlicherweise des Falschspiels verdächtigt oder hat eine Pechsträne. Wird um Geld gespielt, verliert er mindestens den kompletten Einsatz (oder mehr).",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  geographie(
    "TAL_32",
    "Geographie",
    "mehr Detailinformationen zur Bevölkerung, Örtlichkeiten und Flussübergängen",
    "Der Held hat keine Ahnung.",
    "Der Held kennt viele Details der Region: Herrscher, Bevölkerungszahlen, Bräuche, Flussverläufe und Brücken.",
    "Der Held erinnert sich an völlig falsche geographische Details: Einwohnerzahlen von Städten stimmen nicht, Brücken befinden sich an anderer Stelle als gedacht.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  geschichtswissen(
    "TAL_33",
    "Geschichtswissen",
    "mehr Details zu historischen Persönlichkeiten und Epochen",
    "Der Held hat keine Ahnung.",
    "Der Held kennt besonders viele Details über ein bestimmtes Ereignis oder eine historische Person.",
    "Der Held kann zu diesem Thema nur falsche Informationen beitragen: er irrt sich in Daten und Ereignissen.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  goetterUndKulte(
    "TAL_34",
    "Götter & Kulte",
    "mehr Details zu Kulten, Göttern und Priestern",
    "Der Held hat keine Ahnung.",
    "Der Held hat detaillierte Einsichten in das Thema und kennt selbst spezielle Rituale, Gebetstexte oder philosophische Grundlagen.",
    "Der Held verwechselt kultische Handlungen und Ansichten dieser Kirche mit einer anderen.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  kriegskunst(
    "TAL_35",
    "Kriegskunst",
    "bessere Vorteile während des Gefechts",
    "Der Held unterliegt einer Fehleinschätzung.",
    "Der Held hat einen vortrefflichen Plan, der ihm zusätzliche Vorteile im Kampf einbringt.",
    "Der Held begeht einen kapitalen Planungsfehler, der den Kampf zu seinen Ungunsten beeinflusst oder ihm zumindest extreme Nachteile beschert.",
    SkillGroup.wissenstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  magiekunde(
    "TAL_36",
    "Magiekunde",
    "mehr Details zu Zaubern, magischen Wesen oder exotischer Magieanwendung",
    "Der Held hat keine Ahnung.",
    "Der Held kennt Herkunft, wirkenden Zauber und Auslöser eines alten Artefaktes.",
    "Der Held hat falsche Vorstellungen und irrt sich, sodass es zu einem gravierenden Fehlurteil kommt.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  mechanik(
    "TAL_37",
    "Mechanik",
    "schnellere Planung",
    "Die geplante Mechanik funktioniert nicht.",
    "Der doppelte FW zählt als FP.",
    "Was immer der Held konstruieren wollte: Das Objekt ist gefährlich oder die Konstruktion fällt in sich zusammen. Eine Falle wird mit größtmöglichem Erfolg ausgelöst.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
  ),
  rechnen(
    "TAL_38",
    "Rechnen",
    "schnelleres Ergebnis",
    "Das Ergebnis ist falsch.",
    "Schnelle und exakte Bestimmung der Lösung",
    "Das Ergebnis ist komplett falsch, der Held aber von der Richtigkeit absolut überzeugt.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  rechtskunde(
    "TAL_39",
    "Rechtskunde",
    "mehr Optionen zur Lösung eines Falls",
    "Der Held hat keine Ahnung.",
    "Der Held kennt sich mit Besonderheiten des Gesetzes aus und kann einen Plan entwickeln, es zu seinem Vorteil auszulegen.",
    "Die Auslegung des Gesetzes ist falsch oder der Held übersieht einen wichtigen Passus.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  sagenUndLegenden(
    "TAL_40",
    "Sagen & Legenden",
    "mehr Details oder verschiedene Versionen einer Geschichte",
    "Der Held kennt die Legende nicht.",
    "Der Held kann sich an viele Details der Geschichte erinnern und kennt mehrere Varianten.",
    "Der Held verwechselt die Geschichte mit einer anderen oder meint sich an völlig andere Details zu erinnern.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  sphaerenkunde(
    "TAL_41",
    "Sphärenkunde",
    "mehr Details zu Sphären oder dem Limbus",
    "Der Held weiß nichts über das spezielle Thema.",
    "Der Held erinnert sich an bemerkenswerte Details über einen einzelnen Dämon oder den Weg in eine verborgene Globule.",
    "Der Held unterliegt einer gefährlichen Fehleinschätzung.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  sternkunde(
    "TAL_42",
    "Sternkunde",
    "schnellere Horoskoperstellung",
    "Der Held hat keine Ahnung.",
    "Der Held kann sehr genau die Bewegungen der Himmelskörper berechnen.",
    "Eine Fehleinschätzung bei einem Horoskop, einer Mondfinsternis etc.",
    SkillGroup.wissenstalente,
    Attribute.klugheit,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  alchimie(
    "TAL_43",
    "Alchimie",
    "Der Trank weist eine bessere Qualität auf.",
    "Das Elixier ist misslungen oder eine Analyse hat kein Ergebnis gebracht.",
    "Der Held weiß exakt, welches Elixier er vor sich hat, welche Stufe es besitzt und wie lange haltbar es ist.",
    "Das Elixier sorgt für einen unangenehmen Nebeneffekt.",
    SkillGroup.handwerkstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
  ),
  booteUndSchiffe(
    "TAL_44",
    "Boote & Schiffe",
    "Die Distanz bis zum Ziel kann schneller überwunden werden.",
    "Der Held kommt mit dem Boot oder Schiff kaum voran.",
    "Der Held nutzt günstige Strömungen und Winde, um doppelt so schnell voranzukommen wie üblich.",
    "Der Held fällt von Bord oder ein wichtiger Teil des Wasserfahrzeugs wurde beschädigt.",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  fahrzeuge(
    "TAL_45",
    "Fahrzeuge",
    "Die Distanz bis zum Ziel kann schneller überwunden werden.",
    "Das Fahrzeug bewegt sich schwerfällig oder dem Helden gelingt es nicht, es in Bewegung zu setzen.",
    "Das Fahrzeug kommt gut voran und schafft die Strecke in Rekordzeit.",
    "Das Fahrzeug erleidet einen Achsenbruch oder fällt während der Fahrt mitsamt dem Fahrer um, und der Held erleidet Fallschaden.",
    SkillGroup.handwerkstalente,
    Attribute.charisma,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
  ),
  handel(
    "TAL_46",
    "Handel",
    "Der Held kann präziser den Preis bestimmen.",
    "Der Held bekommt nicht so viel wie erhofft.",
    "Der Held bekommt die Ware zu einem Spottpreis bzw. kann sie zu Wucherpreisen loswerden - ohne dass sein Handelspartner es ihm übel nimmt. Die Preiserhöhung oder der Nachlass sollte mindestens 50 % betragen.",
    "Der Held wird über den Tisch gezogen oder der Handelspartner weigert sich, Geschäfte mit dem Helden zu machen. Die Preiserhöhung oder der Nachlass sollte mindestens 50 % betragen.",
    SkillGroup.handwerkstalente,
    Attribute.klugheit,
    Attribute.intuition,
    Attribute.charisma,
  ),
  heilkundeGift(
    "TAL_47",
    "Heilkunde Gift",
    "Der Held kann das Gift schneller bestimmen.",
    "Der Held hat keine Ahnung und kennt keine Möglichkeit der Heilung.",
    "Der Patient kann vollständig entgiftet werden, ohne dass der Held das passende Gegenmittel verwenden musste.",
    "Der Held ordnet einen (schädlichen) Aderlass an oder hat den Patienten bei der Behandlung verletzt oder gar zusätzlich vergiftet (1W6 SP).",
    SkillGroup.handwerkstalente,
    Attribute.mut,
    Attribute.klugheit,
    Attribute.intuition,
  ),
  heilkundeKrankheiten(
    "TAL_48",
    "Heilkunde Krankheiten",
    "Der Held kann die Krankheit schneller bestimmen.",
    "Der Held hat keine Ahnung und kennt weder Heilmittel noch die passende Behandlung.",
    "Der Patient ist geheilt, ohne dass der Held ein Heilmittel verwenden musste. Zudem steckt er sich nicht beim Erkrankten an.",
    "Der Held hat dem Patienten bei der Behandlung geschadet (1W6 SP) oder der Krankheitsverlauf verschlimmert sich. Zudem besteht für den Helden bei ansteckenden Krankheiten eine 25 % höhere Chance, sich bei dem Patienten anzustecken.",
    SkillGroup.handwerkstalente,
    Attribute.mut,
    Attribute.intuition,
    Attribute.konstitution,
  ),
  heilkundeSeele(
    "TAL_49",
    "Heilkunde Seele",
    "Die Unterdrückung des Nachteils hält länger an.",
    "Der Held hat keine Ahnung, wie er dem Patienten helfen kann.",
    "Der Patient kann einen Nachteil (Angst, Persönlichkeitsschwäche oder Schlechte Eigenschaft) für einen ganzen Tag unterdrücken.",
    "Der Held hat den Patienten bei der Behandlung verstört oder seinem Geist anderweitig geschadet. Der Patient erhält für einen Tag eine Stufe des Zustands *Furcht* oder *Verwirrung*.",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.charisma,
    Attribute.konstitution,
  ),
  heilkundeWunden(
    "TAL_50",
    "Heilkunde Wunden",
    "Der Held verbraucht weniger Heilkräuter oder kann die Verletzung schneller versorgen.",
    "Der Held kann dem Patienten nicht helfen.",
    "Die vollen Fertigkeitspunkte werden bei der nächsten Regenerationsphase zusätzlich zur normalen Regeneration zu den Lebenspunkten des Patienten hinzuaddiert.",
    "Der Held hat den Patienten bei der Behandlung verletzt (1W6 SP).",
    SkillGroup.handwerkstalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  holzbearbeitung(
    "TAL_51",
    "Holzbearbeitung",
    "Das Werkstück ist schneller fertig oder es wird eine bessere Qualität erzielt.",
    "Der Held kommt mit der Arbeit an dem Werkstück nicht voran.",
    "Die Zahl der FP bei dieser Probe verdoppelt sich, der Held erhält aber mindestens 5 FP. Erschwernisse, die durch misslungene Sammelproben aufgebaut wurden, werden komplett abgebaut.",
    "Ein Patzer sorgt dafür, dass die angesammelten QS auf 0 sinken und keine weitere Probe für dieses Vorhaben angewandt werden kann.",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.koerperkraft,
  ),
  lebensmittelbearbeitung(
    "TAL_52",
    "Lebensmittelbearbeitung",
    "Der Geschmack des Essens ist besser als üblich.",
    "Das Essen ist angebrannt oder ungenießbar.",
    "Die Mahlzeit ist ein echter Gaumenschmaus, ein gekelterter Wein ein wirklich edler Tropfen.",
    "Das Essen schmeckt nicht nur miserabel, der Konsum hat auch eine schwere Magenverstimmung, Durchfall oder Brechreiz (1W6 SP) zur Folge.",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  lederbearbeitung(
    "TAL_53",
    "Lederbearbeitung",
    "Das Werkstück ist schneller fertig oder es wird eine bessere Qualität erzielt.",
    "Der Held kommt mit der Arbeit an dem Werkstück nicht voran.",
    "Die Zahl der FP bei dieser Probe verdoppelt sich, der Held erhält aber mindestens 5 FP. Erschwernisse, die durch misslungene Sammelproben aufgebaut wurden, werden komplett abgebaut.",
    "Ein Patzer sorgt dafür, dass die angesammelten QS auf 0 sinken und keine weitere Probe für dieses Vorhaben angewandt werden kann.",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.gewandtheit,
    Attribute.konstitution,
  ),
  malenUndZeichnen(
    "TAL_54",
    "Malen & Zeichnen",
    "Die Qualität der Zeichnung ist besser als üblich.",
    "Dem Held gelingt eine mit Phantasie erkennbare, aber wenig schöne Zeichnung.",
    "Das Bild ist so gut, dass der Held für einen berühmten Maler gehalten wird.",
    "schreckliches, unmöglich erkennbares Gekrakel",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  metallbearbeitung(
    "TAL_55",
    "Metallbearbeitung",
    "Das Werkstück ist schneller fertig oder es wird eine bessere Qualität erzielt.",
    "Der Held kommt mit der Arbeit an dem Werkstück nicht voran.",
    "Die Zahl der FP bei dieser Probe verdoppelt sich, der Held erhält aber mindestens 5 FP. Erschwernisse, die durch misslungene Sammelproben aufgebaut wurden, werden komplett abgebaut.",
    "Ein Patzer sorgt dafür, dass die angesammelten QS auf 0 sinken und keine weitere Probe für dieses Vorhaben angewandt werden kann.",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
    Attribute.koerperkraft,
  ),
  musizieren(
    "TAL_56",
    "Musizieren",
    "Das Publikum zeigt sich begeisterter von der Vorstellung.",
    "Die Melodie klingt schief.",
    "Der Held spielt eine Melodie, der keiner widerstehen kann und die alle Zuhörer in ihren Bann zieht.",
    "Schreckliche, unheilvolle Töne werden dem Musikinstrument entlockt. Möglicherweise wird das Instrument dabei beschädigt. Menschen suchen das Weite oder wollen dem Musikanten das Instrument entreißen.",
    SkillGroup.handwerkstalente,
    Attribute.charisma,
    Attribute.fingerfertigkeit,
    Attribute.konstitution,
  ),
  schloesserknacken(
    "TAL_57",
    "Schlösserknacken",
    "Das Schloss lässt sich schneller öffnen.",
    "Das Schloss geht nicht auf.",
    "Das Schloss springt in Rekordzeit auf. Der Held benötigt nur die Hälfte des üblichen Zeitaufwandes.",
    "Der Dietrich bricht ab, die Falle wird ausgelöst oder das Schloss verklemmt sich.",
    SkillGroup.handwerkstalente,
    Attribute.intuition,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  ),
  steinbearbeitung(
    "TAL_58",
    "Steinbearbeitung",
    "Das Werkstück ist schneller fertig oder es wird eine bessere Qualität erzielt.",
    "Der Held kommt mit der Arbeit an dem Werkstück nicht voran.",
    "Die Zahl der FP bei dieser Probe verdoppelt sich, der Held erhält aber mindestens 5 FP. Erschwernisse, die durch misslungene Sammelproben aufgebaut wurden, werden komplett abgebaut.",
    "Ein Patzer sorgt dafür, dass die angesammelten QS auf 0 sinken und keine weitere Probe für dieses Vorhaben angewandt werden kann.",
    SkillGroup.handwerkstalente,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
    Attribute.koerperkraft,
  ),
  stoffbearbeitung(
    "TAL_59",
    "Stoffbearbeitung",
    "Das Werkstück ist schneller fertig oder es wird eine bessere Qualität erzielt.",
    "Der Held kommt mit der Arbeit an dem Werkstück nicht voran.",
    "Die Zahl der FP bei dieser Probe verdoppelt sich, der Held erhält aber mindestens 5 FP. Erschwernisse, die durch misslungene Sammelproben aufgebaut wurden, werden komplett abgebaut.",
    "Ein Patzer sorgt dafür, dass die angesammelten QS auf 0 sinken und keine weitere Probe für dieses Vorhaben angewandt werden kann.",
    SkillGroup.handwerkstalente,
    Attribute.klugheit,
    Attribute.fingerfertigkeit,
    Attribute.fingerfertigkeit,
  );

  final String id;
  final String name;
  final String quality;
  final String failed;
  final String critical;
  final String botch;
  final SkillGroup skillGroup;
  final Attribute attr1;
  final Attribute attr2;
  final Attribute attr3;

  const Skill(
    this.id,
    this.name,
    this.quality,
    this.failed,
    this.critical,
    this.botch,
    this.skillGroup,
    this.attr1,
    this.attr2,
    this.attr3,
  );

  @override
  String toString() {
    return name;
  }
}

const Map<String, Skill> skillKeys = {
  "TAL_1": Skill.fliegen,
  "TAL_2": Skill.gaukeleien,
  "TAL_3": Skill.klettern,
  "TAL_4": Skill.koerperbeherrschung,
  "TAL_5": Skill.kraftakt,
  "TAL_6": Skill.reiten,
  "TAL_7": Skill.schwimmen,
  "TAL_8": Skill.selbstbeherrschung,
  "TAL_9": Skill.singen,
  "TAL_10": Skill.sinnesschaerfe,
  "TAL_11": Skill.tanzen,
  "TAL_12": Skill.taschendiebstahl,
  "TAL_13": Skill.verbergen,
  "TAL_14": Skill.zechen,
  "TAL_15": Skill.bekehrenUndUeberzeugen,
  "TAL_16": Skill.betoeren,
  "TAL_17": Skill.einschuechtern,
  "TAL_18": Skill.etikette,
  "TAL_19": Skill.gassenwissen,
  "TAL_20": Skill.menschenkenntnis,
  "TAL_21": Skill.ueberreden,
  "TAL_22": Skill.verkleiden,
  "TAL_23": Skill.willenskraft,
  "TAL_24": Skill.faehrtensuchen,
  "TAL_25": Skill.fesseln,
  "TAL_26": Skill.fischenUndAngeln,
  "TAL_27": Skill.orientierung,
  "TAL_28": Skill.pflanzenkunde,
  "TAL_29": Skill.tierkunde,
  "TAL_30": Skill.wildnisleben,
  "TAL_31": Skill.brettUndGluecksspiel,
  "TAL_32": Skill.geographie,
  "TAL_33": Skill.geschichtswissen,
  "TAL_34": Skill.goetterUndKulte,
  "TAL_35": Skill.kriegskunst,
  "TAL_36": Skill.magiekunde,
  "TAL_37": Skill.mechanik,
  "TAL_38": Skill.rechnen,
  "TAL_39": Skill.rechtskunde,
  "TAL_40": Skill.sagenUndLegenden,
  "TAL_41": Skill.sphaerenkunde,
  "TAL_42": Skill.sternkunde,
  "TAL_43": Skill.alchimie,
  "TAL_44": Skill.booteUndSchiffe,
  "TAL_45": Skill.fahrzeuge,
  "TAL_46": Skill.handel,
  "TAL_47": Skill.heilkundeGift,
  "TAL_48": Skill.heilkundeKrankheiten,
  "TAL_49": Skill.heilkundeSeele,
  "TAL_50": Skill.heilkundeWunden,
  "TAL_51": Skill.holzbearbeitung,
  "TAL_52": Skill.lebensmittelbearbeitung,
  "TAL_53": Skill.lederbearbeitung,
  "TAL_54": Skill.malenUndZeichnen,
  "TAL_55": Skill.metallbearbeitung,
  "TAL_56": Skill.musizieren,
  "TAL_57": Skill.schloesserknacken,
  "TAL_58": Skill.steinbearbeitung,
  "TAL_59": Skill.stoffbearbeitung,
};
