// TODO: Differentiate between "passiv", "Basismanöver" and "Spezialmanöver".

enum SpecialAbilityBase {
  // <db-replace-token-special-abilities>
  aufmerksamkeit("SA_40", "Aufmerksamkeit", "", 1),
  belastungsgewoehnung("SA_41", "Belastungsgewöhnung", "", 1),
  beidhaendigerKampf("SA_42", "Beidhändiger Kampf", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_9',
    'CT_10',
    'CT_12',
  ]),
  berittenerKampf("SA_43", "Berittener Kampf", "", 1),
  berittenerSchuetze("SA_44", "Berittener Schütze", "", [
    'CT_1',
    'CT_2',
    'CT_11',
    'CT_14',
  ]),
  einhaendigerKampf("SA_45", "Einhändiger Kampf", "", ['CT_4', 'CT_12']),
  entwaffnen("SA_46", "Entwaffnen", "", [
    'CT_4',
    'CT_5',
    'CT_8',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  feindgespuer("SA_47", "Feindgespür", "", 1),
  finte("SA_48", "Finte", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_8',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  haltegriff("SA_49", "Haltegriff", "", ['CT_9']),
  hammerschlag("SA_50", "Hammerschlag", "", [
    'CT_5',
    'CT_6',
    'CT_12',
    'CT_15',
    'CT_16',
  ]),
  kampfreflexe("SA_51", "Kampfreflexe", "", 1),
  klingenfaenger("SA_52", "Klingenfänger", "", ['CT_3']),
  kreuzblock("SA_53", "Kreuzblock", "", ['CT_3', 'CT_4']),
  lanzenangriff("SA_54", "Lanzenangriff", "", ['CT_7']),
  praeziserSchussWurf("SA_55", "Präziser Schuss/Wurf", "", [
    'CT_1',
    'CT_18',
    'CT_2',
    'CT_19',
    'CT_11',
    'CT_14',
  ]),
  praeziserStich("SA_56", "Präziser Stich", "", ['CT_3', 'CT_4']),
  riposte("SA_57", "Riposte", "", ['CT_3', 'CT_4']),
  rundumschlag("SA_58", "Rundumschlag", "", [
    'CT_5',
    'CT_6',
    'CT_10',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  schildspalter("SA_59", "Schildspalter", "", [
    'CT_5',
    'CT_6',
    'CT_15',
    'CT_16',
  ]),
  schnellladen("SA_60", "Schnellladen", "", [
    'CT_1',
    'CT_18',
    'CT_2',
    'CT_19',
    'CT_11',
    'CT_14',
  ]),
  schnellziehen("SA_61", "Schnellziehen", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_8',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  sturmangriff("SA_62", "Sturmangriff", "", [
    'CT_5',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  todesstoss("SA_63", "Todesstoß", "", ['CT_3', 'CT_4']),
  verbessertesAusweichen("SA_64", "Verbessertes Ausweichen", "", 1),
  verteidigungshaltung("SA_65", "Verteidigungshaltung", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_9',
    'CT_10',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  vorstoss("SA_66", "Vorstoß", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  wuchtschlag("SA_67", "Wuchtschlag", "", [
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_12',
    'CT_13',
    'CT_15',
    'CT_16',
  ]),
  wurf("SA_68", "Wurf", "", ['CT_9']),
  zuFallBringen("SA_69", "Zu Fall bringen", "", ['CT_8', 'CT_13']),
  armbrustUeberdrehen("SA_151", "Armbrust überdrehen", "", ['CT_1']),
  aufDistanzHalten("SA_152", "Auf Distanz halten", "", 2),
  ballistischerSchuss("SA_153", "Ballistischer Schuss", "", ['CT_2']),
  berittenerFlugkampf("SA_154", "Berittener Flugkampf", "", 1),
  beschuetzer("SA_155", "Beschützer", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_10',
    'CT_12',
    'CT_13',
  ]),
  betaeubungsschlag("SA_156", "Betäubungsschlag", "", [
    'CT_5',
    'CT_12',
    'CT_13',
  ]),
  blindkampf("SA_157", "Blindkampf", "", 2),
  eisenhagel("SA_158", "Eisenhagel", "", "Diskusse (nur Stufe I), Wurfwaffen"),
  festnageln("SA_159", "Festnageln", "", ['CT_13']),
  gezielterAngriff("SA_160", "Gezielter Angriff", "", 2),
  gezielterSchuss("SA_161", "Gezielter Schuss", "", 3),
  herunterstossen("SA_162", "Herunterstoßen", "", ['CT_13']),
  kampfImWasser("SA_163", "Kampf im Wasser", "", 2),
  kampfstilKombination(
    "SA_164",
    "Kampfstil-Kombination",
    "",
    "je nach Kampfstil; die beiden Kampfstile lassen sich jeweils nur für die entsprechenden Kampftechniken nutzen",
  ),
  klingensturm("SA_165", "Klingensturm", "", ['CT_4', 'CT_12']),
  meisterDerImprovisiertenWaffen(
    "SA_166",
    "Meister der improvisierten Waffen",
    "",
    1,
  ),
  meisterlichesAusweichen("SA_167", "Meisterliches Ausweichen", "", []),
  meisterparade("SA_168", "Meisterparade", "", 4),
  pikenwall("SA_169", "Pikenwall", "", ['CT_13']),
  scharfschuetze("SA_170", "Scharfschütze", "", [
    'CT_1',
    'CT_18',
    'CT_2',
    'CT_19',
    'CT_11',
    'CT_14',
  ]),
  schwitzkasten("SA_171", "Schwitzkasten", "", ['CT_9']),
  unterlaufen("SA_172", "Unterlaufen", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_10',
    'CT_12',
    'CT_15',
    'CT_16',
  ]),
  verbessertesUnterlaufen("SA_173", "Verbessertes Unterlaufen", "", [
    'CT_3',
    'CT_4',
    'CT_5',
    'CT_6',
    'CT_9',
    'CT_10',
    'CT_12',
    'CT_15',
    'CT_16',
  ]),
  verteilterEisenhagel("SA_174", "Verteilter Eisenhagel", "", [
    'CT_19',
    'CT_14',
  ]),
  zweihaendigerReiterkampf("SA_175", "Zweihändiger Reiterkampf", "", [
    'CT_15',
    'CT_16',
  ]),
  unterwasserkampf("SA_418", "Unterwasserkampf", "", []),
  auflaufen("SA_860", "Auflaufen", "", ['CT_7', 'CT_21']),
  spiessgespann("SA_861", "Spießgespann", "", []),
  formation("SA_862", "Formation", "", 1),
  ausfall("SA_864", "Ausfall", "", ['CT_3', 'CT_20', 'CT_4']),
  beritteneLanzenformation("SA_865", "Berittene Lanzenformation", "", ['CT_7']),
  blutgraetsche("SA_866", "Blutgrätsche", "", ['CT_9']),
  doppelangriff("SA_867", "Doppelangriff", "", [
    'CT_3',
    'CT_20',
    'CT_4',
    'CT_5',
    'CT_12',
  ]),
  drachenkampfTaktik("SA_868", "Drachenkampf-Taktik", "", 1),
  durchgezogenerTritt("SA_869", "Durchgezogener Tritt", "", ['CT_9']),
  ellbogenangriff("SA_870", "Ellbogenangriff", "", ['CT_9']),
  gefechtsformation("SA_871", "Gefechtsformation", "", 1),
  gegenhalten("SA_872", "Gegenhalten", "", 4),
  geschossabwehr("SA_873", "Geschossabwehr", "", ['CT_9']),
  graetsche("SA_874", "Grätsche", "", ['CT_9']),
  kernschuss("SA_875", "Kernschuss", "", 3),
  khaFormation("SA_876", "Kha-Formation", "", 1),
  klingeDrehen(
    "SA_877",
    "Klinge drehen",
    "",
    "Dolche, Fechtwaffen, Schwerter, Stangenwaffen (muss eine spitze Klinge haben)",
  ),
  klingentaenzer("SA_878", "Klingentänzer", "", 1),
  kraftvollerSpeerwurf(
    "SA_879",
    "Kraftvoller Speerwurf",
    "",
    "Wurfwaffen (nur Wurfspeere)",
  ),
  lanzenfuehrung("SA_880", "Lanzenführung", "", ['CT_7']),
  machtvolleMeisterparade("SA_881", "Machtvolle Meisterparade", "", 4),
  meisterlicheGeschossabwehr("SA_882", "Meisterliche Geschossabwehr", "", [
    'CT_9',
  ]),
  meisterlicherKlingentaenzer("SA_883", "Meisterlicher Klingentänzer", "", 1),
  plaenklerFormation("SA_884", "Plänkler-Formation", "", 1),
  querschuss("SA_885", "Querschuss", "", ['CT_2']),
  reissangriff("SA_886", "Reißangriff", "", ['CT_6']),
  schildschlag("SA_887", "Schildschlag", "", []),
  turnierreiterei("SA_888", "Turnierreiterei", "", ['CT_7']),
  umrennen("SA_889", "Umrennen", "", ['CT_9']),
  umwickeln("SA_890", "Umwickeln", "", ['CT_6', 'CT_8']),
  ungeheuerTaktik("SA_891", "Ungeheuer-Taktik", "", 1),
  weitwurf("SA_892", "Weitwurf", "", []),
  wirbelangriff("SA_893", "Wirbelangriff", "", [
    'CT_3',
    'CT_20',
    'CT_4',
    'CT_9',
  ]);
  // </db-replace-token-special-abilities>

  final String id;
  final String name;
  final String rules;
  final dynamic ct;

  const SpecialAbilityBase(this.id, this.name, this.rules, this.ct);
}

const specialCombatAbilities = {
  "SA_41": SpecialAbilityBase.belastungsgewoehnung,
  "SA_42": SpecialAbilityBase.beidhaendigerKampf,
  "SA_43": SpecialAbilityBase.berittenerKampf,
  "SA_44": SpecialAbilityBase.berittenerSchuetze,
  "SA_45": SpecialAbilityBase.einhaendigerKampf,
  "SA_46": SpecialAbilityBase.entwaffnen,
  "SA_47": SpecialAbilityBase.feindgespuer,
  "SA_48": SpecialAbilityBase.finte,
  "SA_49": SpecialAbilityBase.haltegriff,
  "SA_50": SpecialAbilityBase.hammerschlag,
  "SA_51": SpecialAbilityBase.kampfreflexe,
  "SA_52": SpecialAbilityBase.klingenfaenger,
  "SA_53": SpecialAbilityBase.kreuzblock,
  "SA_54": SpecialAbilityBase.lanzenangriff,
  "SA_55": SpecialAbilityBase.praeziserSchussWurf,
  "SA_56": SpecialAbilityBase.praeziserStich,
  "SA_57": SpecialAbilityBase.riposte,
  "SA_58": SpecialAbilityBase.rundumschlag,
  "SA_59": SpecialAbilityBase.schildspalter,
  "SA_60": SpecialAbilityBase.schnellladen,
  "SA_61": SpecialAbilityBase.schnellziehen,
  "SA_62": SpecialAbilityBase.sturmangriff,
  "SA_63": SpecialAbilityBase.todesstoss,
  "SA_64": SpecialAbilityBase.verbessertesAusweichen,
  "SA_65": SpecialAbilityBase.verteidigungshaltung,
  "SA_66": SpecialAbilityBase.vorstoss,
  "SA_67": SpecialAbilityBase.wuchtschlag,
  "SA_68": SpecialAbilityBase.wurf,
  "SA_69": SpecialAbilityBase.zuFallBringen,
  "SA_151": SpecialAbilityBase.armbrustUeberdrehen,
  "SA_152": SpecialAbilityBase.aufDistanzHalten,
  "SA_153": SpecialAbilityBase.ballistischerSchuss,
  "SA_154": SpecialAbilityBase.berittenerFlugkampf,
  "SA_155": SpecialAbilityBase.beschuetzer,
  "SA_156": SpecialAbilityBase.betaeubungsschlag,
  "SA_157": SpecialAbilityBase.blindkampf,
  "SA_158": SpecialAbilityBase.eisenhagel,
  "SA_159": SpecialAbilityBase.festnageln,
  "SA_160": SpecialAbilityBase.gezielterAngriff,
  "SA_161": SpecialAbilityBase.gezielterSchuss,
  "SA_162": SpecialAbilityBase.herunterstossen,
  "SA_163": SpecialAbilityBase.kampfImWasser,
  "SA_164": SpecialAbilityBase.kampfstilKombination,
  "SA_165": SpecialAbilityBase.klingensturm,
  "SA_166": SpecialAbilityBase.meisterDerImprovisiertenWaffen,
  "SA_167": SpecialAbilityBase.meisterlichesAusweichen,
  "SA_168": SpecialAbilityBase.meisterparade,
  "SA_169": SpecialAbilityBase.pikenwall,
  "SA_170": SpecialAbilityBase.scharfschuetze,
  "SA_171": SpecialAbilityBase.schwitzkasten,
  "SA_172": SpecialAbilityBase.unterlaufen,
  "SA_173": SpecialAbilityBase.verbessertesUnterlaufen,
  "SA_174": SpecialAbilityBase.verteilterEisenhagel,
  "SA_175": SpecialAbilityBase.zweihaendigerReiterkampf,
  "SA_418": SpecialAbilityBase.unterwasserkampf,
  "SA_860": SpecialAbilityBase.auflaufen,
  "SA_861": SpecialAbilityBase.spiessgespann,
  "SA_862": SpecialAbilityBase.formation,
  "SA_864": SpecialAbilityBase.ausfall,
  "SA_865": SpecialAbilityBase.beritteneLanzenformation,
  "SA_866": SpecialAbilityBase.blutgraetsche,
  "SA_867": SpecialAbilityBase.doppelangriff,
  "SA_868": SpecialAbilityBase.drachenkampfTaktik,
  "SA_869": SpecialAbilityBase.durchgezogenerTritt,
  "SA_870": SpecialAbilityBase.ellbogenangriff,
  "SA_871": SpecialAbilityBase.gefechtsformation,
  "SA_872": SpecialAbilityBase.gegenhalten,
  "SA_873": SpecialAbilityBase.geschossabwehr,
  "SA_874": SpecialAbilityBase.graetsche,
  "SA_875": SpecialAbilityBase.kernschuss,
  "SA_876": SpecialAbilityBase.khaFormation,
  "SA_877": SpecialAbilityBase.klingeDrehen,
  "SA_878": SpecialAbilityBase.klingentaenzer,
  "SA_879": SpecialAbilityBase.kraftvollerSpeerwurf,
  "SA_880": SpecialAbilityBase.lanzenfuehrung,
  "SA_881": SpecialAbilityBase.machtvolleMeisterparade,
  "SA_882": SpecialAbilityBase.meisterlicheGeschossabwehr,
  "SA_883": SpecialAbilityBase.meisterlicherKlingentaenzer,
  "SA_884": SpecialAbilityBase.plaenklerFormation,
  "SA_885": SpecialAbilityBase.querschuss,
  "SA_886": SpecialAbilityBase.reissangriff,
  "SA_887": SpecialAbilityBase.schildschlag,
  "SA_888": SpecialAbilityBase.turnierreiterei,
  "SA_889": SpecialAbilityBase.umrennen,
  "SA_890": SpecialAbilityBase.umwickeln,
  "SA_891": SpecialAbilityBase.ungeheuerTaktik,
  "SA_892": SpecialAbilityBase.weitwurf,
  "SA_893": SpecialAbilityBase.wirbelangriff,
};

class SpecialAbility {
  final SpecialAbilityBase value;
  final int? tier;

  SpecialAbility(this.value, this.tier);

  Map<String, dynamic> toJson() {
    if (tier != null) {
      return {"tier": tier};
    } else {
      return {};
    }
  }

  @override
  String toString() {
    if (tier != null) {
      return "${value.name} $tier";
    } else {
      return value.name;
    }
  }
}
