import 'generated/_special_abilities.dart';
export 'generated/_special_abilities.dart';
import '../widgets/widget_helpers.dart';

const specialCombatAbilities = {
  "SA_41": SpecialAbilityBase.belastungsgewoehnung,
  "SA_42": SpecialAbilityBase.beidhaendigerKampf,
  "SA_43": SpecialAbilityBase.berittenerKampf,
  "SA_44": SpecialAbilityBase.berittenerSchuetze,
  "SA_45": SpecialAbilityBase.einhaendigerKampf,
  "SA_46": SpecialAbilityBase.entwaffnen,
  "SA_47": SpecialAbilityBase.feindgespuer,
  "SA_48": SpecialAbilityBase.finte,
  "SA_49": SpecialAbilityBase.haltegriff,
  "SA_50": SpecialAbilityBase.hammerschlag,
  "SA_51": SpecialAbilityBase.kampfreflexe,
  "SA_52": SpecialAbilityBase.klingenfaenger,
  "SA_53": SpecialAbilityBase.kreuzblock,
  "SA_54": SpecialAbilityBase.lanzenangriff,
  "SA_55": SpecialAbilityBase.praeziserSchussWurf,
  "SA_56": SpecialAbilityBase.praeziserStich,
  "SA_57": SpecialAbilityBase.riposte,
  "SA_58": SpecialAbilityBase.rundumschlag,
  "SA_59": SpecialAbilityBase.schildspalter,
  "SA_60": SpecialAbilityBase.schnellladen,
  "SA_61": SpecialAbilityBase.schnellziehen,
  "SA_62": SpecialAbilityBase.sturmangriff,
  "SA_63": SpecialAbilityBase.todesstoss,
  "SA_64": SpecialAbilityBase.verbessertesAusweichen,
  "SA_65": SpecialAbilityBase.verteidigungshaltung,
  "SA_66": SpecialAbilityBase.vorstoss,
  "SA_67": SpecialAbilityBase.wuchtschlag,
  "SA_68": SpecialAbilityBase.wurf,
  "SA_69": SpecialAbilityBase.zuFallBringen,
  "SA_151": SpecialAbilityBase.armbrustUeberdrehen,
  "SA_152": SpecialAbilityBase.aufDistanzHalten,
  "SA_153": SpecialAbilityBase.ballistischerSchuss,
  "SA_154": SpecialAbilityBase.berittenerFlugkampf,
  "SA_155": SpecialAbilityBase.beschuetzer,
  "SA_156": SpecialAbilityBase.betaeubungsschlag,
  "SA_157": SpecialAbilityBase.blindkampf,
  "SA_158": SpecialAbilityBase.eisenhagel,
  "SA_159": SpecialAbilityBase.festnageln,
  "SA_160": SpecialAbilityBase.gezielterAngriff,
  "SA_161": SpecialAbilityBase.gezielterSchuss,
  "SA_162": SpecialAbilityBase.herunterstossen,
  "SA_163": SpecialAbilityBase.kampfImWasser,
  "SA_164": SpecialAbilityBase.kampfstilKombination,
  "SA_165": SpecialAbilityBase.klingensturm,
  "SA_166": SpecialAbilityBase.meisterDerImprovisiertenWaffen,
  "SA_167": SpecialAbilityBase.meisterlichesAusweichen,
  "SA_168": SpecialAbilityBase.meisterparade,
  "SA_169": SpecialAbilityBase.pikenwall,
  "SA_170": SpecialAbilityBase.scharfschuetze,
  "SA_171": SpecialAbilityBase.schwitzkasten,
  "SA_172": SpecialAbilityBase.unterlaufen,
  "SA_173": SpecialAbilityBase.verbessertesUnterlaufen,
  "SA_174": SpecialAbilityBase.verteilterEisenhagel,
  "SA_175": SpecialAbilityBase.zweihaendigerReiterkampf,
  "SA_418": SpecialAbilityBase.unterwasserkampf,
  "SA_860": SpecialAbilityBase.auflaufen,
  "SA_861": SpecialAbilityBase.spiessgespann,
  "SA_862": SpecialAbilityBase.formation,
  "SA_864": SpecialAbilityBase.ausfall,
  "SA_865": SpecialAbilityBase.beritteneLanzenformation,
  "SA_866": SpecialAbilityBase.blutgraetsche,
  "SA_867": SpecialAbilityBase.doppelangriff,
  "SA_868": SpecialAbilityBase.drachenkampfTaktik,
  "SA_869": SpecialAbilityBase.durchgezogenerTritt,
  "SA_870": SpecialAbilityBase.ellbogenangriff,
  "SA_871": SpecialAbilityBase.gefechtsformation,
  "SA_872": SpecialAbilityBase.gegenhalten,
  "SA_873": SpecialAbilityBase.geschossabwehr,
  "SA_874": SpecialAbilityBase.graetsche,
  "SA_875": SpecialAbilityBase.kernschuss,
  "SA_876": SpecialAbilityBase.khaFormation,
  "SA_877": SpecialAbilityBase.klingeDrehen,
  "SA_878": SpecialAbilityBase.klingentaenzer,
  "SA_879": SpecialAbilityBase.kraftvollerSpeerwurf,
  "SA_880": SpecialAbilityBase.lanzenfuehrung,
  "SA_881": SpecialAbilityBase.machtvolleMeisterparade,
  "SA_882": SpecialAbilityBase.meisterlicheGeschossabwehr,
  "SA_883": SpecialAbilityBase.meisterlicherKlingentaenzer,
  "SA_884": SpecialAbilityBase.plaenklerFormation,
  "SA_885": SpecialAbilityBase.querschuss,
  "SA_886": SpecialAbilityBase.reissangriff,
  "SA_887": SpecialAbilityBase.schildschlag,
  "SA_888": SpecialAbilityBase.turnierreiterei,
  "SA_889": SpecialAbilityBase.umrennen,
  "SA_890": SpecialAbilityBase.umwickeln,
  "SA_891": SpecialAbilityBase.ungeheuerTaktik,
  "SA_892": SpecialAbilityBase.weitwurf,
  "SA_893": SpecialAbilityBase.wirbelangriff,
  "SA_196": SpecialAbilityBase.aufspiessen,
  "SA_197": SpecialAbilityBase.binden,
  "SA_198": SpecialAbilityBase.breschenangriff,
  "SA_199": SpecialAbilityBase.fahrenderSchuetze,
  "SA_200": SpecialAbilityBase.frontalangriff,
  "SA_201": SpecialAbilityBase.fussfeger,
  "SA_202": SpecialAbilityBase.haltegriffBrechen,
  "SA_203": SpecialAbilityBase.handkantenschlag,
  "SA_204": SpecialAbilityBase.hoheKlinge,
  "SA_205": SpecialAbilityBase.kopfstoss,
  "SA_206": SpecialAbilityBase.maechtigerLanzenangriff,
  "SA_207": SpecialAbilityBase.maechtigerRundumschlag,
  "SA_208": SpecialAbilityBase.meisterlicherWurf,
  "SA_209": SpecialAbilityBase.schilddeckung,
  "SA_210": SpecialAbilityBase.schildstoss,
  "SA_211": SpecialAbilityBase.schwinger,
  "SA_212": SpecialAbilityBase.sprungangriff,
  "SA_213": SpecialAbilityBase.sprungtritt,
  "SA_214": SpecialAbilityBase.tiefschlag,
  "SA_215": SpecialAbilityBase.todVonLinks,
  "SA_216": SpecialAbilityBase.verkuerzteWaffenfuehrung,
  "SA_217": SpecialAbilityBase.vorbeiziehen,
  "SA_218": SpecialAbilityBase.waffenwurf,
  "SA_219": SpecialAbilityBase.weiterSchwung,
  "SA_220": SpecialAbilityBase.windmuehle,
  "SA_221": SpecialAbilityBase.wuchtigerWurf,
  "SA_222": SpecialAbilityBase.wuergegriff,
  "SA_223": SpecialAbilityBase.zertruemmern,
  "SA_863": SpecialAbilityBase.angetaeuschterAngriff,
  "SA_947": SpecialAbilityBase.angriffNachHinten,
  "SA_948": SpecialAbilityBase.antaeuschen,
  "SA_949": SpecialAbilityBase.aufliegendeKlinge,
  "SA_950": SpecialAbilityBase.berserkerangriff,
  "SA_951": SpecialAbilityBase.blattschuss,
  "SA_952": SpecialAbilityBase.blitzreflexe,
  "SA_953": SpecialAbilityBase.defensivesVerhalten,
  "SA_954": SpecialAbilityBase.drachentod,
  "SA_955": SpecialAbilityBase.drehschlag,
  "SA_956": SpecialAbilityBase.drehwurf,
  "SA_957": SpecialAbilityBase.durchbohrung,
  "SA_958": SpecialAbilityBase.fixierungsschuss,
  "SA_959": SpecialAbilityBase.eisenfaust,
  "SA_960": SpecialAbilityBase.erweiterteDrachenkampfTaktik,
  "SA_961": SpecialAbilityBase.extremschuss,
  "SA_962": SpecialAbilityBase.formationsattacke,
  "SA_963": SpecialAbilityBase.formationsparade,
  "SA_964": SpecialAbilityBase.geschickterWurf,
  "SA_965": SpecialAbilityBase.machtvollerKernschuss,
  "SA_966": SpecialAbilityBase.machtvollerSturmangriff,
  "SA_967": SpecialAbilityBase.machtvollerWirbelangriff,
  "SA_968": SpecialAbilityBase.meisterElfischerWaffen,
  "SA_969": SpecialAbilityBase.meisterZwergischerWaffen,
  "SA_970": SpecialAbilityBase.meisterlicherTurnierreiter,
  "SA_971": SpecialAbilityBase.meisterlichesUmrennen,
  "SA_972": SpecialAbilityBase.mieseTricks,
  "SA_973": SpecialAbilityBase.nachladespezialist,
  "SA_974": SpecialAbilityBase.nervoesMachen,
  "SA_975": SpecialAbilityBase.offensivesVerhalten,
  "SA_976": SpecialAbilityBase.rueckendeckung,
  "SA_977": SpecialAbilityBase.reizen,
  "SA_978": SpecialAbilityBase.riskanterSchuss,
  "SA_979": SpecialAbilityBase.schmerzwut,
  "SA_980": SpecialAbilityBase.sprungwurf,
  "SA_981": SpecialAbilityBase.taktikDurchbrechen,
  "SA_982": SpecialAbilityBase.taktischeBefehle,
  "SA_983": SpecialAbilityBase.tiefeWunde,
  "SA_984": SpecialAbilityBase.verbesserteAufmerksamkeit,
  "SA_985": SpecialAbilityBase.verbesserterBetaeubungsschlag,
  "SA_986": SpecialAbilityBase.verbesserterDoppelangriff,
  "SA_987": SpecialAbilityBase.verbesserterSchwitzkasten,
  "SA_988": SpecialAbilityBase.versteckteKlinge,
  "SA_989": SpecialAbilityBase.zweifacherAngriff,
  "SA_1140": SpecialAbilityBase.sprungVomReittier,
  "SA_1146": SpecialAbilityBase.betaeubendesGeschoss,
};

class SpecialAbility {
  final SpecialAbilityBase value;
  final int? tier;
  final bool lowerTier = false;

  SpecialAbility(this.value, this.tier, {lowerTier});

  Map<String, dynamic> toJson() {
    if (tier != null) {
      return {"tier": tier};
    } else {
      return {};
    }
  }

  @override
  String toString() {
    if (tier != null) {
      return "${value.name} ${roman(tier!)}";
    } else {
      return value.name;
    }
  }
}

enum SpecialAbilityType { passive, baseManeuvre, specialManeuvre }
