enum SpecialAbilityBase {
  aufmerksamkeit(
    "SA_40",
    "Aufmerksamkeit",
    "Bei einem Hinterhalt oder wenn es darum geht, ob er überrascht wird, erhält er eine Erleichterung von 2 auf *Sinnesschärfe (Hinterhalt entdecken)*, um seine Gegner zu entdecken.",
    1,
  ),
  belastungsgewoehnung(
    "SA_41",
    "Belastungsgewöhnung",
    "Diese SF sorgt dafür, dass für den Kämpfer die negativen Auswirkungen seiner Rüstung um zwei Schritte pro Stufe der Belastungsgewöhnung in der BE-Spalte und der zusätzlichen Abzüge der Rüstungen nach oben wandern. Eine Plattenrüstung würde also bei Belastungsgewöhnung I nur noch behindern wie eine Kettenrüstung (was BE, GS und INI angeht). Der RS bleibt selbstverständlich erhalten.",
    1,
  ),
  beidhaendigerKampf(
    "SA_42",
    "Beidhändiger Kampf",
    "Der Abzug auf Attacke und Parade beträgt bei Stufe I der Sonderfertigkeit nur 1 statt wie üblich 2. Bei Stufe II der Sonderfertigkeit sinken die Erschwernisse zusätzlich zu dem Bonus aus Beidhändiger Kampf I um einen weiteren Punkt auf insgesamt 0.",
    ['CT_3', 'CT_4', 'CT_5', 'CT_9', 'CT_10', 'CT_12'],
  ),
  berittenerKampf(
    "SA_43",
    "Berittener Kampf",
    "Der Reiter hat die Möglichkeit im Reiterkampf spezielle Befehle zu erteilen, beispielsweise Niederreiten oder Sturmangriff zu Pferd.",
    1,
  ),
  berittenerSchuetze(
    "SA_44",
    "Berittener Schütze",
    "Geht das Reittier, ist das Schießen nicht mehr erschwert. Im Galopp ist es nur noch um 4 erschwert. Der Schütze kann zudem aus vollem Galopp nach hinten schießen. Im Trab sind weiterhin Glückstreffer möglich (also bei einer 1 auf W20).",
    ['CT_1', 'CT_2', 'CT_11', 'CT_14'],
  ),
  einhaendigerKampf(
    "SA_45",
    "Einhändiger Kampf",
    "Der Kämpfer erhält folgende Boni, wenn er ausschließlich nur mit einer Waffe einhändig kämpft, also die Waffe nicht mit einer zweiten Waffe, einem Schild, einer Parierwaffe oder einem sonstigen Gegenstand führt: +1 AT, +1 PA, +1 TP.",
    ['CT_4', 'CT_12'],
  ),
  entwaffnen(
    "SA_46",
    "Entwaffnen",
    "Um dem Gegner mit diesem Manöver eine Waffe (ausgenommen Schilde) aus der Hand zu schlagen, ist eine um 4, gegen Zweihandwaffen sogar um 6 erschwerte Attacke nötig. Gegen diesen Angriff kann eine reguläre Verteidigung durchgeführt werden. Misslingt diese, wird die Waffe fallen gelassen.\n\nDer Angriff verursacht 1W3 TP. Um eine Waffe wieder aufzuheben, muss der Held die Regeln für Aufheben von Gegenständen im Kampf befolgen.",
    ['CT_4', 'CT_5', 'CT_8', 'CT_9', 'CT_12', 'CT_13', 'CT_15', 'CT_16'],
  ),
  feindgespuer(
    "SA_47",
    "Feindgespür",
    "Passierschläge sind gegen ihn zusätzlich um 4 erschwert.",
    1,
  ),
  finte(
    "SA_48",
    "Finte",
    "Der Angreifer kann mit diesem Manöver seine eigene Attacke pro Stufe der Sonderfertigkeit um 1 erschweren, was beim Gelingen die Verteidigung des Gegners um 2 pro Stufe der Sonderfertigkeit erschwert.",
    [
      'CT_3',
      'CT_4',
      'CT_5',
      'CT_8',
      'CT_9',
      'CT_12',
      'CT_13',
      'CT_15',
      'CT_16',
    ],
  ),
  haltegriff(
    "SA_49",
    "Haltegriff",
    "Hierzu ist eine erfolgreiche Raufen-AT nötig. Kann der Gegner sich nicht verteidigen, hält der Angreifer ihn fest. So lange der Gegner festgehalten wird, leidet er unter dem Status *Fixiert* und *Eingeengt*. Um sich aus dem Haltegriff zu lösen, ist eine vergleichende Probe auf *Kraftakt (Ziehen & Zerren)* nötig. Der Haltende kann sich nicht verteidigen, so lange er seinen Gegner festhält. Für den Haltegriff muss der Angreifer beide Hände frei haben. Der Haltegriff kann nur gegen Gegner gleicher oder kleinerer Größenkategorie verwendet werden.",
    ['CT_9'],
  ),
  hammerschlag(
    "SA_50",
    "Hammerschlag",
    "Die Attacke für den Hammerschlag ist um 2 erschwert. Dafür wird zur Bestimmung des Schadens ein weiterer W6 zu den Trefferpunkten hinzuaddiert. Wenn das Manöver misslingt, steht dem Verteidiger ein Passierschlag zu.",
    ['CT_5', 'CT_6', 'CT_12', 'CT_15', 'CT_16'],
  ),
  kampfreflexe(
    "SA_51",
    "Kampfreflexe",
    "Der INI-Basiswert steigt um 1 pro Stufe der Sonderfertigkeit.",
    1,
  ),
  klingenfaenger(
    "SA_52",
    "Klingenfänger",
    "Der passive PA-Bonus der vom Helden geführten Parierwaffe steigt um 1.",
    ['CT_3'],
  ),
  kreuzblock(
    "SA_53",
    "Kreuzblock",
    "Um mit Dolchen oder mit Fechtwaffen Waffen der Kampftechniken Kettenwaffen, Stangenwaffen, Zweihandhiebwaffen und Zweihandschwerter parieren zu können, bedarf es der Sonderfertigkeit Kreuzblock und zweier geführter Waffen. Bei der Parade erleidet der Kämpfer keine Abzüge durch die falsche Hand.",
    ['CT_3', 'CT_4'],
  ),
  lanzenangriff(
    "SA_54",
    "Lanzenangriff",
    "Möchte der Reiter einen Gegner mit einer Lanze angreifen, muss dazu der *Befehl* Lanzenangriff erteilt werden. Der Lanzenangriff kann nur im Galopp ausgeführt werden. Nach der Probe auf *Reiten* wird eine Attacke auf Lanzen ausgeführt (dies kostet keine zusätzliche Aktion, sondern ist Teil des Befehls). Pferd und Reiter verringern ihre Geschwindigkeit nach erfolgtem Angriff nicht automatisch.\n\nAußerdem kann ein solcher Angriff nicht mit einer Waffe pariert werden, nur eine Parade mit einem Schild oder Ausweichen sind möglich. Bei einer gelungenen Attacke und einer gelungenen Parade mit dem Schild oder einem unverteidigten Treffer lässt der Angreifer die Lanze los, um nicht vom Aufprall aus dem Sattel gehoben zu werden. Ist der Lanzenangriff erfolgreich, steigen die TP um 2 + GS/2 des Reittiers.\n\nDie Werte der Kriegslanze findest du auf Seite **367**.",
    ['CT_7'],
  ),
  praeziserSchussWurf(
    "SA_55",
    "Präziser Schuss/Wurf",
    "Hierzu erschwert sich der Angreifer die Probe auf Fernkampf um 2 pro Stufe der Sonderfertigkeit. Bei Erfolg werden die Trefferpunkte um 2 pro Stufe der Sonderfertigkeit erhöht.",
    ['CT_1', 'CT_18', 'CT_2', 'CT_19', 'CT_11', 'CT_14'],
  ),
  praeziserStich(
    "SA_56",
    "Präziser Stich",
    "Er erschwert seine Attacke um 2 pro Stufe der Sonderfertigkeit. Bei Erfolg werden die Trefferpunkte um 2 pro Stufe der Sonderfertigkeit erhöht.",
    ['CT_3', 'CT_4'],
  ),
  riposte(
    "SA_57",
    "Riposte",
    "Nach einer erfolgreichen Parade, die für den Kämpfer um 2 erschwert ist, kann er sofort einen Passierschlag gegen seinen Angreifer ausführen. Das Manöver Riposte muss vor dem Attackewurf des Angreifers angesagt werden. Nach der Riposte kann der Kämpfer keine weiteren Verteidigungen in dieser KR mehr durchführen. Eine Riposte kann nicht mit einem Basismanöver kombiniert werden.",
    ['CT_3', 'CT_4'],
  ),
  rundumschlag(
    "SA_58",
    "Rundumschlag",
    "Die angegriffenen Gegner dürfen auf den Angriff getrennt reagieren. Die erste Attacke ist um 2, die zweite um 6 und die dritte um 10 erschwert. Wenn die Verteidigung der Gegner misslingt, wird für jeden Gegner einzeln Schaden ausgewürfelt.\n\nRundumschlag I erlaubt den Angriff auf zwei Gegner, Rundumschlag II den Angriff auf drei Gegner.\n\nEin Patzer bei einem der Angriffe bedeutet, dass keine weiteren Attacken des Rundumschlags in dieser KR ausgeführt werden können.",
    ['CT_5', 'CT_6', 'CT_10', 'CT_12', 'CT_13', 'CT_15', 'CT_16'],
  ),
  schildspalter(
    "SA_59",
    "Schildspalter",
    "Hierzu wird eine Attacke gegen den Schild durchgeführt, gegen die der Gegner mit einer Parade mit dem Schild oder Ausweichen verteidigen darf. Für eine Parade mit dem Schild kann der Parade-Bonus des Schildes nicht genutzt werden. Misslingt die Parade oder das Ausweichen, wird der Schaden von den Strukturpunkten des Schildes abgezogen. Fallen diese auf 0, ist der Schild zerstört. Dieses Spezialmanöver kann nur gegen Schildkämpfer eingesetzt werden. Mehr zu Strukturpunkten siehe Seite **349**.",
    ['CT_5', 'CT_6', 'CT_15', 'CT_16'],
  ),
  schnellladen(
    "SA_60",
    "Schnellladen",
    "Das Nachladen von Blasrohren, Bögen, Diskussen oder Schleudern und das Bereitmachen von Wurfwaffen verkürzen sich um 1 Aktion. Das Nachladen von Armbrüsten dauert nur die Hälfte der angegebenen Aktionen. Diese Sonderfertigkeit muss für die sechs Fernkampftechniken Armbrüste, Blasrohre, Bögen, Diskusse, Schleudern und Wurfwaffen einzeln erworben werden.",
    ['CT_1', 'CT_18', 'CT_2', 'CT_19', 'CT_11', 'CT_14'],
  ),
  schnellziehen(
    "SA_61",
    "Schnellziehen",
    "Anstatt 1 Aktion aufzuwenden, reicht 1 freie Aktion aus, um eine Waffe zu ziehen.",
    [
      'CT_3',
      'CT_4',
      'CT_5',
      'CT_6',
      'CT_8',
      'CT_12',
      'CT_13',
      'CT_15',
      'CT_16',
    ],
  ),
  sturmangriff(
    "SA_62",
    "Sturmangriff",
    "Das Manöver Sturmangriff kann nur durchgeführt werden, wenn der Angreifer eine Anlaufstrecke von mindestens 4 Schritt hat und über eine GS von mindestens 4 verfügt. Die Bewegung ist Teil der Aktion, mit der man angreift. Ist der Sturmangriff erfolgreich, steigen die TP um 2 und die halbe GS des Angreifers. Dieser Angriff kann regulär abgewehrt werden. Sollte der Sturmangriff misslingen, erhält der Verteidiger die Gelegenheit für einen Passierschlag. Dieses Spezialmanöver kann nicht mit dem Basismanöver Finte kombiniert werden.",
    ['CT_5', 'CT_12', 'CT_13', 'CT_15', 'CT_16'],
  ),
  todesstoss(
    "SA_63",
    "Todesstoß",
    "Die Attacke für den Todesstoß ist um 2 erschwert. Dafür wird zur Bestimmung des Schadens ein weiterer W6 zu den Trefferpunkten hinzuaddiert. Wenn das Manöver misslingt, steht dem Verteidiger ein Passierschlag zu.",
    ['CT_3', 'CT_4'],
  ),
  verbessertesAusweichen(
    "SA_64",
    "Verbessertes Ausweichen",
    "Jede Stufe der Sonderfertigkeit erhöht Ausweichen um 1. Um die Sonderfertigkeit nutzen zu können, darf der Held maximal normale Kleidung tragen.",
    1,
  ),
  verteidigungshaltung(
    "SA_65",
    "Verteidigungshaltung",
    "Mit dieser Sonderfertigkeit kann man für die aktuelle Kampfrunde seinen Verteidigungswert um 4 erhöhen. Dafür kann man diese Kampfrunde keine Aktionen mehr ausführen. Verteidigungshaltung muss am Anfang der Runde angesagt werden.",
    [
      'CT_3',
      'CT_4',
      'CT_5',
      'CT_9',
      'CT_10',
      'CT_12',
      'CT_13',
      'CT_15',
      'CT_16',
    ],
  ),
  vorstoss(
    "SA_66",
    "Vorstoß",
    "Mit dieser Sonderfertigkeit kann man seinen Attackewert für die aktuelle Kampfrunde um 2 erhöhen. Dafür kann man diese Kampfrunde keine Verteidigung mehr ausführen. Ein Vorstoß muss am Anfang der Runde angesagt werden. Der Vorstoß kann nicht im Status *Liegend* ausgeführt werden.",
    [
      'CT_3',
      'CT_4',
      'CT_5',
      'CT_6',
      'CT_9',
      'CT_12',
      'CT_13',
      'CT_15',
      'CT_16',
    ],
  ),
  wuchtschlag(
    "SA_67",
    "Wuchtschlag",
    "Die Attacke wird um 2 pro Stufe der Sonderfertigkeit erschwert. Bei Erfolg werden die Trefferpunkte um 2 pro Stufe der Sonderfertigkeit erhöht.",
    ['CT_5', 'CT_6', 'CT_9', 'CT_12', 'CT_13', 'CT_15', 'CT_16'],
  ),
  wurf(
    "SA_68",
    "Wurf",
    "Hierzu muss er ihn zuerst in einen Haltegriff bekommen (siehe Sonderfertigkeit Haltegriff). So lange der Gegner festgehalten wird, leidet er unter den Status *Fixiert* und *Eingeengt*. Hält er seinen Gegner, muss er eine um 2 erschwerte Raufen-AT ausführen. Gelingt diese und kann der Gegner sich nicht erfolgreich verteidigen, geht der Gegner zu Boden und erleidet den Status *Liegend*. Der Wurf selbst verursacht 1W3 TP, ein möglicher darauf folgender Sturz beispielsweise von einer Klippe oder in ein Feuer unter Umständen deutlich mehr.",
    ['CT_9'],
  ),
  zuFallBringen(
    "SA_69",
    "Zu Fall bringen",
    "Die Attacke ist um 4 erschwert. Gegen diesen Angriff kann verteidigt werden. Ist die Verteidigung misslungen, stürzt der Gegner und erleidet den Status Liegend. Der Angriff verursacht 1W3 TP.",
    ['CT_8', 'CT_13'],
  ),
  armbrustUeberdrehen(
    "SA_151",
    "Armbrust überdrehen",
    "Beim Spannen der Armbrust, also bei der 1. Aktion des Ladens, muss das Überdrehen angekündigt werden. Der Schuss richtet +1 TP an. Bei einem Patzer reißt die Armbrustsehne und solange sie nicht ersetzt wird, kann sie nicht mehr benutzt werden. Zudem bekommt der Held neben dem regulären Schaden eines Patzers zusätzlich 1W3 SP.",
    ['CT_1'],
  ),
  aufDistanzHalten(
    "SA_152",
    "Auf Distanz halten",
    "Wer einen Gegner auf Distanz halten will, muss über eine Waffe verfügen, deren Reichweite größer ist als die Reichweite des Widersachers. Ist diese Voraussetzung erfüllt, erhöhen sich die AT-Erschwernisse für den Gegner zusätzlich um 1 pro Stufe der SF (siehe **Regelwerk** Seite **231**).\n\nDafür kann der Held in dieser KR keine Basismanöver einsetzen. Auf Distanz halten muss am Anfang der Runde angesagt werden.",
    2,
  ),
  ballistischerSchuss(
    "SA_153",
    "Ballistischer Schuss",
    "Schüsse mit Waffen der Kampftechniken Bögen haben in der Reichweitenkategorie weit eine um 50 % höhere Reichweite. Beispielsweise würde ein Bogen mit einer Reichweite von 100 Schritt in der Kategorie weit durch einen Ballistischen Schuss eine maximale Reichweite von 150 Schritt erreichen. Ein Ballistischer Schuss ist um 2 erschwert.",
    ['CT_2'],
  ),
  berittenerFlugkampf(
    "SA_154",
    "Berittener Flugkampf",
    "Mit dieser Sonderfertigkeit kann ein Reiter sein Flugreittier Befehle durchführen lassen.",
    1,
  ),
  beschuetzer(
    "SA_155",
    "Beschützer",
    "Die Abenteurerin kann gegnerische Attacken für Gefährten parieren. Dazu muss der Gegner in Angriffsdistanz sein und die Heldin eine ihrer eigenen Reaktionen als PA nutzen. Sollte die PA misslingen, kann der ursprünglich angegriffene Gefährte immer nochversuchen, den Angriff zu verteidigen.",
    ['CT_3', 'CT_4', 'CT_5', 'CT_10', 'CT_12', 'CT_13'],
  ),
  betaeubungsschlag(
    "SA_156",
    "Betäubungsschlag",
    "Gelingt die um 2 erschwerte AT und misslingt die Verteidigung, richtet der Angriff 1W3 TP an. Außerdem muss der Getroffene eine Probe auf *Selbstbeherrschung (Handlungsfähigkeit bewahren)* erschwert um die Anzahl der angerichteten TP ablegen (egal ob Schaden verursacht wurde oder nicht). Bei Misslingen erleidet er 1 Stufe *Betäubung*. Das Manöver lässt sich nur gegen Kulturschaffende und Tiere der Größenkategorie des Helden oder kleiner anwenden. Ja, das bedeutet, dass ein Betäubungsschlag gegen Ungeheuer wirkungslos ist.",
    ['CT_5', 'CT_12', 'CT_13'],
  ),
  blindkampf(
    "SA_157",
    "Blindkampf",
    "Mit der SF Blindkampf kann die Abenteurerin die Auswirkungen von Sichtmodifikatoren im Nahkampf auf AT und Verteidigungen abmildern (siehe **Regelwerk** Seite **239**). Für sie sind die Auswirkungen immer so viele Stufen niedriger, wie die Stufe der SF beträgt. Fernkampf und andere Proben werden von der SF nicht beeinflusst.",
    2,
  ),
  eisenhagel(
    "SA_158",
    "Eisenhagel",
    "Der Abenteurer ist durch die SF Eisenhagel in der Lage, innerhalb 1 Aktion mehrere Wurfwaffen des gleichen Waffentyps einzusetzen (also mehrere Wurfdolche, mehrere Wurfsterne usw.). Durch Eisenhagel I kann er zwei Wurfwaffen gleichzeitig benutzen, durch Eisenhagel II sogar drei. Die Ladezeit, die er benötigt, um alle Wurfwaffen des Eisenhagels bereitzumachen, beträgt 1 Aktion, egal ob es zwei oder drei Waffen sind. Das Ziel der Angriffe muss dabei immer gleich sein. Ein Patzer bei einem der Angriffe bedeutet, dass keine weiteren Attacken des Eisenhagels in dieser KR ausgeführt werden können. Es dürfen nur Fernkampfwaffen mit einem maximalen Gewicht von 0,5 Stein verwendet werden.",
    "Diskusse (nur Stufe I), Wurfwaffen",
  ),
  festnageln(
    "SA_159",
    "Festnageln",
    "Ein Festnageln-Manöver kann nur gegen Gegner durchgeführt werden, die den Status *Liegend* aufweisen. Gelingt die um 4 erschwerte AT und misslingt die Verteidigung, so ist das Opfer festgenagelt. Die Heldin kann mit der verwendeten Waffe nicht mehr parieren, sie kann nur noch ausweichen.\n\nIn den nachfolgenden KR gelingt die AT automatisch, ohne dass die Spielerin würfeln muss. Jede KR richtet der Angriff +1 TP an (in der 1. KR noch keinen zusätzlichen TP, in der 2. KR +1 TP, in der 3. KR +2 TP usw.). Die TP werden wie üblich ausgewürfelt. Der Gegner erhält den Status *Fixiert* und behält den Status *Liegend*. Solange das Opfer festgenagelt ist, kann es sich nicht verteidigen. Die Angreiferin kann am Ende einer KR entscheiden loszulassen. Um sich zu befreien, muss das Opfer eine Vergleichsprobe auf *Kraftakt (Drücken & Verbiegen)* gegen die Heldin gewinnen. Jede Probe kostet 1 Aktion. Das Festnageln-Manöver kann nur gegen Ziele der Größenkategorie klein oder mittel angewandt werden.",
    ['CT_13'],
  ),
  gezielterAngriff(
    "SA_160",
    "Gezielter Angriff",
    "Mit diesem Manöver kann man gezielt eine Trefferzone angreifen. Dazu ist eine Attacke nötig, die entsprechend dem Zonenaufschlag erschwert ist.",
    2,
  ),
  gezielterSchuss(
    "SA_161",
    "Gezielter Schuss",
    "Der Schütze kann im Fernkampf gezielt eine Trefferzone beschießen. Dazu ist eine Probe auf Fernkampf nötig, die entsprechend dem Zonenaufschlag erschwert ist.",
    3,
  ),
  herunterstossen(
    "SA_162",
    "Herunterstoßen",
    "Gelingt dem Helden eine um 4 erschwerte Attacke und misslingt die Verteidigung des Gegners, erleidet dieser minimalen Waffenschaden (wie gewürfelt 1 bei den TP, Bonus durch Schadensschwelle zählt mit) und droht vom Reittier zu stürzen. Er muss sofort eine Probe auf *Reiten (Kampfmanöver)* erschwert um 2 ablegen, bei Misslingen stürzt der Reiter von seinem Reittier und erleidet Sturzschaden (siehe **Regelwerk** Seite **340**).",
    ['CT_13'],
  ),
  kampfImWasser(
    "SA_163",
    "Kampf im Wasser",
    "Für Helden mit dieser Sonderfertigkeit sinken die Erschwernisse beim Kampf im Wasser (siehe **Regelwerk** Seite **239**) um 2.",
    2,
  ),
  kampfstilKombination(
    "SA_164",
    "Kampfstil-Kombination",
    "Mit dieser SF kann der Abenteurer über insgesamt zwei Kampfstile der gleichen Art verfügen, also beispielsweise zwei bewaffnete oder zwei waffenlose Stile (siehe **Aventurisches Kompendium** Seite **145**).\n\nMittels 1 freien Aktion kann der Wechsel zwischen den Kampfstilen eingeleitet werden. Der regeltechnische Wechsel findet am Ende der KR statt. Bis dahin muss noch nach den Regeln des alten Kampfstils gekämpft werden. Um passende Erweiterte SF einzusetzen, muss der Held mit dem dazugehörigen Kampfstil angreifen und auch alle weiteren Voraussetzungen erfüllen.",
    "je nach Kampfstil; die beiden Kampfstile lassen sich jeweils nur für die entsprechenden Kampftechniken nutzen",
  ),
  klingensturm(
    "SA_165",
    "Klingensturm",
    "Die Abenteurerin vermag in 1 Aktion zwei einzelne Attacken zu schlagen. Beide Attacken sind um jeweils 2 erschwert. Der zweite Angriff bekommt einen Malus von -2 TP. Das ausgewürfelte Minimum beträgt aber immer mindestens 1 TP.\n\nDie Angriffe können sich gegen verschiedene Ziele innerhalb der Angriffsdistanz richten. Wird ein Klingensturm mit einem Basismanöver kombiniert, muss dieses für beide Attacken identisch sein. Sollte der Heldin während der ersten AT ein Patzer unterlaufen, verfällt die zweite AT. Das Klingensturm-Manöver kann nicht zusammen mit einem Schild, einer Parierwaffe oder einer weiteren Einhandwaffe kombiniert werden. Der Bonus durch die SF Einhändiger Kampf kann beim Einsatz des Klingensturm benutzt werden.",
    ['CT_4', 'CT_12'],
  ),
  meisterDerImprovisiertenWaffen(
    "SA_166",
    "Meister der improvisierten Waffen",
    "Die Abenteurerin kann improvisierte Waffen ohne Nachteile benutzen. Weder muss sie bereits bei einer gewürfelten 19 bei Attacken und Paraden einen Bestätigungswurf für einen Patzer ablegen, noch erhält der Verteidiger einen Bonus von 2 auf seine Verteidigung bei improvisierten Waffen (siehe **Aventurisches Kompedium** Seite **229**).",
    1,
  ),
  meisterlichesAusweichen(
    "SA_167",
    "Meisterliches Ausweichen",
    "Ein Held mit der SF Meisterliches Ausweichen erleidet bei mehrfachem Ausweichen in einer KR nicht Erschwernisse von jeweils 3, sondern nur von jeweils 2 (siehe **Regelwerk** Seite **232**).",
    [],
  ),
  meisterparade(
    "SA_168",
    "Meisterparade",
    "Eine Heldin mit Meisterparade erleidet bei mehrfachen Paraden in einer KR nicht Erschwernisse von jeweils 3, sondern nur von jeweils 2 (siehe **Regelwerk** Seite **232**).",
    4,
  ),
  pikenwall(
    "SA_169",
    "Pikenwall",
    "Gelangt ein berittener Gegner in die Angriffsdistanz des Helden, darf dieser sofort eine um 2 erschwerte Attacke ausführen. Dies gilt auch dann, wenn der Held über eine niedrigere Initiative verfügt oder der Gegner ein Manöver verwendet, in dem Bewegung und Attacke innerhalb 1 Aktion stattfinden. Die Attacke ist natürlich nicht möglich, wenn dem Helden in dieser KR keine Aktion mehr zur Verfügung steht. Bei einem Pikenwall-Angriff können keine Spezialmanöver durchgeführt werden.",
    ['CT_13'],
  ),
  scharfschuetze(
    "SA_170",
    "Scharfschütze",
    "Die SF erlaubt es der Heldin, aus den Modifikatoren Distanz, Größe und Bewegung resultierende Erschwernisse teilweise zu ignorieren (siehe **Regelwerk** Seite **241**). Bei Stufe I sinken die summierten Erschwernisse um 2, bei Stufe II sinken sie um 4.",
    ['CT_1', 'CT_18', 'CT_2', 'CT_19', 'CT_11', 'CT_14'],
  ),
  schwitzkasten(
    "SA_171",
    "Schwitzkasten",
    "Um einen Feind in den Schwitzkasten zu nehmen, muss die Heldin ihren Widersacher zuvor im Haltegriff haben. In der nächsten KR würfelt die Spielerin eine Raufen-AT. Gelingt sie und es wird nicht erfolgreich verteidigt, ist der Gegner im Schwitzkasten. Misslingt sie, endet der Haltegriff.\n\nIst der Widersacher im Schwitzkasten, erleidet er jede KR 1 SP. Der Gegner muss jede KR eine Probe auf *Selbstbeherrschung (Handlungsfähigkeit bewahren)* ablegen, die erschwert ist um die SP, die in dieser KR verursacht wurden. Bei Misslingen erleidet er 1 Stufe *Betäubung*.\n\nWährend der Gegner im Schwitzkasten ist, stehen ihm zwei Optionen offen:\n\n- Schwitzkasten aufsprengen: Er kann versuchen, den Schwitzkasten zu sprengen. Dazu muss ihm eine Vergleichsprobe auf *Kraftakt (Ziehen & Zerren)* gelingen. War der Widersacher erfolgreich, enden der Schwitzkasten und der Haltegriff.\n- Angreifen: Er kann die Heldin angreifen.\nSolange der Schwitzkasten aufrechterhalten wird, leidet der Feind unter den Status *Fixiert* und *Eingeengt*.",
    ['CT_9'],
  ),
  unterlaufen(
    "SA_172",
    "Unterlaufen",
    "Für jede Stufe dieser SF kann die Heldin eine Stufe Nachteile durch Nahkampfreichweiten gegen Gegner mit längeren Waffen ignorieren (siehe **Regelwerk** Seite **231**). Mit Stufe I lässt sich beispielsweise der Unterschied zwischen kurzer Waffe und mittlerer Waffe überwinden, mit Stufe II sogar der Unterschied zwischen kurz und lang. Kann die Abenteurerin durch Unterlaufen den Reichweitenvorteil nicht komplett ignorieren, sind die Nachteile zumindest um 1 Stufe verringert.\n\nDie Heldin muss das Unterlaufen vor ihrer AT ankündigen. Diese AT ist um die Nahkampfreichweite modifiziert, die nicht durch das Manöver ausgeglichen werden kann.\n\nMisslingt die AT, steht dem Gegner ein Passierschlag zu. Der Vorteil des Manövers gilt nur für einen Angriff. Unterlaufen kann mit keinem Spezialmanöver kombiniert werden.",
    [
      'CT_3',
      'CT_4',
      'CT_5',
      'CT_6',
      'CT_9',
      'CT_10',
      'CT_12',
      'CT_15',
      'CT_16',
    ],
  ),
  verbessertesUnterlaufen(
    "SA_173",
    "Verbessertes Unterlaufen",
    "Ein Abenteurer kann mit dieser SF das Manöver Unterlaufen mit Spezialmanövern kombinieren.",
    [
      'CT_3',
      'CT_4',
      'CT_5',
      'CT_6',
      'CT_9',
      'CT_10',
      'CT_12',
      'CT_15',
      'CT_16',
    ],
  ),
  verteilterEisenhagel(
    "SA_174",
    "Verteilter Eisenhagel",
    "Eine Heldin, die über diese SF verfügt, kann bei Verwendung des Manövers Eisenhagel verschiedene Ziele mit ihren Wurfwaffen angreifen.",
    ['CT_19', 'CT_14'],
  ),
  zweihaendigerReiterkampf(
    "SA_175",
    "Zweihändiger Reiterkampf",
    "Verfügt der Held über diese SF, kann er vom Rücken eines Reittiers aus eine Zweihandwaffe führen und einsetzen. Allerdings sind diese Attacken um 4 erschwert.",
    ['CT_15', 'CT_16'],
  ),
  unterwasserkampf(
    "SA_418",
    "Unterwasserkampf",
    "Für Wesen mit dieser Sonderfertigkeit gelten die Erschwernisse im Kampf unter Wasser nicht (siehe **Regelwerk** Seite **239**).",
    [],
  ),
  auflaufen(
    "SA_860",
    "Auflaufen",
    "Der Held muss entweder eine höhere INI in dieser KR als sein Gegner aufweisen oder in der letzten KR bereits 1 Aktion für dieses Manöver aufgewandt haben, damit er die folgende AT durchführen kann. Außerdem darf er keine Handlung für eine Bewegung im gleichen Zeitraum eingesetzt haben.\n\nDie AT ist um 2 erschwert, dem Angriff kann man nur ausweichen. Sollte das Manöver gelingen, erleidet das Ziel nicht nur den üblichen Schaden der Waffe (bei Lanzen der Schaden, den die Waffe bei einem Lanzenangriff macht), sondern auch die halbe GS des Ziels als zusätzliche TP.",
    ['CT_7', 'CT_21'],
  ),
  spiessgespann(
    "SA_861",
    "Spießgespann",
    "Sollten zwei Kämpfer gleichzeitig eine Waffe mit der Reichweite überlang führen, können sie einen gemeinsamen Angriff gegen ein Ziel durchführen. Die Angriffe beider Kämpfer sind eine jeweils um 4 erschwerte AT. Ein Patzer / kritischer Erfolg eines Kämpfers führt automatisch zu einem Patzer / kritischen Erfolg auch des anderen. Die INI beider wird durch die niedrigere INI beider Kämpfer angegeben. Verfügen beide über die Sonderfertigkeit *Sturmangriff*, können sie diesen ausführen und damit die TP ihres Angriffs um insgesamt 4 + die geringste GS der beiden Angreifer erhöhen. Weitere Manöver können nicht eingesetzt werden.\n\nDer Schaden wird nur einmal ausgewürfelt, nicht von beiden Kämpfern.",
    [],
  ),
  formation(
    "SA_862",
    "Formation",
    "Ein Kämpfer mit dieser Sonderfertigkeit kann zusammen mit bis zu vier weiteren Kämpfern, die sich maximal einen halben Schritt vor, hinter, links und rechts von ihm befinden dürfen, eine Formation aufbauen. Alle Kämpfer, die durch diese Sonderfertigkeit eine Formation bilden, erhalten entweder +2 AT oder +2 VW. Alle Beteiligten müssen sich bei der Bildung der Formation auf einen der beiden Boni einigen.\n\nNur einer der Kämpfer benötigt die SF, damit alle davon profitieren. Die Formation hält solange, wie die Kämpfer in der notwendigen Reichweite zusammenstehen.",
    1,
  ),
  ausfall(
    "SA_864",
    "Ausfall",
    "Um einen Ausfall zu starten, muss eine einleitende AT gelingen, die um 2 erschwert ist. Pro Stufe des Manövers, kann die Heldin innerhalb der selben Aktion 1 zusätzliche AT ausführen. Ob die Verteidigungen des Gegners gelingen, ist dabei unerheblich. Jede zusätzliche AT innerhalb des Ausfalls, ist um weitere 2 Punkte erschwert (also -2 für einleitende AT, -4 für die erste zusätzliche AT, -6 für die zweite zusätzliche AT). Wird eine AT im Ausfall mit einem Basismanöver kombiniert, so profitiert immer nur diese einzelne AT davon. Misslingt eine der AT, ist der Ausfall sofort beendet.\n\nDie Verteidigungen gegen die zusätzlichen AT werden nicht gemäß der Regel für mehrere Verteidigungen in einer KR erschwert (siehe **Regelwerk** Seite **232**), stattdessen ist die Verteidigung des Gegners gegen die erste zusätzliche AT um 4, gegen die zweite zusätzliche AT um 8 erleichtert. Sollte es sich bei einem der Angriffe um einen Kritischen Erfolg handeln, wird der VW des Gegners mit der Erleichterung verrechnet und dann halbiert.\n\nAlle AT in einem Ausfall müssen immer den selben Gegner zum Ziel haben. Ein Kritischer Treffer wird immer nur für die aktuelle AT angewandt. Bis zum Ende der nächsten KR bekommt die Heldin eine Erschwernis von 2 auf Verteidigungen.",
    ['CT_3', 'CT_20', 'CT_4'],
  ),
  beritteneLanzenformation(
    "SA_865",
    "Berittene Lanzenformation",
    "Ein Reiter mit dieser Sonderfertigkeit kann zusammen mit bis zu zwei weiteren Reitern, die sich maximal 3 Schritt links und rechts von ihm befinden dürfen, einen konzentrierten Angriff ausführen. Die Lanzen der Kämpfer müssen in die gleiche Richtung ausgerichtet sein und die Reittiere in die gleiche Richtung galoppieren.\n\nFür jeden Reiter in dieser Formation bekommt das Ziel des Angriffs eine zusätzliche Erschwernis von 1 auf VW.",
    ['CT_7'],
  ),
  blutgraetsche(
    "SA_866",
    "Blutgrätsche",
    "Wer eine Blutgrätsche ausführen will, benötigt dafür 2 Schritt Anlauf. Der Held führt eine Raufen-AT aus, die um 2 erschwert ist. Einer erfolgreichen Attacke kann nur ausgewichen werden. Misslingt die Verteidigung, erleidet der Gegner zusätzlich zum üblichen Schaden +1 TP und den Status *Liegend*. Er muss außerdem eine Probe auf *Selbstbeherrschung* erschwert um 2 ablegen, bei deren Misslingen er zusätzlich noch eine Stufe *Betäubung* erhält. Der Held selbst hat bis zum Ende der nächsten KR eine Erschwernis von 2 auf VW und erleidet automatisch den Status *Liegend*.",
    ['CT_9'],
  ),
  doppelangriff(
    "SA_867",
    "Doppelangriff",
    "Der Doppelangriff muss im Beidhändigen Kampf angewandt werden. Zusätzlich zu den Modifikatoren im Beidhändigen Kampf ist die erste AT des Helden um 2 erschwert, die zweite AT um 2 erleichtert. Alle Verteidigungen des Helden in dieser Kampfrunde entfallen. Die Verteidigung des Gegners gegen beide Angriffe sinkt um 2. Misslingt eine der beiden Attacken, so ist die Verteidigung des Gegners nicht gesenkt, aber der Held verliert dennoch alle Verteidigungen. Diese Spezialmanöver kann im Beidhändigen Kampf eingesetzt werden, obwohl dabei üblicherweise nur Basismanöver erlaubt sind.",
    ['CT_3', 'CT_20', 'CT_4', 'CT_5', 'CT_12'],
  ),
  drachenkampfTaktik(
    "SA_868",
    "Drachenkampf-Taktik",
    "Durch die Sonderfertigkeit erwirbt der Held eine Einsatzmöglichkeit für das Talent *Kriegskunst*. Im Kampf gegen Drachen kann er 1 Aktion aufwenden, um eine Probe auf *Kriegskunst* abzulegen. Bei Erfolg erhält er für die Dauer von QS KR einen Bonus von +2 AT und +2 FK.",
    1,
  ),
  durchgezogenerTritt(
    "SA_869",
    "Durchgezogener Tritt",
    "Die TP des Angriffs erhöhen sich pro Stufe der Sonderfertigkeit um +1 TP. Zudem muss der Gegner eine Probe auf *Körperbeherrschung (Balance)* bestehen, um nicht den Status *Liegend* zu erhalten. Die Probe ist pro Stufe der Sonderfertigkeit um 1 erschwert. Der VW der Heldin sinkt bis zum Ende der nächsten KR um die Stufe der Sonderfertigkeit.",
    ['CT_9'],
  ),
  ellbogenangriff(
    "SA_870",
    "Ellbogenangriff",
    "Die TP des Angriffs erhöhen sich pro Stufe der Sonderfertigkeit um +1 TP. Außerdem muss der Gegner des Helden eine Probe auf *Selbstbeherrschung (Handlungsfähigkeit bewahren)* bestehen, um nicht 1 Stufe *Betäubung* zu erhalten. Die Probe ist pro Stufe der Sonderfertigkeit um 1 erschwert. Die AT des Helden sinkt bis zum Ende der nächsten KR um die Stufe der Sonderfertigkeit.",
    ['CT_9'],
  ),
  gefechtsformation(
    "SA_871",
    "Gefechtsformation",
    "Eine Kämpferin mit dieser Sonderfertigkeit kann zusammen mit bis zu vier weiteren Kämpfern, die sich maximal einen halben Schritt vor, hinter, links und rechts von ihr befinden dürfen, eine Gefechtsformation aufbauen. Alle Kämpfer, die durch diese Sonderfertigkeit eine Gefechtsformation bilden, erhalten entweder +1 AT und +2 VW, oder +2 AT und +1 VW. Alle Beteiligten müssen sich bei der Bildung der Gefechtsformation auf einen der beiden Boni einigen.\n\nNur einer der Kämpfer benötigt die Sonderfertigkeit, damit alle davon profitieren. Verfügen mehrere Kämpfer darüber, können auch entsprechend mehr Kämpfer die Vorteile nutzen.",
    1,
  ),
  gegenhalten(
    "SA_872",
    "Gegenhalten",
    "Die Heldin kann sich bei einem Angriff des Gegners nach dessen gelungener AT entscheiden, statt auf PA zu würfeln, ein Gegenhalten-Manöver zu starten (beim Ausweichen ist dieses Manöver nicht einsetzbar). Dazu muss eine Probe auf AT gewürfelt werden. Gelingt die AT, so hat die Heldin den Angriff abgewehrt. Misslingt die Probe, so konnte nicht pariert werden und der Gegner verursacht zusätzlich zu seinem üblichen Schaden +2 TP. Nach jedem Gegenhalten-Manöver erhält die Heldin 1 Stufe *Betäubung*. Gegenhalten zählt in diesem Sinne als eine Verteidigung und erschwert nachfolgende Verteidigungen. Weitere Verteidigungen in der selben KR sind wie üblich erschwert, gleich ob dazu wieder Paraden, Ausweichen oder erneut Gegenhalten verwendet wird.",
    4,
  ),
  geschossabwehr(
    "SA_873",
    "Geschossabwehr",
    "Um sich gegen einen Angriff mit Wurfwaffen zu verteidigen, würfelt der Held statt einer Probe auf Ausweichen eine Raufen-PA. Gelingt sie, hat er die geworfene Waffe erfolgreich abgewehrt (aber nicht gefangen). Es gelten folgende Modifikatoren für die Raufen-Parade:\n\n- improvisierte Wurfwaffen: +/-0\n- alle anderen Wurfwaffen: -2\n- Wurfspeere, Wurfdiskus: -4\n- geworfene Nahkampfwaffen (z. B. durch die SF Waffenwurf (siehe **Aventurisches Kompendium** Seite **165**): -6\n\nMunition von Bögen und Armbrüsten lässt sich durch diese SF nicht abwehren.\n\nJede Stufe nach der ersten erleichtert die Raufen-PA um jeweils 2. Eine misslungene Probe bedeutet, dass die Verteidigung misslungen ist. Der Held muss für den Einsatz des Manövers eine Hand frei haben.",
    ['CT_9'],
  ),
  graetsche(
    "SA_874",
    "Grätsche",
    "Wer eine Grätsche ausführen will, benötigt dafür 2 Schritt Anlauf. Der Held führt eine Raufen-AT aus, die um 2 erschwert ist. Einer erfolgreichen Attacke kann nur ausgewichen werden. Misslingt die Verteidigung, erleidet der Gegner den üblichen Schaden und den Status *Liegend*. Der Held selbst hat bis zum Ende der nächsten KR eine Erschwernis von 2 auf Verteidigungen und erleidet automatisch den Status *Liegend*.",
    ['CT_9'],
  ),
  kernschuss(
    "SA_875",
    "Kernschuss",
    "Üblicherweise darf eine im Nahkampf verwickelte Heldin keinen Fernkampfangriff durchführen (siehe **Regelwerk** Seite **241**). Mit dieser Sonderfertigkeit ist sie jedoch in der Lage, selbst im Nahkampf noch Fernkampfangriffe durchzuführen. Sollte sie sich also in Angriffsdistanz eines Gegners befinden, ist sie trotzdem noch in der Lage, einen Pfeil abzuschießen oder eine Wurfaxt zu werfen. Bei Stufe I ist die Probe auf FK um 4, bei Stufe II um 2 und bei Stufe III gar nicht mehr erschwert.",
    3,
  ),
  khaFormation(
    "SA_876",
    "Kha-Formation",
    "Ein Kämpfer mit dieser Sonderfertigkeit kann zusammen mit bis zu vier weiteren Kämpfern, die sich  maximal einen halben Schritt vor, hinter, links und rechts von ihm befinden dürfen, eine Kha-Formation aufbauen. Alle Kämpfer müssen zum bilden dieser Formationen mit einem Schild bewaffnet sein, der einen PA-Modifikator von +3 oder besser aufweist.\n\nAlle Kämpfer, die durch diese Sonderfertigkeit eine Kha-Formation bilden, erhalten +3 VW und zusätzlich +6 VW gegen Fernkampfangriffe. Die Kämpfer in Kha-Formation können sich maximal mit GS 2 bewegen. Bewegen sie sich schneller, verfällt der Bonus auf VW augenblicklich.\n\nNur einer der Kämpfer benötigt die Sonderfertigkeit, damit alle davon profitieren. Verfügen mehrere Kämpfer darüber, können auch entsprechend mehr Kämpfer die Vorteile nutzen.",
    1,
  ),
  klingeDrehen(
    "SA_877",
    "Klinge drehen",
    "Nach einer gelungenen AT, die mindestens 5 SP angerichtet hat, kann die Heldin die Klinge in der Wunde drehen. Dies verursacht zusätzlich 2 SP und der Gegner muss eine Probe auf *Selbstbeherrschung (Störungen ignorieren)* ablegen. Misslingt die Probe, so erleidet er bis zum Ende der nächsten KR 1 Stufe *Schmerz*. Die angreifende Heldin erleidet für den gleichen Zeitraum eine Erschwernis von 2 auf den VW.",
    "Dolche, Fechtwaffen, Schwerter, Stangenwaffen (muss eine spitze Klinge haben)",
  ),
  klingentaenzer(
    "SA_878",
    "Klingentänzer",
    "Ein Klingentänzer würfelt bei der Bestimmung der Initiative zusätzlich +1W6 (also in der Regel insgesamt 2W6). Um die Sonderfertigkeit nutzen zu können, dürfen keine Modifikatoren durch BE oder zusätzliche Abzüge auf GS oder INI vorhanden sein.",
    1,
  ),
  kraftvollerSpeerwurf(
    "SA_879",
    "Kraftvoller Speerwurf",
    "Setzt ein Held diese Sonderfertigkeit ein, erhöhen sich die TP seines Angriffs um 2. Wird der Gegner getroffen, muss er eine Probe auf *Körperbeherrschung (Balance)* erschwert um 2 ablegen, bei deren Misslingen er den Status *Liegend* erhält. Die Reichweiten des Wurfspeers beim Einsatz des Manövers werden halbiert.",
    "Wurfwaffen (nur Wurfspeere)",
  ),
  lanzenfuehrung(
    "SA_880",
    "Lanzenführung",
    "Der Held kann mit Lanzen, die normalerweise nur in einem Lanzenangriff eingesetzt werden können, Attacken und Paraden im Nahkampf als Fußkämpfer ausführen. Anders als bei der Führung beim Lanzenangriff, verfügt der Held in diesem Fall über eine Parade mit der Lanze. Dabei werden AT und PA nach den normalen Regeln berechnet. Allerdings erleidet er Erschwernisse von 6 auf AT und 4 auf PA. Die TP eines solchen Angriffs sind halbiert, die L+S beträgt KK 16 und die Reichweite der Lanze ist lang. Diese SF kann nicht vom Rücken eines Reittiers aus eingesetzt werden.",
    ['CT_7'],
  ),
  machtvolleMeisterparade(
    "SA_881",
    "Machtvolle Meisterparade",
    "Ein Held mit dieser Sonderfertigkeit erleidet bei mehrfachen Paraden in einer KR nicht Erschwernisse von jeweils 3, sondern nur von jeweils 1 (siehe **Regelwerk** Seite **232**).",
    4,
  ),
  meisterlicheGeschossabwehr(
    "SA_882",
    "Meisterliche Geschossabwehr",
    "Der Held würfelt bei der Verteidigung gegen Wurfwaffen statt einer Probe auf Ausweichen eine Raufen- PA. Gelingt sie, hat er die geworfene Waffe erfolgreich gefangen. Es gelten folgende Modifikatoren für die Raufen-Parade:\n\n- improvisierte Wurfwaffen: -2\n- alle anderen Wurfwaffen: -4\n- Wurfspeere, Wurfdiskus: -6\n- geworfene Nahkampfwaffen (z. B. durch die SF *Waffenwurf* (siehe **Aventurisches Kompendium** Seite **165**): -8\n\nMunition von Bögen und Armbrüsten lässt sich durch diese SF nicht fangen.\n\nJede Stufe nach der ersten erleichtert die einzelnen Proben um jeweils 2. Eine misslungene Probe bedeutet, dass die Verteidigung misslungen ist. Der Held muss für den Einsatz des Manövers eine Hand frei haben. Will er die Waffe für einen FK-Angriff einsetzen, muss er die reguläre LZ der Waffe aufwenden, bevor er einen Angriff ausführen kann.",
    ['CT_9'],
  ),
  meisterlicherKlingentaenzer(
    "SA_883",
    "Meisterlicher Klingentänzer",
    "Ein meisterlicher Klingentänzer bekommt +1/+2/+3 auf Verteidigung, wenn er beim würfeln seiner Initiative mit 2W6 ein Würfelergebnis von mindestens 3/7/11 erzielt. Um die Sonderfertigkeit nutzen zu können, dürfen keine Modifikatoren durch BE oder zusätzliche Abzüge auf GS oder INI vorhanden sein.",
    1,
  ),
  plaenklerFormation(
    "SA_884",
    "Plänkler-Formation",
    "Ein Kämpfer mit dieser Sonderfertigkeit kann zusammen mit bis zu zwei weiteren Kämpfern, die sich maximal einen halben Schritt rechts und links von ihm befinden müssen, eine Schlachtreihe aufstellen. Alle Kämpfer, die durch diese SF eine Plänkler-Formation bilden, erhalten entweder +1 AT oder +1 VW. Alle Beteiligten müssen sich bei der Bildung der Formationen auf einen der beiden Boni einigen.\n\nNur einer der Kämpfer benötigt die Sonderfertigkeit, damit alle davon profitieren. Verfügen mehrere Kämpfer darüber, können auch entsprechend mehr Kämpfer die Vorteile nutzen.",
    1,
  ),
  querschuss(
    "SA_885",
    "Querschuss",
    "Beim Spannen des Bogens, also bei der 1. Aktion des Ladens, muss der Querschuss angekündigt werden. Pro Stufe der Sonderfertigkeit kann der Schuss +1 TP anrichten, ist aber auch um jeweils 1 erschwert. Es kommt zudem häufiger zu Patzern: Bei Stufe I bei 19-20, bei Stufe II bei 18-20, bei Stufe III bei 17-20 bzw. die Chance für einen Patzer steigt pro Stufe der SF um 5 %.",
    ['CT_2'],
  ),
  reissangriff(
    "SA_886",
    "Reißangriff",
    "Nach einer gelungenen und unverteidigten AT darf der Spieler des Helden eine Probe auf *Kraftakt (Ziehen & Zerren)* ablegen. Nach der Probe kann er sich dazu entscheiden, entweder QS/2 zusätzliche SP anzurichten oder die Verteidigung des Gegners um den gleichen Wert bis zum Ende der nächsten KR zu erschweren. Die AT des Helden ist bis zum Ende der nächsten KR um 2 gesenkt. Die Probe auf *Kraftakt* muss nicht eingesetzt werden, wenn sich der Held dagegen entscheidet.",
    ['CT_6'],
  ),
  schildschlag(
    "SA_887",
    "Schildschlag",
    "Das Schildschlag-Manöver kann nur gegen einen Gegner mit dem Status *Liegend* eingesetzt werden. Der Attackewert des Helden mit dem Schild ist bei diesem Manöver um 2 erleichtert. Gelingt der Angriff und verteidigt der Gegner nicht, werden die TP des Schilds verdoppelt, danach noch für einen kleinen/mittleren/großen Schild +-0/+1/+2 TP addiert.",
    [],
  ),
  turnierreiterei(
    "SA_888",
    "Turnierreiterei",
    "Während eines Turniers kann die Heldin in den Disziplinen Ring- und Schildstechen sowie Tjoste jeweils einen beliebigen eigenen Würfelwurf wiederholen, bei welchem das für sie bessere Ergebnis zählt. Dabei ist es unerheblich, ob es sich um einen W6- oder W20-Wurf handelt oder für welchen Zweck er benutzt wurde. Es kann ein Wurf sein, um die TP zu bestimmen, oder eine Teilprobe von *Reiten* (nicht aber die gesamte Probe), eine AT usw.\n\nSollte die Heldin während des Turniers den Wiederholungswurf für eine der drei Disziplinen benutzt haben, kann sie die Fähigkeit auch noch für die anderen beiden einsetzen, aber nicht mehr für die gleiche Disziplin.",
    ['CT_7'],
  ),
  umrennen(
    "SA_889",
    "Umrennen",
    "Gelingt eine um 2 erschwerte AT und misslingt die Verteidigung, verursacht der Angriff der Heldin zwar nur TP/2, allerdings muss der Gegner eine Probe auf *Körperbeherrschung (Kampfmanöver)* erschwert um die angerichteten TP bestehen, um nicht den Status *Liegend* sowie 1 Stufe *Betäubung* zu erhalten. Die *Betäubung* hält allerdings nur bis zum Ende der nächsten KR an.",
    ['CT_9'],
  ),
  umwickeln(
    "SA_890",
    "Umwickeln",
    "Für das Umwickeln wird eine Attacke gegen die Waffe durchgeführt, gegen die der Gegner mit einer Parade  mit der Waffe oder Ausweichen verteidigen darf. Misslingt die Parade oder das Ausweichen, muss der Held eine Probe auf *Kraftakt (Ziehen & Zerren)* ablegen und kann bis zum Ende der nächsten KR die AT und PA des Gegners um QS/2 erschweren. Der Angriff richtet ansonsten keinen Schaden an. Der Held kann während die Erschwernis wirkt, das Manöver gegen den Gegner nicht nochmal einsetzen",
    ['CT_6', 'CT_8'],
  ),
  ungeheuerTaktik(
    "SA_891",
    "Ungeheuer-Taktik",
    "Durch die Sonderfertigkeit erwirbt der Held eine Einsatzmöglichkeit für das Talent *Kriegskunst*. Im Kampf gegen ein bestimmtes Ungeheuer kann er 1 Aktion aufwenden, um eine Probe auf *Kriegskunst* abzulegen. Bei Erfolg erhält er QS in Kampfrunden einen Bonus von +2 AT und +2 FK.",
    1,
  ),
  weitwurf(
    "SA_892",
    "Weitwurf",
    "Würfe mit Waffen der Kampftechniken Wurfwaffen haben in der Reichweitenkategorie *weit* eine um 50 % höhere Reichweite. Beispielsweise würde ein Wurfspeer mit einer Reichweite von 40 Schritt in der Kategorie weit durch einen Weitwurf eine maximale Reichweite von 60 Schritt erreichen. Ein Weitwurf ist um 2 erschwert.",
    [],
  ),
  wirbelangriff(
    "SA_893",
    "Wirbelangriff",
    "Die angegriffenen Gegner dürfen auf den Angriff getrennt reagieren. Die erste Attacke ist um 2, die zweite um 4 und die dritte um 6 erschwert. Wenn die Verteidigung der Gegner misslingt, wird für jeden Gegner einzeln Schaden ausgewürfelt.\n\nWirbelangriff I erlaubt den Angriff auf zwei Gegner, Wirbelangriff II den Angriff auf drei Gegner.\n\nEin Patzer bei einem der Angriffe bedeutet, dass keine weiteren Attacken des  Wirbelangriffs in dieser KR ausgeführt werden können.\n\nEin Treffer richtet 2 TP weniger an als üblich (bis zu einem Minimum von 0 TP).",
    ['CT_3', 'CT_20', 'CT_4', 'CT_9'],
  );

  final String id;
  final String name;
  final String rules;
  final dynamic ct;

  const SpecialAbilityBase(this.id, this.name, this.rules, this.ct);
}

const specialCombatAbilities = {
  "SA_41": SpecialAbilityBase.belastungsgewoehnung,
  "SA_42": SpecialAbilityBase.beidhaendigerKampf,
  "SA_43": SpecialAbilityBase.berittenerKampf,
  "SA_44": SpecialAbilityBase.berittenerSchuetze,
  "SA_45": SpecialAbilityBase.einhaendigerKampf,
  "SA_46": SpecialAbilityBase.entwaffnen,
  "SA_47": SpecialAbilityBase.feindgespuer,
  "SA_48": SpecialAbilityBase.finte,
  "SA_49": SpecialAbilityBase.haltegriff,
  "SA_50": SpecialAbilityBase.hammerschlag,
  "SA_51": SpecialAbilityBase.kampfreflexe,
  "SA_52": SpecialAbilityBase.klingenfaenger,
  "SA_53": SpecialAbilityBase.kreuzblock,
  "SA_54": SpecialAbilityBase.lanzenangriff,
  "SA_55": SpecialAbilityBase.praeziserSchussWurf,
  "SA_56": SpecialAbilityBase.praeziserStich,
  "SA_57": SpecialAbilityBase.riposte,
  "SA_58": SpecialAbilityBase.rundumschlag,
  "SA_59": SpecialAbilityBase.schildspalter,
  "SA_60": SpecialAbilityBase.schnellladen,
  "SA_61": SpecialAbilityBase.schnellziehen,
  "SA_62": SpecialAbilityBase.sturmangriff,
  "SA_63": SpecialAbilityBase.todesstoss,
  "SA_64": SpecialAbilityBase.verbessertesAusweichen,
  "SA_65": SpecialAbilityBase.verteidigungshaltung,
  "SA_66": SpecialAbilityBase.vorstoss,
  "SA_67": SpecialAbilityBase.wuchtschlag,
  "SA_68": SpecialAbilityBase.wurf,
  "SA_69": SpecialAbilityBase.zuFallBringen,
  "SA_151": SpecialAbilityBase.armbrustUeberdrehen,
  "SA_152": SpecialAbilityBase.aufDistanzHalten,
  "SA_153": SpecialAbilityBase.ballistischerSchuss,
  "SA_154": SpecialAbilityBase.berittenerFlugkampf,
  "SA_155": SpecialAbilityBase.beschuetzer,
  "SA_156": SpecialAbilityBase.betaeubungsschlag,
  "SA_157": SpecialAbilityBase.blindkampf,
  "SA_158": SpecialAbilityBase.eisenhagel,
  "SA_159": SpecialAbilityBase.festnageln,
  "SA_160": SpecialAbilityBase.gezielterAngriff,
  "SA_161": SpecialAbilityBase.gezielterSchuss,
  "SA_162": SpecialAbilityBase.herunterstossen,
  "SA_163": SpecialAbilityBase.kampfImWasser,
  "SA_164": SpecialAbilityBase.kampfstilKombination,
  "SA_165": SpecialAbilityBase.klingensturm,
  "SA_166": SpecialAbilityBase.meisterDerImprovisiertenWaffen,
  "SA_167": SpecialAbilityBase.meisterlichesAusweichen,
  "SA_168": SpecialAbilityBase.meisterparade,
  "SA_169": SpecialAbilityBase.pikenwall,
  "SA_170": SpecialAbilityBase.scharfschuetze,
  "SA_171": SpecialAbilityBase.schwitzkasten,
  "SA_172": SpecialAbilityBase.unterlaufen,
  "SA_173": SpecialAbilityBase.verbessertesUnterlaufen,
  "SA_174": SpecialAbilityBase.verteilterEisenhagel,
  "SA_175": SpecialAbilityBase.zweihaendigerReiterkampf,
  "SA_418": SpecialAbilityBase.unterwasserkampf,
  "SA_860": SpecialAbilityBase.auflaufen,
  "SA_861": SpecialAbilityBase.spiessgespann,
  "SA_862": SpecialAbilityBase.formation,
  "SA_864": SpecialAbilityBase.ausfall,
  "SA_865": SpecialAbilityBase.beritteneLanzenformation,
  "SA_866": SpecialAbilityBase.blutgraetsche,
  "SA_867": SpecialAbilityBase.doppelangriff,
  "SA_868": SpecialAbilityBase.drachenkampfTaktik,
  "SA_869": SpecialAbilityBase.durchgezogenerTritt,
  "SA_870": SpecialAbilityBase.ellbogenangriff,
  "SA_871": SpecialAbilityBase.gefechtsformation,
  "SA_872": SpecialAbilityBase.gegenhalten,
  "SA_873": SpecialAbilityBase.geschossabwehr,
  "SA_874": SpecialAbilityBase.graetsche,
  "SA_875": SpecialAbilityBase.kernschuss,
  "SA_876": SpecialAbilityBase.khaFormation,
  "SA_877": SpecialAbilityBase.klingeDrehen,
  "SA_878": SpecialAbilityBase.klingentaenzer,
  "SA_879": SpecialAbilityBase.kraftvollerSpeerwurf,
  "SA_880": SpecialAbilityBase.lanzenfuehrung,
  "SA_881": SpecialAbilityBase.machtvolleMeisterparade,
  "SA_882": SpecialAbilityBase.meisterlicheGeschossabwehr,
  "SA_883": SpecialAbilityBase.meisterlicherKlingentaenzer,
  "SA_884": SpecialAbilityBase.plaenklerFormation,
  "SA_885": SpecialAbilityBase.querschuss,
  "SA_886": SpecialAbilityBase.reissangriff,
  "SA_887": SpecialAbilityBase.schildschlag,
  "SA_888": SpecialAbilityBase.turnierreiterei,
  "SA_889": SpecialAbilityBase.umrennen,
  "SA_890": SpecialAbilityBase.umwickeln,
  "SA_891": SpecialAbilityBase.ungeheuerTaktik,
  "SA_892": SpecialAbilityBase.weitwurf,
  "SA_893": SpecialAbilityBase.wirbelangriff,
};

class SpecialAbility {
  final SpecialAbilityBase value;
  final int? tier;

  SpecialAbility(this.value, this.tier);

  Map<String, dynamic> toJson() {
    if (tier != null) {
      return {"tier": tier};
    } else {
      return {};
    }
  }

  @override
  String toString() {
    if (tier != null) {
      return "${value.name} $tier";
    } else {
      return value.name;
    }
  }
}
