name: Unit Tests
on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "code_testing"
  cancel-in-progress: false

jobs:
  testing_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout including submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Inject DB fields
        run: dart run build_runner build
      
      - name: Run tests
        run: flutter test -r github
